### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by Addonman** [frozn/TipTac#1]
Are you nameing your versions by date? if its so its 2021 not 2020.

**Comment by frozn** [comment]
Funny. I grabbed the latest version number from curseforge (20.11.04) and made 2 changes and increment only the last number twice.  Didn't think about it being related to the current date, even if day and month happen to be the same today. 😄

Nevertheless I updated the version number: https://github.com/frozn/TipTac/releases/tag/v21.11.06
