### ISSUE TITLE
Attempt to access forbidden object from code tainted by an AddOn

### ISSUE THREAD

**Issue by kwonjt0501** [frozn/TipTac#100]
You are doing well. I always get the same error as in the screenshot while playing Mythic+, but I'm not sure exactly when it happens.
But the person next to me playing games like me doesn't happen.
The difference is that the ally name tag is turned on and off, but an error occurs when the ally name tag is turned on.
![error_1](https://user-images.githubusercontent.com/114258227/192042539-f6586d83-e35d-4654-9dd4-b4aebce9109a.png)
![error_2](https://user-images.githubusercontent.com/114258227/192042550-80f69f59-6594-4835-81cb-48fc07d5be8f.png)
![error_3](https://user-images.githubusercontent.com/114258227/192042557-a6f0ce18-0692-4851-9aea-69ac856f9e95.png)

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
