### ISSUE TITLE
Anchor not working

### ISSUE THREAD

**Issue by kingreboot** [frozn/TipTac#108]
With DF, it seems like tool tip won't anchor to the point I have set it

**Comment by kingreboot** [comment]
Was an issue with Leatrix, not your addon

**Comment by frozn** [comment]
Nevertheless good to know, that there are issues in combination with leatrix addon. 👍

**Comment by Rycia** [comment]
This is till an issue with the Leatrix addon.

**Comment by frozn** [comment]
If you enabled "Interface->Enhance tooltip" in Leatrix make shure you disable anchor modifications there (click on gear symbol, set "Anchor = None") to prevent interfering with TipTac.

If there are other problems, I need further informations to reproduce this.
