### ISSUE TITLE
BUG Border of Tool Tip changes random

### ISSUE THREAD

**Issue by Vilogity** [frozn/TipTac#117]
Hmm hard to explain.... It's a curious Bug
I set the TipTac Border to Class Color in Menu Collors and then in Menu Backdrop: Blizzard Tooltip enlarged and Texture of BlizzardTooltip.
When I log in, sometimes all is fine.
Then I log in to a other Char and then it looks different and i have a thin Border see in PIC 2
When I log in to my Priest again, I also have a thin Border ?!
Later I log in to my Pala, then the Border is so I chose it, like in Pic 1.
Sometimes when i make a Reload ui, then it looks like normal again.

This changes random and i dont know why?!
I disable all other stuff for Tooltip in elv ui
I deledet all stuff in WTF Folder and set my Fav new, works maybe one Day.   

![WoWScrnShot_110122_065653 (2)](https://user-images.githubusercontent.com/35414453/199174962-c8b952e3-0f94-4d0f-8bfc-8c5e311c1b7e.jpg)
![WoWScrnShot_test](https://user-images.githubusercontent.com/35414453/199174965-7ec83e5d-07e0-4e0d-a840-2f467cdd19a3.jpg)

**Comment by Vilogity** [comment]
Hi Frozn
You can close this case, I fond the real Problem with a test, then I dont believe it's a real TipTac Bug.....
I use Elvui with Merathilis UI, and it's a MerathilisUI Problem, without MerathilisUI all is fine.
I think it's a Skin Problem........or what ever, I test it over 4 H now, and it works without MerathilisUI.

sry

**Comment by frozn** [comment]
Nevertheless I took a look at MerathilisUI anyway and found a possible solution to prevent styling of frames who already were styled by TipTac. Here's a dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/9914057/TipTac-dev.zip)

Can you test with MerathilisUI again?

**Comment by Vilogity** [comment]
I'm on it.

**Comment by Vilogity** [comment]
Ok, tested the dev version, an yes, after disable the Skin in ELVUI it works.
Enable, after a few minutes becomes a Thin Border....

**Comment by frozn** [comment]
I installed ElvUI and ElvUI_MerathilisUI myself and tested it. I added another modification and here's the actual dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/9923898/TipTac-dev.zip)

Works for me including enabled skinning of tooltip (both in ElvUI and ElvUI_MerathilisUI)... for you too? 😉

**Comment by Vilogity** [comment]
I Donwload and check.

**Comment by Vilogity** [comment]
So, tested this several Hours in M+ and normal Gaming with Enabled and Disabled Skins and i have no Problems with changing the Border.
This works.
THX Frozn :-)

**Comment by frozn** [comment]
Yeah, great news! :partying_face:
