### ISSUE TITLE
[Bug] Changing Backdrop Inset property causes item tooltips to "flicker" on render

### ISSUE THREAD

**Issue by Kethion** [frozn/TipTac#118]
Hi,
I noticed some strange behavior when adjusting the backdrop inset away from the default of 2.5. From what I can gather, it seems to adjust the border location from the default inset of 2.5 to the user specified inset after rendering, causing a sort of flicker. This only happens for item tooltips for some reason, and occurs for me even when it's the only setting adjusted from default. I haven't found another setting that is involved in this behavior so I think it may just be an issue with the setting itself.

**Comment by frozn** [comment]
You're right, I can reproduce it. Searching for a fix. 👍

**Comment by Voxxel** [comment]
I got the flicker too. I think it's a returning bug, it was once in the original TipTac too years ago.

**Comment by frozn** [comment]
Fixed with release [v22.11.14](https://github.com/frozn/TipTac/releases/tag/v22.11.14-release).
