### ISSUE TITLE
Tooltip for SpellFlyoutButton(?)s

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#12]
Dunno what is that button frame

SpellFlyoutButton? when i clicked that button pops up multi spell buttons.

Icons didn't show up to that frames.

https://imgur.com/a/FecpLPD

**Comment by frozn** [comment]
Do you have activated "ItemRef->Smart Icon Appearance"? If yes, it's correct that they didn't pop up, because an icon is already shown (on the button).

**Comment by hobulian** [comment]
> Do you have activated "ItemRef->Smart Icon Appearance"? If yes, it's correct that they didn't pop up, because an icon is already shown (on the button).

I didn't activated Smart icon feature. Only that button that aggregate other spells(by form of SpellFlyoutButton) doesn't have tooltip icon i think. It's same to SL M+ dungeon portals. 
https://imgur.com/a/lS9Gxap

**Comment by frozn** [comment]
I added border color and infos for flyouts and pet actions (config options under "ItemRef"). That was pretty nasty to implement... :weary:

I committed these changes to the main-branch. I already had a look at it, but could you possibly also take a look in whether the issues are fixed?

I can't check the part with the SL M+ dungeon portals yet. I'm on here.

I didn't built a new release yet... I want to merge several bugfixes/enhancements, so that not too many announcements have to be made. The releases currently have to be installed manually, which is otherwise too time-consuming for the people.

**Comment by hobulian** [comment]
> I added border color and infos for flyouts and pet actions (config options under "ItemRef"). That was pretty nasty to implement... 😩
> 
> Spells in macros on action bar should also work now.
> 
> I committed these changes to the main-branch. I already had a look at it, but could you possibly also take a look in whether the issues are fixed?
> 
> I can't check the part with the SL M+ dungeon portals yet. I'm on here.
> 
> I didn't built a new release yet... I want to merge several bugfixes/enhancements, so that not too many announcements have to be made. The releases currently have to be installed manually, which is otherwise too time-consuming for the people.

I've checked your workout . It's quite great work. Except if you put flyoutbutton into actionbar, seems not working. It works quite fine when in spell book!

**Comment by frozn** [comment]
Strange... my flyout buttons with mage portals or warlock daemons are working fine (with Bartender4 enabled for my action bars and without).

**Comment by hobulian** [comment]
> Strange... my flyout buttons with mage portals or warlock daemons are working fine (with Bartender4 enabled for my action bars and without).

Oh it's working now maybe I mis implemented fixed codes. My bad.

**Comment by frozn** [comment]
In the near future, I probably won't be able to do a +20 mythic dungeon to get an M+ dungeon portal. Do you eventually have on of them unlocked yet? If yes, do the flyouts of the M+ dungeon portals work with the current changes?

**Comment by hobulian** [comment]
> In the near future, I probably won't be able to do a +20 mythic dungeon to get an M+ dungeon portal. Do you eventually have on of them unlocked yet? If yes, do the flyouts of the M+ dungeon portals work with the current changes?

I unlocked them and it worked :)

**Comment by frozn** [comment]
That are great news! Then this issue should be solved.
