### ISSUE TITLE
Mouse over crafting mat icon issue

### ISSUE THREAD

**Issue by JnX3r** [frozn/TipTac#120]
25x Interface/AddOns/TipTacItemRef/ttItemRef.lua:772: attempt to call field 'GetRecipeReagentItemLink' (a nil value)

**Comment by frozn** [comment]
Duplicate of #109. Fixed with release [v22.10.30](https://github.com/frozn/TipTac/releases/tag/v22.10.30). Nevertheless thanks for reporting this! 👍
