### ISSUE TITLE
Not sure if my issue is with TipTac or not

### ISSUE THREAD

**Issue by bubfeeld** [frozn/TipTac#121]
13x ...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:616: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:616: in function <...ns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:596>
[string "@Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua"]:644: in function `OnEnter'
[string "@Interface/AddOns/ChocolateBar/Chocolate.lua"]:266: in function <Interface/AddOns/ChocolateBar/Chocolate.lua:235>

Locals:
cfg = <table> {
 fontFace = "VuhDo\Fonts\ariblk.ttf"
 classification_elite = "Level %s|cffffcc00 Elite"
 iconFaction = true
 overrideFade = true
 tipBackdropEdge = "Tooltips\UI-Tooltip-Border"
 optionsLeft = 141.578949
 backdropEdgeSize = 16
 reactText = true
 showTarget = "last"
 powerBar = false
 anchorFrameUnitPoint = "CENTER"
 tipColor = <table> {
 }
 hideDefaultBar = false
 healthBar = false
 colRace = "|cffddeeaa"
 showDebuffs = false
 classification_normal = "Level %s"
 colLevel = "|cffffcc00"
 classification_minus = "-%s "
 fontSize = 16
 classification_rare = "Level %s|cffff66ff Rare"
 fontSizeDeltaHeader = 2
 showBuffs = false
 left = 1314.340332
 reactColoredBackdrop = true
 anchorWorldUnitPoint = "CENTER"
 classification_trivial = "~%s "
 backdropInsets = 4
 modifyFonts = true
 classification_worldboss = "Level %s|cffff0000 Boss"
 tipBorderColor = <table> {
 }
 anchorWorldTipPoint = "CENTER"
 manaBar = false
 iconClass = true
 classification_rareelite = "Level %s|cffffaaff Rare Elite"
 optionsBottom = 335.500000
 fadeTime = 0.784819
 targetYouText = "<<YOU>>"
 iconSize = 26.472673
 top = 638.181274
 preFadeTime = 0.784819
 barFontFace = "Fonts\FRIZQT__.TTF"
 fontSizeDeltaSmall = -2
 fontFlags = "THICKOUTLINE"
 barFontSize = 12
 anchorFrameTipPoint = "CENTER"
 tipBackdropBG = "Tooltips\UI-Tooltip-Background"
}
(*temporary) = nil
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = "VERTICAL"
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0.800000
(*temporary) = 0.800000
(*temporary) = 0.800000
(*temporary) = 0.200000
(*temporary) = "attempt to call method 'SetGradientAlpha' (a nil value)"
tiptacBG = <table> {
 bgFile = "Tooltips\UI-Tooltip-Background"
 tile = false
 edgeSize = 16
 edgeFile = "Tooltips\UI-Tooltip-Border"
 insets = <table> {
 }

[i left out part of the error message with my characters names and such]

}
f = AraReputation {
 0 = <userdata>
 Center = Texture {
 }
 TopLeftCorner = Texture {
 }
 onBlock = true
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.lua:1071
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 AddModule = <function> defined @Interface/AddOns/Ara_Broker_Reputations/Ara_Broker_Reputations.l

---

If I disable Tiptac, my reputations display normally on the dropdown when i mouseover them on my bar.

Hmm....I did some digging and found if i turned off the 'show gradient tooltips' under backdrop options, Arabroker Rep works.

So im guessing this is an error/conflict with that addon and not TIptac really then?

**Comment by frozn** [comment]
Yes, it's a problem within addon Ara_Broker_Reputations. The texture function SetGradientAlpha() has been removed in df. TipTac uses a gradient for it's tooltips, too. To fix this for df I replaced calling the function SetGradientAlpha() with a gradient texture, see here:

https://github.com/frozn/TipTac/blob/266401b676d4b1d9ea1a4292b75e2f0c221dcd18/TipTac/ttCore.lua#L634-L640

This modification will be included in the next release of TipTac. The authors from Ara_Broker_Reputations have to do the same.

**Comment by bubfeeld** [comment]
yah sadly i dont think anyone is still working on Ara Broker Reputations anymore, but who knows ,lol!! thanks for your work!!

**Comment by frozn** [comment]
Ara_Broker_Reputations ist currently under development. The latest version is from Oct 28 this year, and on github @Ookami313 created a bug already: https://github.com/AraBroker/Ara_Broker_Reputations/issues/1

**Comment by bubfeeld** [comment]
interesting, with your guidance i did some tinkering and seem to have to solved it though. you are awesome sir!

**Comment by frozn** [comment]
Seems good to me. Later only the texture (Interface\AddOns\TipTac\media\gradient.tga) has to be included into Ara_Broker_Reputations and the path has to be changed accordingly.

**Comment by bubfeeld** [comment]
yah my expertise is VERY limited, i can copy paste fixes and figure out very simple things, but definitely not long term stuff. 
Luckily in this case, someone is still actually working on that mod, so im sure they will come up with something more elegant,
thanks again!

**Comment by mightykong** [comment]
> Seems good to me. Later only the texture (Interface\AddOns\TipTac\media\gradient.tga) has to be included into Ara_Broker_Reputations and the path has to be changed accordingly. 🙂

I'm the maintainer of Ara, I actually don't really use TipTac, so I never caught this error.  That code has been there since I took over.  From what I see, I need to call this now:  Interface\AddOns\TipTac\media\gradient, but you're saying I need to change this later to Interface\AddOns\TipTac\media\gradient.tga.

Is that after a TipTac update?

**Comment by frozn** [comment]
I have taken a look into your commit. Because of reading TipTac's config to set the backdrop/gradient it would be ok to use texture `[[Interface\AddOns\TipTac\media\gradient]]` from TipTa too. But the fix including the gradient texture is currently only available in the main branch and will be included soon in the next release.

But taken over the gradient texture to your addon is fine, too.
