### ISSUE TITLE
[Feature Request] Add more combat/static unitframe toggles

### ISSUE THREAD

**Issue by Toasticon** [frozn/TipTac#122]
Having switched over to ElvUI I realized one important feature its builtin tooltip lacks and that is having the option to disable tooltips on all unitframes but things like hovering over NPCs/Players, doodads and so forth AT ALL TIMES.

For example: 
- You do Open World PVP or BGs and want to hover over somebody else for checking mana or idk.
- Or in Raids or M+ you want to hover over something like a caster because nameplates become a limiting factor at a certain point.

This was possible with TipTac in combination with Shadow Unit Frames for example where I could just disable tooltip from working on Player/Target, Party, and Raid frames and voila, all the above worked as intended. Sadly there is no option atm but to ditch ElvUI for SUF which seems like a mess right now during DF pre-patch. 

So what I'm simply asking is if it were possible to add more combat/static toggles for those unitframes? Just a toggle for all but NPCs/Players (not the actual frame) would be enough.

**Comment by frozn** [comment]
Did you try "Combat->Hide Unit Tips for Unit Frames in Combat"? Seems to me, that this is what you are looking for.

**Comment by Toasticon** [comment]
Yeah it's a decent feature but sometimes for some odd reason the tooltip slips through when in combat and as a healer that's a big no-no. When I have time I'll look into it in order to make a permanent toggle like I mentioned above.

**Comment by frozn** [comment]
I added the option to hide frame and/or world unit tips or all tips in or out of combat. Included in release [v22.11.18](https://github.com/frozn/TipTac/releases/tag/v22.11.18-release). 👍

**Comment by Toasticon** [comment]
You deserve at least 4, no 5! internet awards. Too bad github doesn't have a tip-jar.
