### ISSUE TITLE
Move Anchor not working on Beta

### ISSUE THREAD

**Issue by jjholleman** [frozn/TipTac#125]
Moving the Anchor is not working correctly on the Beta. (It does work on Retail)
The tooltip is stuck in the BOTTOMRIGHT corner of the screen. 
There are no Lua errors in Bugsack.
All other addons are disabled.

I'm using the latest v22.11.04 [DF].

**Comment by frozn** [comment]
Yes, related to #116.

**Comment by frozn** [comment]
Fixed with release [v22.11.14](https://github.com/frozn/TipTac/releases/tag/v22.11.14-release).
