### ISSUE TITLE
Item compare from bags lua error

### ISSUE THREAD

**Issue by timetofall** [frozn/TipTac#127]
Getting the below LUA error when comparing an item in my bag to an item i have equipped by hovering over the item in bag and holding down left shift.

Sorry forgot to add:
1) I am on the Retail Beta
2) I am on the latest version of TipTac Reborn

> 
> 12x Interface/AddOns/TipTacItemRef/ttItemRef.lua:1009: attempt to call method 'GetItem' (a nil value)
> [string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1009: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1007>
> [string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1571: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1569>
> [string "=(tail call)"]: ?
> [string "=[C]"]: in function `securecallfunction'
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
> [string "=[C]"]: in function `SetAttribute'
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
> [string "=[C]"]: in function `securecallfunction'
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function `ProcessInfo'
> ...
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:49: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:44>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:71: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:67>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:135: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
> [string "=[C]"]: in function `securecallfunction'
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
> [string "=(tail call)"]: ?
> [string "@Interface/FrameXML/ContainerFrame.lua"]:1503: in function `UpdateTooltip'
> [string "@Interface/FrameXML/GameTooltip.lua"]:498: in function <Interface/FrameXML/GameTooltip.lua:491>
> [string "=[C]"]: ?
> 
> Locals:
> self = ShoppingTooltip1 {
>  0 = <userdata>
>  SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
>  SetHyperlink = <function> defined =[C]:-1
>  SetAzeriteEssence = <function> defined =[C]:-1
>  SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
>  SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  ttGradient = Texture {
>  }
>  SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetRecipeReagentItem = <function> defined =[C]:-1
>  SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  BottomOverlay = Texture {
>  }
>  SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
>  NineSlice = Frame {
>  }
>  SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  TopEdge = Texture {
>  }
>  SetUnitDebuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetBagItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetBackdropColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1679
>  LeftEdge = Texture {
>  }
>  SetCurrencyByID = <function> defined =[C]:-1
>  SetSpellBookItem = <function> defined =[C]:-1
>  textLeft1Font = "GameFontNormalSmall"
>  SetShapeshift = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  hasMoney = 1
>  SetArtifactPowerByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  textRight2Font = "GameFontHighlightSmall"
>  TopOverlay = Texture {
>  }
>  SetSocketedItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetUnitDebuff = <function> defined =[C]:-1
>  SetMountBySpellID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
>  SetToyByItemID = <function> defined =[C]:-1
>  TextLeft1 = ShoppingTooltip1TextLeft1 {
>  }
>  GetTooltipData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:344
>  SetLFGDungeonShortageReward = <function> defined =[C]:-1
>  OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
>  SetArtifactItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetPossession = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetAzeriteEssenceSlot = <function> defined =[C]:-1
>  SetUnitBuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetConduit = <function> defined =[C]:-1
>  SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
>  SetMinimapMouseover = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetQuestLogCurrency = <function> defined =[C]:-1
>  SetRecipeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetQuestPartyProgress = <function> defined =[C]:-1
>  ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
>  OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
>  SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetUnit = <function> defined =[C]:-1
>  SetTotem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
>  ttSetBackdrop

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Fixed with release [v22.11.15](https://github.com/frozn/TipTac/releases/tag/v22.11.15-release).

**Comment by timetofall** [comment]
> Thanks for reporting this! 👍
> 
> Fixed with release [v22.11.15](https://github.com/frozn/TipTac/releases/tag/v22.11.15-release).

Just tested, looks good, no more Lua error when comparing items from bags! thank you 👍
