### ISSUE TITLE
GetMiniAchievements error - WotLK

### ISSUE THREAD

**Issue by Zautix** [frozn/TipTac#128]
Version: v22.11.14

TipTacItemRef\ttItemRef.lua:1712: hooksecurefunc(): GetMiniAchievement is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@TipTacItemRef\ttItemRef.lua"]:1712: in function `ADDON_LOADED'
[string "@TipTacItemRef\ttItemRef.lua"]:303: in function `?'
[string "@TipTacItemRef\ttItemRef.lua"]:221: in function <TipTacItemRef\ttItemRef.lua:221>

Appears immediately on entering world

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Fixed with release [v22.11.15](https://github.com/frozn/TipTac/releases/tag/v22.11.15-release).
