### ISSUE TITLE
[Feature request] PetBattleAbilityTooltip Anchoring function

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#13]
Now tooltips of pet abilities in pet battle encounter anchored to UI parent i think. 
https://imgur.com/a/FeLDlP3

But hope it will follow Frame Tip Type like other buttons in pet battle. For consistency

**Comment by frozn** [comment]
Implementing the pet battle UI is on my todo-list. 👍

**Comment by frozn** [comment]
With release [v23.08.23](https://github.com/frozn/TipTac/releases/tag/v23.08.23-release) I added the styling of tooltips during pet battle and improved pet ability buttons in bottom frame, so that they are anchored the same way like "switch pet" or "give up" button.
