### ISSUE TITLE
need show talent and equip level

### ISSUE THREAD

**Issue by hyxboy** [frozn/TipTac#131]
I really want these options

**Comment by frozn** [comment]
Related to #88.

**Comment by frozn** [comment]
Reopened it regarding talent level.

**Comment by frozn** [comment]
Added displaying of average item level in release [v22.11.25](https://github.com/frozn/TipTac/releases/tag/v22.11.25-release).

Implementing talent points distribution in df is still pending.

**Comment by frozn** [comment]
Added showing of talent points spent in df with release [v22.12.03](https://github.com/frozn/TipTac/releases/tag/v22.12.03-release).
