### ISSUE TITLE
Hide Unit Frame Tooltips no longer seems to work

### ISSUE THREAD

**Issue by WanderingFox** [frozn/TipTac#134]
**Describe the bug**
Selecting "Hide Unit Frame Tooltips" in the combat section does not seem to work. Hiding all tooltips works fine. I presume this has to do with the changes made to tooltip generation.

**To Reproduce**
1. Select "Hide Unit Frame Tooltips in Combat"
2. Hover over a unit frame while in combat and note that the tooltip is still there

**Expected behavior**
The tooltip to be hidden (or the option to be removed)

**WoW (please complete the following information):**
 - Flavor: retail
 - Version: 10.0.2

**Additional context**
It was handy, but not a huge deal for me if it can't be reimplemented. Hiding all tooltips is just as good :)

Thank you again for maintaining this awesome addon!

**Comment by frozn** [comment]
With release [v22.11.18](https://github.com/frozn/TipTac/releases/tag/v22.11.18-release) I implemented some changes regarding hiding tooltips in or out of combat. Please check the settings under "Combat". Two of the checkboxes have been replaced by dropdown menus.

Which version of TipTac do you use? I can't reproduce this currently.

**Comment by WanderingFox** [comment]
v22.11.18

It's possible that it's because my main unit frames are grid2 frames (same happens with pitbull4 frames).

Out of combat:
![image](https://user-images.githubusercontent.com/2967926/202862084-24c5a303-9faf-4f12-97fc-1db15cf424db.png)


In combat but with "frame units" selected as hide in combat:
![image](https://user-images.githubusercontent.com/2967926/202862107-61e03639-aa73-4206-804d-a51588fb1df5.png)
![image](https://user-images.githubusercontent.com/2967926/202862121-80221093-e6b5-4952-a918-75185082dcaf.png)

It works fine with "all tips" though:
![image](https://user-images.githubusercontent.com/2967926/202862140-b0e8e894-a40d-4e55-8b04-7a019affc7c1.png)
![image](https://user-images.githubusercontent.com/2967926/202862160-e36c2375-9afc-47c7-b396-e2597ff6b347.png)

**Comment by WanderingFox** [comment]
Looking at my own screenshots I found the culprit. My MRP profile got reset and it was taking over the tooltip and showing it despite tiptac's settings.

Apologies!

**Comment by frozn** [comment]
Glad that you could solve your issue! 👍
