### ISSUE TITLE
Move Stack Size info from icon texture to normal tooltip frame

### ISSUE THREAD

**Issue by tflo** [frozn/TipTac#135]
I would love to see the Stack Size info as simple line inside the normal tooltip, instead of inside the icon texture.

Why?

As it is now, I have to decide between…

- Activating "Smart Icon Appearance" and using an additional addon just for the stack size, as TipTac's stack info is hidden for bag item tooltips. Or…
- Deactivating "Smart Icon Appearance"; then I do not need an additional addon, but have to live with a redundant icon.

Displaying the stack info as normal line inside the normal tooltip would solve this dilemma 100% :)

Here an example, how this could look like (from my patched version of the old MaxStackSize addon):

<img width="557" alt="WoWScrnShot_111822_191355 copy" src="https://user-images.githubusercontent.com/1410282/202775506-131b08ca-edfa-4b49-966d-c2cdc137591f.png">

Thanks for considering,

– Tom

**Comment by frozn** [comment]
Added with release [v22.11.20](https://github.com/frozn/TipTac/releases/tag/v22.11.20-release). 👍

**Comment by tflo** [comment]
Perfect! Thank you :)
