### ISSUE TITLE
TipTacItemRef interfering with Altoholic

### ISSUE THREAD

**Issue by zaphon** [frozn/TipTac#136]
**Describe the bug**
I re-installed Altoholic this morning as it had broken with the phase 2 pre-patch released last week. Prior to the pre-patch it had been working fine along with TipTac, but after this morning, for whatever reason, if I have TipTac loaded (specifically TipTacItemRef enabled) it doesn't add anything to the tooltips. I've debugged through Altoholic and it's hook is being called and I dumped the tooltip before it returns from it's function (it looks proper when it returns, something is wiping it after this). This function is hooked via TooltipDataProcessor.AddTooltipPostCall.

**To Reproduce**
1. Install TipTac
2. Install Altoholic
3. Configure Altoholic's tooltips to show information (like item counts on alts)
4. Mouse over an item, you won't see any counts. However if you go into TipTac's options and disable ItemRefTooltip Modifications it starts working.

**Expected behavior**
It will be obvious from screenshots

**Screenshots**
https://imgur.com/a/zA1eFVa - There are 3 screenshots showing the behavior with ItemRefTooltip Modifications disabled, the options screen, and with it enabled.

**TipTac Reborn (please complete the following information):**
 - Version 22.11.18

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.2.46702

**Comment by tflo** [comment]
I had the same issue.

I could fix it by using `PLAYER_ENTERING_WORLD` instead of `VARIABLES_LOADED` in TipTacItemRef/ttItemRef.lua, lines 254 and 316.

It seems the VARIABLES_LOADED event is too early.

Here the diff:

```diff
254c254
< ttif:RegisterEvent("VARIABLES_LOADED");
---
> ttif:RegisterEvent("PLAYER_ENTERING_WORLD");
316c316,317
< function ttif:VARIABLES_LOADED(event)
---
> function ttif:PLAYER_ENTERING_WORLD(event, isLogin, isReload)
> 	if not isLogin and not isReload then return end
```

– Tom

**Comment by zaphon** [comment]
Can confirm this works.

**Comment by frozn** [comment]
Thanks for digging into this! 👍 

But the real issue with this has been, that the hidden scanning tooltip in `TipTacItemRef\libs\LibItemString.lua` accidentally clears the tooltip lines. I replaced this with new C_TooltipInfo function for df, and now everything seems good to me. 🙂
