### ISSUE TITLE
Keybinds being blocked after using a portal

### ISSUE THREAD

**Issue by Zasz333** [frozn/TipTac#137]
**Describe the bug**
Interface cant be used when the error occurs. Seems to happen after entering a portal to another continent and then only realizing the error when using a keybind to use an ability.

**To Reproduce**
1. Use a portal
2. Use keybind for any ability
3. "Tiptac has been blocked" error pops up.
4. See error text below.

**Expected behavior**
The interface should not prevent keybind usage.

**TipTac Reborn (please complete the following information):**
 - Version 22.11.18

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.2.46702

Error text:

[ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@FrameXML/UIParent.lua"]:3095: in function `UIParentManageFramePositions'
[string "@FrameXML/UIParent.lua"]:2570: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3113: in function `UIParent_ManageFramePositions'
[string "@FrameXML/EditModeManager.lua"]:640: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@FrameXML/PetActionBar.lua"]:84: in function <FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

**Comment by frozn** [comment]
I changed the anchoring of the GameTooltip to TipTac's anchor to prevent errors regarding SetPoint() with release [v22.11.25](https://github.com/frozn/TipTac/releases/tag/v22.11.25-release).

Since I didn't get this error, does the fix work for you?

**Comment by CelestianGC** [comment]
I've been getting this error (after update) still. It's not 100% but it happens randomly when zoning into a dungeon or from Org to Oribos.

**Comment by Zasz333** [comment]
I havent had the error today. Just downloaded the newest version. Will report if I encounter it again.

**Comment by CelestianGC** [comment]
Loaded up TipTac today and happed immediately when I took a alt to DF. Had to disable it again.

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
