### ISSUE TITLE
Immersion addon quest choice currency tooltip border is not colored now

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#14]
Quest reward(currency) preview without addon immersion seems to work fine now.

But when with Immersion, if there is currency at quest reward, it's border and icon function seems to be not working now.

https://imgur.com/a/XeaA4or

Can be fixed by adding 

hooksecurefunc(tip,"SetQuestCurrency",SetQuestCurrency_Hook);

-- HOOK: SetQuestCurrency_Hook
local function   ##SetQuestCurrency_Hook(self,type,id)
	if (cfg.if_enable) and (not tipDataAdded[self]) then
		local currencyId = GetQuestCurrencyID(type, id);
	
		if (currencyId) then
			tipDataAdded[self] = "currency";
			LinkTypeFuncs.currency(self,nil,"currency",currencyId);
		end
	 end
 end

**Comment by frozn** [comment]
I have noticed, that some currency rewards of my own quests in quest log had a wrong border color. I added a fix to the function "ttItemRef.lua"->LinkTypeFuncs:currency(), so that currency containers are considered for border colors. So Renown does not need to be adjusted manually. Looks fine now. :slightly_smiling_face:

I committed my changes to main-branch. Can you test with this version, if your issue is resolved already with this modification?

**Comment by hobulian** [comment]
> I have noticed, that some currency rewards of my own quests in quest log had a wrong border color. I added a fix to the function "ttItemRef.lua"->LinkTypeFuncs:currency(), so that currency containers are considered for border colors. So Renown does not need to be adjusted manually. Looks fine now. 🙂
> 
> I committed my changes to main-branch. Can you test with this version, if your issue is resolved already with this modification?

It's fine with other stuffs but immersion rewards seems still not working ..
I think "SetQuestCurrency" related stuff have to be added also.

**Comment by frozn** [comment]
I changed the hooking of quest(log) items and currencies to add compatibility to other addons (e.g. Immersion). I added the following hooks:

- GameTooltip:SetQuestItem()
- GameTooltip:SetQuestCurrency()
- GameTooltip:SetQuestLogItem()
- GameTooltip:SetQuestLogCurrency()

I temporarily installed addon Immersion and it looks fine now. I committed my changes to main-branch.

**Comment by hobulian** [comment]
> I changed the hooking of quest(log) items and currencies to add compatibility to other addons (e.g. Immersion). I added the following hooks:
> 
> * GameTooltip:SetQuestItem()
> * GameTooltip:SetQuestCurrency()
> * GameTooltip:SetQuestLogItem()
> * GameTooltip:SetQuestLogCurrency()
> 
> I temporarily installed addon Immersion and it looks fine now. I committed my changes to main-branch.

Thanks for your hardworking. I know it's not easy to download and check addons that you are not using. I've checked your fix and it works fine now.

**Comment by frozn** [comment]
I noticed some spots, where currency border and infos are missing, too (e.g. top of torghast box). So I also added hooks for GameTooltip:SetCurrencyByID() and GameTooltip:SetCurrencyTokenByID() for currencies.

I think that this issue is finally closed then.
