### ISSUE TITLE
Setpoint error

### ISSUE THREAD

**Issue by koolman007** [frozn/TipTac#142]
272x FrameXML/GameTooltip.lua:190: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML/GameTooltip.lua"]:190: in function <FrameXML/GameTooltip.lua:172>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "*GameTooltip.xml:25_OnTooltipSetDefaultAnchor"]:1: in function <[string "*GameTooltip.xml:25_OnTooltipSetDefaultAnch..."]:1>

happens everytime i try to set anchor point for tooltip. Also happens when ever i login into any character.

**Comment by frozn** [comment]
Please delete the following file: `World of Warcraft\__<Edition>__\WTF\<Account>\<Server>\<Character>\layout-local.txt`

Did this fix your error?

**Comment by koolman007** [comment]
> Please delete the following file: `World of Warcraft\__<Edition>__\WTF\<Account>\<Server>\<Character>\layout-local.txt`
> 
> Did this fix your error?

Thanks. Its still happening when I try to move the anchor around. But i am not getting it everytime i log into a character.

**Comment by vojtasrb** [comment]
Same problem here. It's happening to me even without setting new anchor point.

**Comment by frozn** [comment]
I changed the anchoring of the GameTooltip to TipTac's anchor to prevent errors regarding SetPoint() with release [v22.11.25](https://github.com/frozn/TipTac/releases/tag/v22.11.25-release).

Since I didn't get this error, does the fix work for you?

**Comment by koolman007** [comment]
> I changed the anchoring of the GameTooltip to TipTac's anchor to prevent errors regarding SetPoint() with release [v22.11.25](https://github.com/frozn/TipTac/releases/tag/v22.11.25-release).
> 
> Since I didn't get this error, does the fix work for you?

Hi, sorry for getting back late to you. This certainly has fixed the error for me! thanks very much for your hard work.

**Comment by frozn** [comment]
Glad to hear this! 🥳
