### ISSUE TITLE
ADDON_ACTION_FORBIDDEN [UNKNOWN]

### ISSUE THREAD

**Issue by yourapple** [frozn/TipTac#143]
1x [ADDON_ACTION_FORBIDDEN] 插件 'TipTacTalents' 尝试调用保护功能 'UNKNOWN()'。
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

**Comment by Zasz333** [comment]
Got the same error when using right click on jewelhammer's focus from bfa juwelcrafting. It blocked all key binds from that point until /reload or relogging.

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
