### ISSUE TITLE
SetPoint error when visiting bank with Bagnon

### ISSUE THREAD

**Issue by helicdark** [frozn/TipTac#144]
Message: Interface\FrameXML\ContainerFrame_Shared.lua:1296: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
Time: Tue Nov 22 22:31:17 2022
Count: 129
Stack: Interface\FrameXML\ContainerFrame_Shared.lua:1296: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.

Locals: 

happens everytime i visit my bank with bagnon loaded.
firstly the tooltip will be shown like [https://imgur.com/a/GOsADGV](https://imgur.com/a/GOsADGV) while i didn't set it to transparent background at all; then after i drag the bag window and point at anything in bank again, this lua error pops up.

**Comment by frozn** [comment]
Please delete the following file: World of Warcraft\__<Edition>__\WTF\<Account>\<Server>\<Character>\layout-local.txt

Did this fix your error?

**Comment by helicdark** [comment]
> Please delete the following file: World of Warcraft____\WTF<Account><Server><Character>\layout-local.txt
> 
> Did this fix your error?

Thanks, but i'm afraid not. It's still happening when the bank window pops up( btw a same error happens on the original tiptac when opening my bag instead of bank).

Plus, no more error occurs if I disable Bagnon. I suppose there are conflicts between them?

**Comment by frozn** [comment]
I changed the anchoring of the GameTooltip to TipTac's anchor to prevent errors regarding SetPoint() with release [v22.11.25](https://github.com/frozn/TipTac/releases/tag/v22.11.25-release).

Since I didn't get this error, does the fix work for you?

**Comment by helicdark** [comment]
> I changed the anchoring of the GameTooltip to TipTac's anchor to prevent errors regarding SetPoint() with release [v22.11.25](https://github.com/frozn/TipTac/releases/tag/v22.11.25-release).
> 
> Since I didn't get this error, does the fix work for you?

Well, not really, the error still pops up. But thanks for updating.
I guess this is not TipTac's fault and have disabled Bagnon, then everything goes well.

**Comment by helicdark** [comment]
Bagnon updated and the error no longer appears.

**Comment by frozn** [comment]
Glad that this issue is solved for you! 🥳
