### ISSUE TITLE
[ADDON_ACTION_FORBIDDEN] AddOn 'TipTac' tried to call the protected function 'CopyToClipboard()'

### ISSUE THREAD

**Issue by cosmo-somebody** [frozn/TipTac#145]
**Describe the bug**
Unable to Share specialization after talent change without error

**To Reproduce**
1. Right click an existing talent and left click another talent
2. Apply Changes
3. Use dropdown to Share

**Expected behavior**
Expected to be able to Share (copy to clipboard) without error or having to disable TipTac to do so.

**Screenshots**
Will do so if Error and Description are not satisfactory.

**TipTac Reborn (please complete the following information):**
 - Version 22.11.20

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.2 Build 46702

**Additional context**
I can fully reproduce the error on another character.

**LUA Error**:
``1x [ADDON_ACTION_FORBIDDEN] AddOn 'TipTac' tried to call the protected function 'CopyToClipboard()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CopyToClipboard'
[string "@Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua"]:454: in function `callback'
[string "@SharedXML/LoadSystem/LoadSystemTemplates.lua"]:26: in function <.SharedXML/LoadSystem/LoadSystemTemplates.lua:17>
[string "=(tail call)"]: ?
[string "@SharedXML/SharedUIPanelTemplates.lua"]:2457: in function `SetSelectedValue'
[string "@SharedXML/SharedUIPanelTemplates.lua"]:2409: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>``

**taint.log**
`11/23 11:03:01.987  Hide()
11/23 11:03:01.987  An action was blocked because of taint from TipTac - CopyToClipboard()
11/23 11:03:01.987      Interface/AddOns/Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua:454 callback()
11/23 11:03:01.987      Interface/SharedXML/LoadSystem/LoadSystemTemplates.lua:26
11/23 11:03:01.987      Interface/SharedXML/SharedUIPanelTemplates.lua:2457 Frame:SetSelectedValue()
11/23 11:03:01.987      Interface/SharedXML/SharedUIPanelTemplates.lua:2409 func()
11/23 11:03:01.987      Interface/SharedXML/UIDropDownMenu.lua:1007 UIDropDownMenuButton_OnClick()
11/23 11:03:01.987      DropDownList1Button4:IDropDownMenuTemplates.xml:136_OnClick()`

**Comment by frozn** [comment]
Glad to here that this issue is solved for you. Thanks for reporting! 👍
