### ISSUE TITLE
Tooltip appearance LUA error

### ISSUE THREAD

**Issue by Invitv** [frozn/TipTac#146]
440x FontString:SetFormattedText(): Font not set
[string "=[C]"]: in function `SetFormattedText'
[string "@TipTac/ttBars.lua"]:151: in function `SetFormattedBarValues'
[string "@TipTac/ttBars.lua"]:256: in function `?'
[string "@TipTac/ttCore.lua"]:397: in function `SendElementEvent'
[string "@TipTac/ttCore.lua"]:1247: in function `ApplyUnitAppearance'
[string "@TipTac/ttCore.lua"]:1469: in function <TipTac/ttCore.lua:1430>
[string "=[C]"]: ?

Locals:
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "%s / %s"
(*temporary) = "81.0k"
(*temporary) = "81.0k"

**Comment by frozn** [comment]
Are both "Font->Font Face" and "Bars->Font Face" properly set to a valid font?

**Comment by Invitv** [comment]
They were earlier... apparently not so now... thanks! fixed :)

**Comment by frozn** [comment]
Great! 👍
