### ISSUE TITLE
Tiptac and  outfitter interaction

### ISSUE THREAD

**Issue by Addonman** [frozn/TipTac#147]
When i resize size of tooltip in tiptac it also effects other addons  or should i say Outfitter. Outfitter has like 2 or 3 cascadeing options windows and they get smaller and smaller. Barely readable.

https://github.com/MrMime71/Outfitter/issues/14

**Comment by frozn** [comment]
This is a bug in library "LibDropDownMC-1.0" which is used by Outfitter. To prevent cascading scales you can temprarily comment out the following line in "\Outfitter\Libraries\LibDropdown-1.0.lua":

```
-- Make the frame match the tooltip
local function InitializeFrame(frame)
	if TooltipBackdropTemplateMixin then
		frame.layoutType = GameTooltip.layoutType
		if GameTooltip.layoutType then
			frame.NineSlice:SetCenterColor(GameTooltip.NineSlice:GetCenterColor())
			frame.NineSlice:SetBorderColor(GameTooltip.NineSlice:GetBorderColor())
		end
	else
		local backdrop = GameTooltip:GetBackdrop()

		frame:SetBackdrop(backdrop)

		if backdrop then
			frame:SetBackdropColor(GameTooltip:GetBackdropColor())
			frame:SetBackdropBorderColor(GameTooltip:GetBackdropBorderColor())
		end
	end
	-- frame:SetScale(GameTooltip:GetScale()) <--------------------------------------
end
```

**Comment by frozn** [comment]
Additionally I created an enhancement issue to add styling of LibDropdown-1.0 because I think it's nice to have.

**Comment by Addonman** [comment]
Thank you for information. Its used by bunch of addons i use so i might not want to mess with that .

**Comment by frozn** [comment]
I added TipTac's styling of the dropdown menu from LibDropdownMC-1.0. Scaling is also considered. Works fine now in the dev version. If you want to try it for yourself, here it is:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/10503732/TipTac-dev.zip)

This will be included in the upcoming release.
