### ISSUE TITLE
Quality border for WorldQuest

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#15]
Some world quest seems to have it's own quality(example of worldbosses[heroic] or some quests at maw[unique]). But it's bordering color function is now absent. I think It's good to be added.

**Comment by hobulian** [comment]
hooksecurefunc("GameTooltip_AddQuestTimeToTooltip", GTT_AddQuestTimeToTooltip);	

-- AddC Quality Border for WorldQuests
local function GTT_AddQuestTimeToTooltip(self,id)
	if (cfg.if_enable) and (not tipDataAdded[self]) then
		local tagInfo = C_QuestLog.GetQuestTagInfo(id);
		-- Quality Border
		if (cfg.if_itemQualityBorder) and (tagInfo and tagInfo.quality) then
			local difficultyColorMixin = CreateColor(GetItemQualityColor((tagInfo.quality == 1 and 3) or (tagInfo.quality == 2 and 4) or 1));
			ttif:SetBackdropBorderColor(self, difficultyColorMixin:GetRGBA());
			tipDataAdded[self] = "quest";
		end
	end
end

I manually added those stuff. And seems it's working. hope this will be helpful.

**Comment by hobulian** [comment]
Quality border for DressUpFrame seems to be needed.

https://imgur.com/a/UZjXhEB

**Comment by frozn** [comment]
I added a hook to VignettePinMixin:OnMouseEnter() for special events in maw (which I saw some day) and committed it to main-branch. Does this solve the problem either completely or partially?

**Comment by hobulian** [comment]
> I added a hook to VignettePinMixin:OnMouseEnter() for special events in maw (which I saw some day) and committed it to main-branch. Does this solve the problem either completely or partially?

It didn't changed Worldquest's qualityborder and #7 
https://imgur.com/a/7H9uKo5

Hmm. I didn't get what special events in maw meant So couldn't checked it out. 

What i meant 
"worldbosses[heroic] " was like worldquest
https://ko.wowhead.com/quest=64531/%EB%AA%A8%EB%A5%B4%EC%A0%9C%EC%8A%A4
which has quest quality of heroic(purple).

"some quests at maw[unique]" was like worldquest
https://ko.wowhead.com/quest=64273/%EC%A0%80%EC%8A%B9%EC%82%B4%EC%9D%B4-%ED%87%B4%EC%B9%98-%EC%9E%91%EC%97%85
which has quest quality of rare(blue).

**Comment by frozn** [comment]
I committed changes to main-branch to consider world quests for difficulty border.

**Comment by hobulian** [comment]
It's working now :) What a great work.

**Comment by frozn** [comment]
Thank you for looking over and verifying! :smile::thumbsup:

**Comment by frozn** [comment]
I subsequently added border color and infos for tracker of addon WorldQuestTracker, too.

**Comment by hobulian** [comment]
> I subsequently added border color and infos for tracker of addon WorldQuestTracker, too.

Wow I didn't expected that such is possible. I screamed with joy when i checked out that feature in game!
