### ISSUE TITLE
Get SpellFlyout Direction Nil Value when using Dominos

### ISSUE THREAD

**Issue by craglin** [frozn/TipTac#151]
**Describe the bug**
Bug only occurs in conjunction with Dominos action bar manager. On a rogue, attempting to access poisons listing flyout on an action bar.. 

**To Reproduce**
1. Drag "Poisons" to any action bar.
2. Click "Poisons" button.

**Expected behavior**
Spell flyout of available poisons.

**Screenshots**
Screenshot not applicable.

**TipTac Reborn (please complete the following information):**
 - Version 22.12.03

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version: 10.0.2

**Additional context**
BugSack Debug info below:
1x FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@FrameXML/SpellFlyout.lua"]:240: in function `Toggle'
[string "@FrameXML/SecureTemplates.lua"]:361: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:1175: in function <FrameXML/ActionButton.lua:1145>
[string "=[C]"]: ?

Locals:
self = SpellFlyout {
 0 = <userdata>
 isActionBar = true
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:90
 eventsRegistered = false
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:105
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:114
 Toggle = <function> defined @FrameXML/SpellFlyout.lua:206
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:64
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:84
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:76
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:110
 SetBorderSize = <function> defined @FrameXML/SpellFlyout.lua:442
 Layout = <function> defined @SharedXML/LayoutFrame.lua:333
 SetBorderColor = <function> defined @FrameXML/SpellFlyout.lua:435
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 Background = Frame {
 }
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:48
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:329
}
flyoutID = 66
parent = DominosActionButton49 {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML/ActionButton.lua:1200
 FlyoutArrowContainer = Frame {
 }
 NewActionTexture = Texture {
 }
 RightDivider = Frame {
 }
 DoModeChange = <function> defined @FrameXML/QuickKeybind.lua:95
 __MSQ_bType = "Action"
 __MSQ_NewNormal = Texture {
 }
 UpdateButtonArt = <function> defined =[C]:-1
 QuickKeybindButtonOnLeave = <function> defined @FrameXML/QuickKeybind.lua:33
 UpdateAction = <function> defined @FrameXML/ActionButton.lua:357
 OnReceiveDrag = <function> defined @FrameXML/ActionButton.lua:1194
 icon = DominosActionButton49Icon {
 }
 SlotArt = Texture {
 }
 AutoCastable = Texture {
 }
 UpdateTooltip = <function> defined @FrameXML/ActionButton.lua:914
 UpdateState = <function> defined @FrameXML/ActionButton.lua:494
 SetShowCooldowns = <function> defined @Dominos/bars/actionBar/button.lua:82
 __MSQ_ChargeSkin = <table> {
 }
 OnDragStart = <function> defined @FrameXML/ActionButton.lua:1182
 UpdatePressAndHoldAction = <function> defined @FrameXML/ActionButton.lua:340
 __MSQ_UpdateButtonArt = true
 __MSQ_NormalSkin = <table> {
 }
 HotKey = DominosActionButton49HotKey {
 }
 HighlightTexture = Texture {
 }
 UpdateOverlayGlow = <function> defined @FrameXML/ActionButton.lua:707
 GetPagedID = <function> defined @FrameXML/ActionButton.lua:1005
 Update = <function> defined @FrameXML/ActionButton.lua:373
 ClearProfessionQuality = <function> defined @FrameXML/ActionButton.lua:540
 UpdateShownInsecure = <function> defined @Dominos/bars/actionBar/button.lua:35
 QuickKeybindButtonOnEnter = <function> defined @FrameXML/QuickKeybind.lua:22
 IconMask = MaskTexture {
 }
 __MSQ_NormalHook = true
 __Regions = <table> {
 }
 __MSQ_Scale = 1
 SetNormalAtlas = <function> defined =[C]:-1
 __MSQ_Normal = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 CheckedTexture = Texture {
 }
 OnLoad = <function> defined @FrameXML/ActionButton.lua:279
 __MSQ_EmptyType = true
 PushedTexture = Texture {
 }
 SetButtonState = <function> defined @FrameXML/ActionButton.lua:1140
 __MSQ_Mask = MaskTexture {
 }
 SetTooltip = <function> defined @FrameXML/ActionButton.lua:914
 Count = DominosActionButton49Count {
 }
 __MSQ_IsAction = true
 UpdateUsable = <function> defined @FrameXML/ActionButton.lua:500
 __MSQ_Icon = DominosActionButton49Icon {
 }
 SetNormalTexture = <function> defined =[C]:-1
 FlyoutBorderShadow = DominosActionButton49FlyoutBorderShadow {
 }
 GetShowGrid = <function> defined @FrameXML/ActionButton.lua:1227
 SetButtonStateBase = <function> defined =[C]:-1
 UpdateHotkeys = <function> defined =[C]:-1
 __MSQ_Enabled = true
 Q

**Comment by Toasticon** [comment]
Dominos is the issue because it's not updated. Blizzard code is the issue because the devs are lazy and no addon dev has found a REAL solution. Dominos has since been abandoned unless you yourself can find a proper solution.
https://github.com/tukui-org/ElvUI/issues/571
https://github.com/tullamods/Dominos/issues/641
https://github.com/Nevcairiel/Bartender4/issues/92
https://github.com/Stanzilla/WoWUIBugs/issues/302

**Comment by lowpita** [comment]
Hey. There was actually a work around for this from nevcairiel, bartender's author. Check changelog: https://www.curseforge.com/wow/addons/bartender4/files/4102728
I don't know about dominos tho. This same rework is implemented into elvui.

**Comment by Tuller** [comment]
I've implemented a workaround in 10.0.13.

**Comment by frozn** [comment]
Phew... I pushed out many fixes regarding the complete rewrite of ttCore in the last days. It's nice, that some issues solves themselves. 😉
