### ISSUE TITLE
LUA Error 

### ISSUE THREAD

**Issue by Teseus7** [frozn/TipTac#152]
4x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'ActionButton8:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

**Comment by fgmenth** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'MultiBarBottomRightButton6:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

Same thing happens to me. It happens **every time I level up and apply a talent point**, guaranteed. It's probably a taint happening somewhere but I can't seem to pinpoint exactly where.

**Comment by StormFX** [comment]
I'm having a similar issue, but it only happens on my Shaman. I've attached a taint.log.
[taint.log](https://github.com/frozn/TipTac/files/10213544/taint.log)

**Comment by fgmenth** [comment]
It's reproducible for me whenever I manually change my talents (not applying a preset). Leveling up doesn't make a difference, so disregard that part of my previous comment.

**Comment by frozn** [comment]
Do you have an addon active to customize the action bars. Dominos perhaps?

**Comment by StormFX** [comment]
Yeah, I looked through the taint log, it only mentions Dominos a time or two. Not sure what is causing it, just thought I'd let you know.

**Comment by fgmenth** [comment]
I'm playing with the default UI, not using any action bar addons. It's just weird that it's only doing it after I select a talent.

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
