### ISSUE TITLE
Class colored health bars do not work

### ISSUE THREAD

**Issue by adambowles** [frozn/TipTac#154]
**Describe the bug**
Class colored health bars do not work, showing as green

**To Reproduce**

**Expected behavior**
Health bar should be colored by class color

**Screenshots**
![image](https://user-images.githubusercontent.com/10128574/207405155-19c2b921-9391-4c07-abf0-e262a9543db1.png)

**TipTac Reborn (please complete the following information):**
 - Version 22.12.03

**WoW (please complete the following information):**
 - Flavor: WotLKC
 - Version 3.4.0

**Additional context**

**Comment by frozn** [comment]
Unfortunately I can't reproduce this issue. Class colored health bars are working fine for me in WotLKC.

For testing purpose please disable all addons except the 4 ones for TipTac. Do they still not work?

**Comment by adambowles** [comment]
Yep, 4 TipTac addons are the only addons loaded, still happens

**Comment by frozn** [comment]
Strange...

Only to be shure: Please delete the 4 addon folders for TipTac in `\World of Warcraft\_classic_\Interface\AddOns`, download the latest release again and place them again in the addons folder.

Works or unchanged?

**Comment by adambowles** [comment]
Yep, I deleted the addon and downloaded a new copy from the releases on this repo.
Still didn't show class colors

I deleted my WTF config file for TipTac and class colors are showing now, do you want a copy of my old config?

**Comment by frozn** [comment]
Yes, I would like trying to reproduce this behaviour with your settings. 👍

**Comment by adambowles** [comment]
`
TipTac_Config = {
	["showRealm"] = "none",
	["classification_elite"] = "+%s ",
	["barHeight"] = 12,
	["tipBackdropEdge"] = "Interface\\Buttons\\WHITE8X8",
	["backdropEdgeSize"] = 3,
	["powerBar"] = true,
	["anchorFrameUnitPoint"] = "BOTTOMRIGHT",
	["tipBorderColor"] = {
		0.5254901960784314, -- [1]
		0.5372549019607843, -- [2]
		0.5411764705882353, -- [3]
		1, -- [4]
	},
	["powerBarText"] = "percent",
	["healthBarClassColor"] = true,
	["classification_rare"] = "%s|r (Rare) ",
	["colorGuildByReaction"] = false,
	["barsCondenseValues"] = true,
	["left"] = 1972.563720703125,
	["classification_trivial"] = "~%s ",
	["iconSize"] = 32,
	["manaBar"] = true,
	["gradientColor"] = {
		0, -- [1]
		0, -- [2]
		0, -- [3]
		0, -- [4]
	},
	["pixelPerfectBackdrop"] = true,
	["fadeTime"] = 5,
	["targetYouText"] = "You",
	["showGuildRank"] = true,
	["gradientTip"] = false,
	["gttScale"] = 1,
	["iconFaction"] = false,
	["overrideFade"] = false,
	["hideRealmText"] = false,
	["preFadeTime"] = 5,
	["hideWorldTips"] = false,
	["if_showSpellIdAndRank"] = false,
	["if_smartIcons"] = true,
	["showTTguildAfter"] = true,
	["tipColor"] = {
		0, -- [1]
		0, -- [2]
		0, -- [3]
		0.8349610418081284, -- [4]
	},
	["hideDefaultBar"] = true,
	["healthBar"] = true,
	["healthBarText"] = "full",
	["classification_normal"] = "%s ",
	["if_showIcon"] = false,
	["reactText"] = false,
	["anchorFrameTipPoint"] = "BOTTOMRIGHT",
	["showDebuffs"] = false,
	["iconCombat"] = false,
	["fontSize"] = 12,
	["anchorWorldTipType"] = "normal",
	["optionsLeft"] = 1397.162475585938,
	["fontSizeDeltaHeader"] = 3,
	["showBuffs"] = false,
	["manaBarText"] = "full",
	["fontFlags"] = "OUTLINE",
	["if_showItemId"] = false,
	["tipBackdropBG"] = "Interface\\Buttons\\WHITE8X8",
	["anchorWorldUnitPoint"] = "BOTTOMRIGHT",
	["classification_worldboss"] = "%s|r (Boss) ",
	["backdropInsets"] = 0,
	["classification_rareelite"] = "+%s|r (Rare) ",
	["showPlayerGender"] = true,
	["if_borderlessIcons"] = false,
	["anchorWorldTipPoint"] = "BOTTOMRIGHT",
	["colorNameByClass"] = true,
	["iconClass"] = false,
	["iconAnchor"] = "LEFT",
	["anchorWorldUnitType"] = "normal",
	["healthBarColor"] = {
		0.3019607843137255, -- [1]
		0.9019607843137255, -- [2]
		0.3019607843137255, -- [3]
		1, -- [4]
	},
	["top"] = 1181.538452148438,
	["if_showItemLevel"] = false,
	["classColoredBorder"] = true,
	["anchorFrameTipType"] = "mouse",
	["optionsBottom"] = 795.0685424804688,
	["fontSizeDeltaSmall"] = -1,
	["modifyFonts"] = true,
	["barTexture"] = "Interface\\AddOns\\Quartz\\textures\\Minimalist",
	["anchorFrameUnitType"] = "normal",
	["classification_minus"] = "-%s ",
}`

**Comment by adambowles** [comment]
Cool it's removed all the line breaks

**Comment by frozn** [comment]
> Cool it's removed all the line breaks
😆

I will have a look...

**Comment by frozn** [comment]
I found the problem: The selected bar texture in options under "Bars->Bar Texture" (`Interface\\AddOns\\Quartz\\textures\\Minimalist`) doesn't exist (any more). After selecting the default "Blizzard" entry the class colored health bar works fine again.
