### ISSUE TITLE
Quality border for Anima Related Tooltips

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#16]
Some anima-power(thorghast, M+, SoD 1st boss) tooltip's bordering color function is now absent. I think It's good to be added.

PlayerChoiceFrame https://imgur.com/a/LoPqliQ
ScenarioBlocksFrame.MawBuffsBlock.Container.List https://imgur.com/a/c5hpOQh
MawBuffBelowMinimapFrame and it's chat link item-ref also seems to be needed. https://imgur.com/a/QftFJQ1

**Comment by frozn** [comment]
I added the whole anima/maw power stuff and committed my changes to the main-branch. I added a special handling for this kind of unit auras to switch border color from standard spell color to the corresponding rarity color.

This was at least as nasty as the flyout stuff. :sweat_smile:

**Comment by frozn** [comment]
Thank you! :slightly_smiling_face: Although I researched pretty much I was surprised that there is no function to get the spellID based on a mawPowerID. Therefore I needed the table...

I am very curious about your feedback about SoD and M+... :coffee:

**Comment by hobulian** [comment]
Worked in M+ now. Great. Will check SoD 1st boss tomorrow.

**Comment by hobulian** [comment]
Checked SoD 1st boss and it's working. Perfect!

**Comment by frozn** [comment]
Thank you for looking over and verifying! :smile::thumbsup:
