### ISSUE TITLE
Show the true reaction string if NPC belongs to a reputation faction

### ISSUE THREAD

**Issue by tflo** [frozn/TipTac#161]
Currently TipTac is "flattening" all reactions >= 5 to 5 (Friendly). 

Non-rep-faction NPCs don't have anything higher than 5, but NPCs that belong to a rep faction can have 5 (Friendly), 6 (Honored), 7 (Revered) or 8 (Exalted) towards the player.

_Why would I want to see this information?_

**First**, it is a potentially useful bit of information, and as such it should not be hidden. Displaying the true reaction does not occupy significantly more tooltip space, and also does not waste CPU cycles.

**Second**, seeing the true reaction _at a glance_ is especially useful when I have to repair my gear: Exalted repair NPCs give significantly more discount than Friendly ones.

Sure, the faction is displayed in the tooltip, and therefore the absence of a faction in the tooltip tells me that I should not repair my gear with that guy (e.g. Scraptooth, the greedy repair Dredger in Sinfall is factionless… ;)

If the NPC belongs to a faction _and I know my standing with that faction by heart_, then no problem either. But if I don't, I first have to look up my standing with the faction, and only then I can decide if I should repair there. (For example, see all the new factions while leveling in the Dragon Isles, or factions in older zones: Do you know all the standings of your current char by heart?)

The time required for this small improvement should be small: Just the true reaction _string_ would be enough, I don't really care about the coloring of the string. That is, I do not ask you to modify the color table in the options; green for everything greater or equal 5 would be completely OK.

Thanks for considering,

– Tom

**Comment by frozn** [comment]
Sounds good to me. I try to include it into the next release. 👍

**Comment by tflo** [comment]
BTW, found a [pretty well made addon](https://www.curseforge.com/wow/addons/broker_durabilityinfo) yesterday, that addresses exactly my issue:

<img width="602" alt="WoWScrnShot_010623_143945" src="https://user-images.githubusercontent.com/1410282/211024326-e0b41806-da6b-48d0-aa09-26dfe0c1a082.png">

But I think my suggestion would still be a good addition.

**Comment by frozn** [comment]
I added the unit reaction for honored, revered and exalted NPCs. It's included in release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release).
