### ISSUE TITLE
Lua error 

### ISSUE THREAD

**Issue by Niyuni** [frozn/TipTac#164]
Latest Version of TipTac and WoW.

1954x [string "return function() local local_env = aura_en..."]:68: attempt to index field 'game_tooltip' (a nil value)
[string "return function() local local_env = aura_env or {}"]:68: in function <[string "return function() local local_env = aura_en..."]:64>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "@FrameXML/GameTooltip.lua"]:954: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1476: in function <FrameXML/UIParent.lua:1399>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @Altoholic/Services/Tooltip.lua:616
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 ttLastUpdate = 0
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBackdropColor = <function> defined @TipTac/ttCore.lua:1771
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:324
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 hasMoney = 1
 ttDisplayingUnit = false
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetAzeritePower = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined @Altoholic/Services/Tooltip.lua:616
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined =[C]:-1
 SetTotem = <function> defined

**Comment by frozn** [comment]
This seems not related to TipTac. The field "game_tooltip" isn't used anywhere.

Perhaps you can give the latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release) a try.
