### ISSUE TITLE
Lua Error...

### ISSUE THREAD

**Issue by Milky063** [frozn/TipTac#165]
**Describe the bug**
lua Error

**To Reproduce**

**Expected behavior**

1x [ADDON_ACTION_FORBIDDEN] AddOn 'TipTac' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:157: in function `ActionButtonUp'
[string "ACTIONBUTTON2"]:4: in function <[string "ACTIONBUTTON2"]:1>

**Screenshots**

**TipTac Reborn (please complete the following information):**
 - Version [e.g. 22.11.20, visible on top right in TipTac Reborn's config options (accessible with `/tiptac`)]

TipTac-v22.12.15-release.zip

**WoW (please complete the following information):**
 - Flavor: [e.g. Retail, WotLKC, Classic Era] Retail
 -
 - Version [e.g. 10.0.2, 3.4.0, 1.14.3, visible on top right in TipTac Reborn's config options (accessible with `/tiptac`)] 
tiptac: 22.12.15
wow: 10.0.2

**Additional context**

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
