### ISSUE TITLE
TipTac has been blocked from an action only available for the Blizzard UI.

### ISSUE THREAD

**Issue by BoomsiFTW** [frozn/TipTac#166]
**Describe the bug**
Getting randomly the message: "TipTac has been blocked from an action only available for the Blizzard UI...."
After that, I am not able to use my bindings to cast spells and stuff. What is working, is when I CLICK the spells in the bar instead.
After reloading it is working again for some time.
I don't get any lua errors.
The error above only shows up with activated TipTac. No other addon is generating this kind of error.

**To Reproduce**
Not sure what needs to happen to get that error. Most of the time I get it in BGs or when infight.

**Expected behavior**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/44933479/210579800-261ded1a-3b22-459a-bdd3-6557bf68b39f.png)

**TipTac Reborn (please complete the following information):**
v22.12.15-release

**WoW (please complete the following information):**
Retail

**Additional context**
-

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
