### ISSUE TITLE
Conflict with "Plater" addon

### ISSUE THREAD

**Issue by kwonjt0501** [frozn/TipTac#168]
When used with the "plater" addon, a lua error occurs when the aura disappears. I've confirmed that the problem doesn't occur with the Blizzard nameplate, and the problem doesn't occur with "plater" alone.
Attached a screenshot.
![aura error](https://user-images.githubusercontent.com/114258227/211043242-578741e6-150a-407a-a691-76e2b2c4eeea.png)
TipTac-v22.12.15-release

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Fix will be included in the next release.

**Comment by frozn** [comment]
Fixed with release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release).
