### ISSUE TITLE
2x SharedXML/Color.lua:60: bad argument #2 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by tatatada** [frozn/TipTac#177]
2x SharedXML/Color.lua:60: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@SharedXML/Color.lua"]:60: in function <SharedXML/Color.lua:59>
[string "=(tail call)"]: ?
[string "@TipTac/ttStyle.lua"]:281: in function `GeneratePetLines'
[string "@TipTac/ttStyle.lua"]:340: in function `ModifyUnitTooltip'
[string "@TipTac/ttStyle.lua"]:470: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:688: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:2238: in function `SetUnitAppearanceToTip'
[string "@TipTac/ttCore.lua"]:2336: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:688: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1195: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1086: in function <TipTac/ttCore.lua:1085>
...
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:970: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1476: in function <FrameXML/UIParent.lua:1399>
[string "=[C]"]: ?

Locals:
(*temporary) = "|c%s%s|r"
(*temporary) = "ffffffff"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by frozn** [comment]
Please check if there is a valid color set under "Colors->Race & Creature Type Color".

**Comment by Dairyman** [comment]
The colour is not the problem it is set to  "ffffffff" see the locals variables
```
Locals:
(*temporary) = "|c%s%s|r"
(*temporary) = "ffffffff"
(*temporary) = nil
(*temporary) = "string expected, got nil"
```
The text part of it is `nil` which maps to `unitRecord.name`.

I get the errors in pet battles when hovering the Pet Icons up top.

**Comment by frozn** [comment]
I nailed it down. The fix will be included in the next release. 👍
