### ISSUE TITLE
Latest version Makes Some Drop-Down Menu's Small

### ISSUE THREAD

**Issue by Pillgar** [frozn/TipTac#178]
On TipTac v23.01.23, the drop down menu's for Recount addon become very small.   Disabling Tiptac makes the drop down menu's for Recount normal again.

**Comment by frozn** [comment]
This is a bug in library "LibDropDown-1.0" which is used by Recount. Same error like in Outfitter, see here: #147.

I "solve" this I added TipTac's styling of the dropdown menu from LibDropdown-1.0. Scaling is also considered. Works fine now in the dev version. If you want to try it for yourself, here it is:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/10503732/TipTac-dev.zip)

This will be included in the upcoming release.
