### ISSUE TITLE
TipTacTalents getclasscolor error

### ISSUE THREAD

**Issue by Snichy** [frozn/TipTac#181]
Hi,

Im getting the below error message when hovering over a group mate (mainly in instances).  Its the latest version of WoW Retail and 23.1.23 version of TipTac Reborn.

`153x Usage: local classInfo = C_CreatureInfo.GetClassInfo(classID)
[string "=[C]"]: in function `GetClassInfo'
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:803: in function `GetClassColor'
[string "@TipTacTalents/ttTalents.lua"]:219: in function `TTT_UpdateTooltip'
[string "@TipTacTalents/ttTalents.lua"]:139: in function <TipTacTalents/ttTalents.lua:105>
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:137: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:135>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:970: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1486: in function <FrameXML/UIParent.lua:1409>

Locals:
(*temporary) = "Usage: local classInfo = C_CreatureInfo.GetClassInfo(classID)"`

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Will be fixed with the next release.
