### ISSUE TITLE
LUA error during pet battle

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#182]
**Describe the bug**
Some pet battles, presumably ones against an enemy pet and not a tamer (e.g. "The Oldest Dragonfly" WQ), generate the following LUA error:
3x SharedXML/Color.lua:60: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@SharedXML/Color.lua"]:60: in function <SharedXML/Color.lua:59>
[string "=(tail call)"]: ?
[string "@TipTac/ttStyle.lua"]:281: in function `GeneratePetLines'
[string "@TipTac/ttStyle.lua"]:340: in function `ModifyUnitTooltip'
[string "@TipTac/ttStyle.lua"]:470: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:688: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:2238: in function `SetUnitAppearanceToTip'
[string "@TipTac/ttCore.lua"]:2336: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:688: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1195: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1086: in function <TipTac/ttCore.lua:1085>
...
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:970: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1476: in function <FrameXML/UIParent.lua:1399>
[string "=[C]"]: ?

Locals:
(*temporary) = "|c%s%s|r"
(*temporary) = "ffffffff"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**To Reproduce**
1. Go to some open world battle pet fight (e.g. Enyobon /way #2025 39.5 73.6)
2. Start pet battle.
3. Observe LUA error immediately and every time when hovering over the enemy pet.

**Expected behavior**
There should be no LUA errors.

**TipTac Reborn (please complete the following information):**
 - Version 23.01.23

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.5

**Additional context**
Does not happen outside battle (hovering over the enemy pet before/after the battle won't generate the error).
The problem was not present in previous versions.

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Related to #177. The fix will be included in the next release.

**Comment by hollo6** [comment]
Thanks! Indeed this is no longer an issue after today's changes.
