### ISSUE TITLE
Interface/SharedXML/Color.lua:60: bad argument #2 to 'format' (string expected, got nil) (GeneratePlayerLines)

### ISSUE THREAD

**Issue by Jeremy7600** [frozn/TipTac#183]
**Describe the bug**
Bug appears intermittently when navigating the world. 

**To Reproduce**

1. Walk to Cooking Daily quest giver in Dalaran
2. Hover over quest giver
3. See error

**Expected behavior**
No error

**TipTac Reborn (please complete the following information):**
 - Version 23.01.23
 
**WoW (please complete the following information):**
 - Flavor: Wrath
 - Version 3.4.1

**Additional context**
Message: Interface/SharedXML/Color.lua:60: bad argument #2 to 'format' (string expected, got nil)
Time: Fri Jan 27 11:51:38 2023
Count: 20
Stack: Interface/SharedXML/Color.lua:60: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `format'
[string "@Interface/SharedXML/Color.lua"]:60: in function <Interface/SharedXML/Color.lua:59>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TipTac/ttStyle.lua"]:229: in function `GeneratePlayerLines'
[string "@Interface/AddOns/TipTac/ttStyle.lua"]:338: in function `ModifyUnitTooltip'
[string "@Interface/AddOns/TipTac/ttStyle.lua"]:470: in function `?'
[string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:688: in function `FireGroupEvent'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:2238: in function `SetUnitAppearanceToTip'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:2319: in function <Interface/AddOns/TipTac/ttCore.lua:2278>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:

**Comment by Jeremy7600** [comment]
Does not always happen at this quest giver.

**Comment by frozn** [comment]
Seems a little strange to me that the error occures in function `GeneratePlayerLines()` because it's a NPC. I walked to the quest giver and got no error if hovering over this unit.

But in the case `UnitRace()` doesn't return a valid race, the error you mentioned occures. So I added a check for this case. This will be included in the next release. 👍

**Comment by Jeremy7600** [comment]
It is random and maybe a player walked under my cursor. It happened later just walking around Dalaran, I didn't notice who my mouse was on.
