### ISSUE TITLE
Health and mana bars not displaying within tooltip

### ISSUE THREAD

**Issue by caricatura** [frozn/TipTac#186]
**Describe the bug**
Health and mana bars no longer display within the tooltip since the last 2 versions. They are being displayed as a long line at the bottom of the screen 

**To Reproduce**
1. Enable health and or mana bars
2. Mouseover a unit
3. View detached health and or mana bars at the bottom of the screen taking up full screen width

**Expected behavior**
Health and mana bars should be displayed within the tooltip as was the case in previous versions
**Screenshots**
![WoWScrnShot_012923_004930](https://user-images.githubusercontent.com/1388291/215310512-cff7898c-d8a0-498f-9854-da48bfcf9f7b.jpg)

**TipTac Reborn (please complete the following information):**
 - Version 23.01.28

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.5

**Comment by frozn** [comment]
Unfortunately I can't reproduce this on my side. I suggest reinstalling and replacing the 4 TipTac folders and to disable all other addons to exclude things.

**Comment by helicdark** [comment]
Same thing happened in WotLK Classic 3.4.0 & 3.4.1

**Comment by frozn** [comment]
I fixed this issue with the latest release [v23.02.05](https://github.com/frozn/TipTac/releases/tag/v23.02.05-release). 👍
