### ISSUE TITLE
Tooltip showing up enlarged

### ISSUE THREAD

**Issue by Peregran** [frozn/TipTac#187]
**Describe the bug**
After using chocolate data broker and mousing over some of the options the tooltips of various items show bigger than normal.   If I disable the LDB, I don't see the issue (quick test, not comprehensive)

**To Reproduce**
1. Roll over a action button, tooltip is normal size
2. Roll over a item in chocolate ldb and tooltip is larger
3. Doing something random (not sure what) the tooltip returns to normal size.
4. Issue did not occur before your code rewrite 2 versions back

**Expected behavior**
Tooltips should always be same general size.   Worked fine with 22.12.15

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/73302712/215330958-e76fb494-44f4-44a0-96fe-ea309db95dfb.png)

After (larger):
![image](https://user-images.githubusercontent.com/73302712/215330983-276f6608-678f-4385-a7ec-4b1ad2ab4964.png)

**TipTac Reborn (please complete the following information):**
Version 23.01.28

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.5

**Additional context**

**Comment by Peregran** [comment]
Issue appears to be with "Currency Tracking" LDB.   If I comment out all the "Setscale" calls for the tooltips in that addon the issue doesn't happen, so I'm guessing it is messing with the tooltip scales and not resetting it.   Perhap this helps in determining the issue as it didn't happen pre-code rewrite.

**Comment by outlawzgosu** [comment]
I'm having the same issue and I also use Currency tracking. Mousing over the currency tracking icons on the screen makes tooltips large and I have to /reload to set them back to normal.

I temporarily fixed this issue by creating a new addon that creates an invisible frame over Currency Tracker, preventing the mouse from mousing over the icons. Seems to work for the time being but would love for currency tracker and tiptac to work together.

**Comment by lowpita** [comment]
![image](https://user-images.githubusercontent.com/14031869/215348234-5a304fa5-0b78-407b-aff1-65eeb02b8c27.png)
Hey. I have a similar issue with this happening on savedinstances when mouseovering the minimap icon.

**Comment by Peregran** [comment]
No need to create a frame over currency tracking you could just disable the addon until the issue is resolved.   Since I am a developer (at least part time), I just commented out the code in currency tracker so it still works but without the scaling issue until either this addon and/or the other addon are fixed depending what the real issue is (not blaming anyone).

**Comment by frozn** [comment]
I improved setting tip's scale and removed calling tip:SetIgnoreParentScale(true) to improve compatibility to other addons.

Fix will be included in the next release. 👍
