### ISSUE TITLE
Last two releases broke cursor's anchoring 

### ISSUE THREAD

**Issue by k1ck3r** [frozn/TipTac#188]
**Describe the bug**
I had to be sure that properly checked that exactly _last two_ version broke things for me. Unfortunately, anchoring is acting crazy. Here is the link with the following screens made https://imgur.com/a/Wr78DRd

Now to the real things. I'm using mouse anchoring, Top Left on every units (no matter world or unit) and with some additional adjustments to X/Y through menu "Mouse" in TipTac. Here goes nothing:

1. Cursor is on position on portal and seems Top Left alignment works.
2. Just to ensure that Top Left alignment works for units.
3. On 3rd screen we go fancy: we move -10 X and keep 0 at Y - result is: _changes to Y_
4. On 4th - +10 X / - 10 Y and now we have more like Bottom Right alignment. Cursor is still on Top Left, but now movement is again on Y only
5. Last few screenshots just shows that whatever i action take for positioning precisely the tooltip, it just acts strange. 
6. On the very last SS, tooltip is not skinned on the following Blizz's frames: SpellBook, Proffessions Pane, Adventure Guide. It did however works with Talents, Achievements, Collections

**To Reproduce**

1. Use version **23.01.28** or **23.01.23** of TipTac
2. Nothing fancy, just play around with positioning tooltip more precisely on Mouse Anchor 
3. The most strange thing of all is, that once i downgrade to version 22.12.15 all of the above is gone as issue.

WoW Version: Retail Live (10.0.5)

**Comment by frozn** [comment]
Thanks for reporting this! 👍

I accidentally set mouse anchor X offset also to mouse anchor Y offset internally. 🙈

The fix will be included in the next release. If you don't want to wait, here's the actual dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/10539163/TipTac-dev.zip)

Duplicate of #176.

**Comment by k1ck3r** [comment]
Much appreciate your time spent ;) Will try it for sure! Thanks again for keeping this project UP!

**Comment by frozn** [comment]
TipTac only reanchors tooltips if they would be displayed on blizzards default position (normally in the right bottom corner). If a tooltip for example is anchored next to a buff you're hovering over, TipTac won't reanchor it.

In the past TipTac accidentally reanchors some tooltips what shouldn't happen. This has been fixed with the latest releases.
