### ISSUE TITLE
Quality border for Battle pets

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#19]
Quality border for Battle pets is now absent. I think It's good to be added.
https://imgur.com/a/9PGFQFW

**Comment by frozn** [comment]
Can't reproduce it in the current version. Quality border color for battle pets in auction house is working fine:

![image](https://user-images.githubusercontent.com/5655881/149420833-f47474cb-01a8-415f-a30f-6276f01a32e7.png)
