### ISSUE TITLE
Request: <optional> disable custom tooltip anchoring

### ISSUE THREAD

**Issue by Rezy942** [frozn/TipTac#190]
**Is your feature request related to a problem? Please describe.**
Currently from what I can see - there is no one-for-all solution that disables custom anchoring. (please direct me if im wrong).
A user can instead click "anchor" and reposition the tooltip anchors.

**Describe the solution you'd like**
Perhaps a button in anchoring tab that will default all anchoring to blizzard standard?
It can be named "let Blizzard control tooltip anchoring" or something.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Thank you for keeping up this amazing addon

**Comment by frozn** [comment]
You're right. This option is missing and nice to have. 👍 

I added a checkbox under "Anchors" to enable/disable anchor modifications. Will be included in the next release.

**Comment by Rezy942** [comment]
Thank you SO much!!!
