### ISSUE TITLE
LUA error on paragon reward tooltip

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#191]
**Describe the bug**
Upon hovering over a paragon reward tooltip, I get the following LUA error:
45x ...libs/LibFroznFunctions-1.0-4/LibFroznFunctions-1.0.lua:255: attempt to perform arithmetic on a nil value
[string "@TipTac/libs/LibFroznFunctions-1.0-4/LibFroznFunctions-1.0.lua"]:255: in function `RefreshAnchorShoppingTooltips'
[string "@TipTac/ttCore.lua"]:2206: in function <TipTac/ttCore.lua:2204>
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@FrameXML/QuestUtils.lua"]:466: in function `QuestUtils_AddQuestRewardsToTooltip'
[string "@FrameXML/GameTooltip.lua"]:217: in function <FrameXML/GameTooltip.lua:201>
[string "=[C]"]: in function `GameTooltip_AddQuestRewardsToTooltip'
[string "@FrameXML/ReputationFrame.lua"]:312: in function `ReputationParagonFrame_SetupParagonTooltip'
[string "@FrameXML/ReputationFrame.lua"]:333: in function <FrameXML/ReputationFrame.lua:330>

Locals:
self = <table> {
 CreatePushArray = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:580
 GetAverageItemLevel = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2133
 MixinDifferingObjects = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:715
 FormatText = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:372
 RegisterForGroupEvents = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:776
 GetValueFromObjectByPath = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:677
 MirrorAnchorPointCentered = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1140
 HookScriptOnTooltipSetItem = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:170
 IsAverageItemLevelAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2105
 CallFunctionAndSuppressErrorMessageAndSpeech = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:653
 AreTalentsAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1955
 GetItemQualityColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:988
 CanInspect = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1737
 IsInspectFrameOpen = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1729
 RegisterNewSlashCommands = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:848
 IsTableEmpty = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:396
 RecalculateSizeOfGameTooltip = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1262
 InspectUnit = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1629
 CreateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1530
 CreateMarkupForClassIcon = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1066
 UnitIsWildBattlePet = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:75
 UpdateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1567
 ExistsInTable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:589
 HookSecureFuncIfExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:746
 GetClassColorByClassFile = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:947
 UnitIsBattlePetCompanion = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:87
 GetUnitReactionIndex = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1430
 GetPowerColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:979
 FontExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1280
 TextureExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1307
 RemoveCallbackFromQueuedInspectCallbacks = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1675
 IsFrameBackInFrameChain = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1223
 CallFunctionDelayed = <function> defined @

**To Reproduce**
1. Have an uncollected paragon reward chest
2. Open Reputation pane
3. Hover over the paragon reward (bag icon)
4. See the above LUA error pop up

**Expected behavior**
No LUA errors should be popping up.

**Screenshots**
![image](https://user-images.githubusercontent.com/365584/215770771-40aba3a1-9486-4ed7-add2-f1009148d57d.png)

**TipTac Reborn (please complete the following information):**
 - Version 23.01.28 (dev version from https://github.com/frozn/TipTac/issues/180#issuecomment-1409393148 )

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.5

**Comment by frozn** [comment]
Fixed in main branch. Will be included in the next release. 👍

**Comment by frozn** [comment]
I pushed out all fixes regarding comparing items with today's release ([v23.02.06](https://github.com/frozn/TipTac/releases/tag/v23.02.06-release)).

**Comment by hollo6** [comment]
Working now, thank you!
