### ISSUE TITLE
Bug: Tooltip health & mana bars size of whole screen when backdrop modifications are disabled

### ISSUE THREAD

**Issue by Rezy942** [frozn/TipTac#192]
**Describe the bug**
When unchecking this box, the tooltip bars go crazy.
![image](https://user-images.githubusercontent.com/122007087/215799370-ad1b87a4-aa61-49ef-9b81-b8e5bdddbf14.png)
This happens with 0 other addons enabled.

**Expected behavior**
I want to be able to stop the addon from recoloring the backdrop of tooltips and just leave it at blizzard default.
Currently it works but as you can see, the bars go nuts.

**Screenshots**
![image](https://user-images.githubusercontent.com/122007087/215799232-da2dd0a6-41e2-4c2e-ad26-6c8d712e9833.png)

**Comment by frozn** [comment]
I haven't seen this error because and didn't disable this option normally. 🙈

Fixed this. Will be included in the next release. 👍

**Comment by Rezy942** [comment]
Thanks a lot!
