### ISSUE TITLE
LUA error on random tooltips

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#194]
**Describe the bug**
I got this when hovering over a Dalaran Hearthstone. Yesterday it popped up for something completely different, I believe it was Inscription but not 100% sure about that.

2x ...libs/LibFroznFunctions-1.0-4/LibFroznFunctions-1.0.lua:250: attempt to perform arithmetic on a nil value
[string "@TipTac/libs/LibFroznFunctions-1.0-4/LibFroznFunctions-1.0.lua"]:250: in function `RefreshAnchorShoppingTooltips'
[string "@TipTac/ttCore.lua"]:2206: in function <TipTac/ttCore.lua:2204>
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@SharedXML/Tooltip/TooltipDataRules.lua"]:161: in function `func'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:49: in function <SharedXML/Tooltip/TooltipDataHandler.lua:44>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:71: in function <SharedXML/Tooltip/TooltipDataHandler.lua:67>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:135: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@FrameXML/ActionButton.lua"]:906: in function `SetTooltip'
[string "@FrameXML/ActionButton.lua"]:1185: in function <FrameXML/ActionButton.lua:1180>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:322: in function <FrameXML/SecureHandlers.lua:306>
[string "=(tail call)"]: ?

Locals:
self = <table> {
 CreatePushArray = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:580
 GetAverageItemLevel = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2133
 MixinDifferingObjects = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:715
 FormatText = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:372
 RegisterForGroupEvents = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:776
 GetValueFromObjectByPath = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:677
 MirrorAnchorPointCentered = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1140
 HookScriptOnTooltipSetItem = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:170
 IsAverageItemLevelAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2105
 CallFunctionAndSuppressErrorMessageAndSpeech = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:653
 AreTalentsAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1955
 GetItemQualityColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:988
 CanInspect = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1737
 IsInspectFrameOpen = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1729
 RegisterNewSlashCommands = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:848
 IsTableEmpty = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:396
 RecalculateSizeOfGameTooltip = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1262
 InspectUnit = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1629
 CreateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1530
 CreateMarkupForClassIcon = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1066
 UnitIsWildBattlePet = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:75
 UpdateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1567
 ExistsInTable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:589
 HookSecureFuncIfExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:746
 GetClassColorByClassFile = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:947
 UnitIsBattlePetCompanion = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:87
 GetUnitReactionIndex = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1430
 GetPowerColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:979
 FontExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1280
 TextureExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1307
 RemoveCallbackFromQueuedInspectCallbacks = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1675
 IsFrameBackInFrameChain = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1223
 CallFunctionDelayed = <function> defined @

**To Reproduce**
1. Hover over some random tooltip, try Dalaran Hearthstone or some profession skill (possibly has to be very soon after logging in)
2. Observe the above LUA error

**Expected behavior**
I should not get any LUA errors.

**TipTac Reborn (please complete the following information):**
 - Version 23.01.28 (dev version from https://github.com/frozn/TipTac/issues/180#issuecomment-1409393148 )

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.5

**Additional context**
Possibly only happens soon after logging in.

**Comment by frozn** [comment]
Fixed in main branch. Will be included in the next release. 👍

**Comment by frozn** [comment]
I pushed out all fixes regarding comparing items with today's release ([v23.02.06](https://github.com/frozn/TipTac/releases/tag/v23.02.06-release)).

**Comment by hollo6** [comment]
Seems to be fixed, I no longer receive these errors. Thanks!
