### ISSUE TITLE
LUA error on currency tooltip

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#196]
**Describe the bug**
When hovering over the popup on completing a WQ:

2x Usage: local link = C_CurrencyInfo.GetCurrencyLink(type [, amount])
[string "=[C]"]: ?
[string "@TipTacItemRef/ttItemRef.lua"]:746: in function <TipTacItemRef/ttItemRef.lua:741>
[string "=[C]"]: in function `SetQuestLogCurrency'
[string "@FrameXML/AlertFrameSystems.lua"]:117: in function <FrameXML/AlertFrameSystems.lua:104>

Locals:
(*temporary) = "Usage: local link = C_CurrencyInfo.GetCurrencyLink(type [, amount])"

**To Reproduce**
1. Complete a WQ with a currency reward (only saw this for gold but probably anything else works)
2. Hover over the WQ reward tooltip
5. See above LUA error

**Expected behavior**
No LUA error.

**TipTac Reborn (please complete the following information):**
 - Version 23.01.28-dev

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.5

**Additional context**
ttItemRef.lua L746: there is an _ indstead of a .

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Fixed with next release.

**Comment by hollo6** [comment]
Fixed indeed, thanks!
