### ISSUE TITLE
Bug: Confliction with NovaInstanceTracker

### ISSUE THREAD

**Issue by Cameronza** [frozn/TipTac#199]
Currently when hovering over the minimap button of the addon NovaInstanceTracker, it doesn't show the tooltip correctly as shown below. 

![D5P131h](https://user-images.githubusercontent.com/17275831/217261287-e4970883-fb28-4cd0-879c-fd5eae12fbba.png)

**TipTac Reborn:**
 - Version: 23.02.06

**NovaInstanceTracker:**
 - Version: 1.40

**WoW:**
 - Flavor: WotLKC
 - Version: 3.4.1

**Comment by frozn** [comment]
Installed NovaInstanceTracker for myself and can't reproduce this issue. Seems fine to me in WotLKC:

![image](https://user-images.githubusercontent.com/5655881/217374320-ae7f81e4-eb67-4094-b8aa-4f6d4e1a7e45.png)

Do you get an error log?

**Comment by Cameronza** [comment]
> Do you get an error log?

Not sure where I'd go to look at an error log apart from .lua errors, but I was able to recreate the bug messing around with TipTac. I reset the addon to default settings, picked the Blizzard layout and then tried to show item level in the ItemRef section.

**Comment by Cameronza** [comment]
Fixed with latest update, thank you.
