### ISSUE TITLE
Classic Era / SoM error

### ISSUE THREAD

**Issue by alphabitnz** [frozn/TipTac#2]
TipTac\ttStyle.lua:55: attempt to call upvalue 'UnitQuestTrivialLevelRange' (a nil value)

```
8x TipTac\ttStyle.lua:55: attempt to call upvalue 'UnitQuestTrivialLevelRange' (a nil value)
[string "@TipTac\ttStyle.lua"]:55: in function <TipTac\ttStyle.lua:47>
[string "@TipTac\ttStyle.lua"]:221: in function `ModifyUnitTooltip'
[string "@TipTac\ttStyle.lua"]:296: in function `?'
[string "@TipTac\ttCore.lua"]:298: in function `SendElementEvent'
[string "@TipTac\ttCore.lua"]:662: in function `ApplyUnitAppearance'
[string "@TipTac\ttCore.lua"]:841: in function <TipTac\ttCore.lua:802>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
level = -3
(*temporary) = nil
(*temporary) = "player"
(*temporary) = "attempt to call upvalue 'UnitQuestTrivialLevelRange' (a nil value)"
tt = TipTac {
 CreatePushArray = <function> defined @TipTac\ttCore.lua:269
 elements = <table> {
 }
 ClassColorMarkup = <table> {
 }
 AddModifiedTip = <function> defined @TipTac\ttCore.lua:976
 MirrorAnchorsSmart = <table> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 CVAR_UPDATE = <function> defined @TipTac\ttCore.lua:395
 u = <table> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 playerLevel = 60
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 isColorBlind = false
 ApplyUnitAppearance = <function> defined @TipTac\ttCore.lua:626
 BottomEdge = <unnamed> {
 }
 CURSOR_UPDATE = <function> defined @TipTac\ttCore.lua:327
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 AnchorFrameToMouse = <function> defined @TipTac\ttCore.lua:533
 MirrorAnchors = <table> {
 }
 RegisterElement = <function> defined @TipTac\ttCore.lua:289
 PLAYER_LEVEL_UP = <function> defined @TipTac\ttCore.lua:344
 RemoveUnwantedLines = <function> defined @TipTac\ttCore.lua:542
 0 = <userdata>
 yPadding = 11
 tipsToModify = <table> {
 }
 backdropInfo = <table> {
 }
 SendElementEvent = <function> defined @TipTac\ttCore.lua:295
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 text = <unnamed> {
 }
 GetUnitReactionIndex = <function> defined @TipTac\ttCore.lua:572
 close = <unnamed> {
 }
 ApplySettings = <function> defined @TipTac\ttCore.lua:470
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 Center = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 TopEdge = <unnamed> {
 }
 AddTargetedBy = <function> defined @TipTac\ttCore.lua:598
 ApplyTipBackdrop = <function> defined @TipTac\ttCore.lua:519
 BottomRightCorner = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 xPadding = 0
}
UnitQuestTrivialLevelRange = nil

```

**Comment by k1ck3r** [comment]
Yep, facing such issues with TipTac, once any other compatible-addon with it tries to call its functions (eg. Elv, Bazooka, even Blizz's Garrison UI drops some errors upon hovering:( )

**Comment by frozn** [comment]
thanks for reporting this. fixed with [v21.12.02](https://github.com/frozn/TipTac/releases/tag/v21.12.02).

@k1ck3r: can you describe the problem and provide an error log and the version you are using?

**Comment by k1ck3r** [comment]
```
7x ...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:870: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:870: in function `GarrisonLandingPageReportMission_OnEnter'
[string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:828: in function `GarrisonLandingPageReportList_UpdateMouseOverTooltip'
[string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:281: in function <...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:281>
[string "=[C]"]: ?

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:12
 textLeft1Font = "GameTooltipHeaderText"
 SetAction = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 hasMoney = 1
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
 BottomOverlay = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 updateTooltipTimer = 0.072000
 HasBackdropInfo = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:18
 ClearLines = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 SetupTextureCoordinates = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:16
 comparing = false
 SetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:27
 ClearBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:34
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 default = 1
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetQuestItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 waitingForData = false
 FadeOut = <function> defined @TipTac\ttCore.lua:877
 numMoneyFrames = 1
 ApplyBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:22
 PixelSnapDisabled = true
 SetRecipeReagentItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = GameTooltipTextLeft1 {
 }
 Show = <function> defined =[C]:-1
 GetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:19
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:13
 SetUnitBuff = <function> defined =[C]:-1
 GetBackdropCoordValue = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:15
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
 textRight1Font = "GameTooltipHeaderText"
 ttIcon = <unnamed> {
 }
 GetEdgeSize = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:14
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 ttGradient = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 SetUnitAura = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:17
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 ttCount = <unnamed> {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
(*temporary) = "LEFT"
(*temporary) = GarrisonLandingPageReportListListScrollFrameButton2 {
 EncounterIcon = <unnamed> {
 }
 MissionTypeIcon = <unnamed> {
 }
 id = 3
 Rewards = <table> {
 }
 BG = <unnamed> {
 }
 MissionType = <unnamed> {
 }
 0 = <userdata>
 Title = <unnamed> {
 }
 Reward2 = <unnamed> {
 }
 Status = <unnamed> {
 }
 Reward3 = <unnamed> {
 }
 TimeLeft = <unnamed> {
 }
 Reward1 = <unnamed> {
 }
}
(*temporary) = "RIGHT"
(*temporary) = 0
(*temporary) = 0
 ```

This error is quite consistent - on every login, once get out of combat, and hover something. I've tried your new version as well, nothing changed, BUT now i'm able to skin the tooltip using some other way - creating an overlay trigger - otherwise:

- styling doesn't work at all, i can't even set  the background to a solid color
- the most annoying thing is the border (!) can't do anything with it.
- what i've tried (so i can provide some descent checks before reporting:
   - 0 addons - 0 configuration - only TT
   - installed the game on a different location/disk - only TT - no result whatsoever
   - at this point i've thought "it might be my pc" and installed the game on my work laptop. same was done through my wife's account. Nothing really can be done via TT - Even changing the size/style of the tooltip's text makes my pc (and my wife's!) to stutter for few seconds

Hope you'll find the buggy shit

**Comment by alphabitnz** [comment]
> ```
> 7x ...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:870: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
> [string "=[C]"]: in function `SetPoint'
> [string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:870: in function `GarrisonLandingPageReportMission_OnEnter'
> [string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:828: in function `GarrisonLandingPageReportList_UpdateMouseOverTooltip'
> [string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:281: in function <...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:281>
> [string "=[C]"]: ?
> 
> Locals:
> (*temporary) = GameTooltip {
>  0 = <userdata>
>  OnBackdropLoaded = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:12
>  textLeft1Font = "GameTooltipHeaderText"
>  SetAction = <function> defined =[C]:-1
>  ItemTooltip = <unnamed> {
>  }
>  SetHyperlink = <function> defined =[C]:-1
>  hasMoney = 1
>  SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
>  BottomOverlay = <unnamed> {
>  }
>  GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
>  updateTooltipTimer = 0.072000
>  HasBackdropInfo = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:18
>  ClearLines = <function> defined =[C]:-1
>  TextRight1 = GameTooltipTextRight1 {
>  }
>  SetupTextureCoordinates = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:16
>  comparing = false
>  SetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:27
>  ClearBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:34
>  TopOverlay = <unnamed> {
>  }
>  GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
>  default = 1
>  SetUnitDebuff = <function> defined =[C]:-1
>  SetItemByID = <function> defined =[C]:-1
>  textRight2Font = "GameTooltipText"
>  SetQuestItem = <function> defined =[C]:-1
>  shoppingTooltips = <table> {
>  }
>  waitingForData = false
>  FadeOut = <function> defined @TipTac\ttCore.lua:877
>  numMoneyFrames = 1
>  ApplyBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:22
>  PixelSnapDisabled = true
>  SetRecipeReagentItem = <function> defined =[C]:-1
>  layoutType = "TooltipDefaultLayout"
>  TextLeft1 = GameTooltipTextLeft1 {
>  }
>  Show = <function> defined =[C]:-1
>  GetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:19
>  SetQuestLogItem = <function> defined =[C]:-1
>  OnBackdropSizeChanged = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:13
>  SetUnitBuff = <function> defined =[C]:-1
>  GetBackdropCoordValue = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:15
>  SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
>  textRight1Font = "GameTooltipHeaderText"
>  ttIcon = <unnamed> {
>  }
>  GetEdgeSize = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:14
>  NineSlice = <unnamed> {
>  }
>  textLeft2Font = "GameTooltipText"
>  ttGradient = <unnamed> {
>  }
>  TextRight2 = GameTooltipTextRight2 {
>  }
>  TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
>  SetUnitAura = <function> defined =[C]:-1
>  SetInventoryItem = <function> defined =[C]:-1
>  SetBagItem = <function> defined =[C]:-1
>  needsReset = true
>  SetupPieceVisuals = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:17
>  SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
>  ttCount = <unnamed> {
>  }
>  TextLeft2 = GameTooltipTextLeft2 {
>  }
> }
> (*temporary) = "LEFT"
> (*temporary) = GarrisonLandingPageReportListListScrollFrameButton2 {
>  EncounterIcon = <unnamed> {
>  }
>  MissionTypeIcon = <unnamed> {
>  }
>  id = 3
>  Rewards = <table> {
>  }
>  BG = <unnamed> {
>  }
>  MissionType = <unnamed> {
>  }
>  0 = <userdata>
>  Title = <unnamed> {
>  }
>  Reward2 = <unnamed> {
>  }
>  Status = <unnamed> {
>  }
>  Reward3 = <unnamed> {
>  }
>  TimeLeft = <unnamed> {
>  }
>  Reward1 = <unnamed> {
>  }
> }
> (*temporary) = "RIGHT"
> (*temporary) = 0
> (*temporary) = 0
> ```
> 
> This error is quite consistent - on every login, once get out of combat, and hover something. I've tried your new version as well, nothing changed, BUT now i'm able to skin the tooltip using some other way - creating an overlay trigger - otherwise:
> 
>     * styling doesn't work at all, i can't even set  the background to a solid color
> 
>     * the most annoying thing is the border (!) can't do anything with it.
> 
>     * what i've tried (so i can provide some descent checks before reporting:
>       
>       * 0 addons - 0 configuration - only TT
>       * installed the game on a different location/disk - only TT - no result whatsoever
>       * at this point i've thought "it might be my pc" and installed the game on my work laptop. same was done through my wife's account. Nothing really can be done via TT - Even changing the size/style of the tooltip's text makes my pc (and my wife's!) to stutter for few seconds
> 
> 
> Hope you'll find the buggy shit

Log it as a fresh issue man, this one was mine which has been resolved and closed
