### ISSUE TITLE
Lua error with Blizzard_NamePlates

### ISSUE THREAD

**Issue by kwonjt2001** [frozn/TipTac#200]
hello. Let me ask you a question.
Playing while using the ally NamePlate display in the dungeon. At some point during play, I get an error related to screenshots. It seems to be necessary to check if it is a problem with another Addon.
I think we need to check whether it is a problem with another addon or a problem with Tiptac.
 However, there seemed to be no problem with TipTac-v23.01.28-release.

- Currently using TipTac-v23.02.06-release.
![WoWScrnShot_020923_153838](https://user-images.githubusercontent.com/98691652/217779561-781ee654-7fa0-4b29-9458-bf024bea5ef0.jpg)
![WoWScrnShot_020923_153842](https://user-images.githubusercontent.com/98691652/217779365-7d6648d1-01e7-4fa3-b4f1-79b378852061.jpg)
![WoWScrnShot_020923_153847](https://user-images.githubusercontent.com/98691652/217779471-ab4bb761-9f6e-4097-b210-5eff80e02194.jpg)
![WoWScrnShot_020923_153851](https://user-images.githubusercontent.com/98691652/217779653-8a9ab540-460a-4258-9634-44c38c7ca25b.jpg)
![WoWScrnShot_020923_153857](https://user-images.githubusercontent.com/98691652/217779707-dfde2599-e739-4725-b867-cc04ce7c1741.jpg)
![WoWScrnShot_020923_153902](https://user-images.githubusercontent.com/98691652/217779742-2afb55da-0952-4cda-8639-38e1eefaefe2.jpg)

**Comment by kwonjt0501** [comment]
TipTac-v23.01.28-release. Version also happens. It seems to appear when some event occurs in the dungeon. for example
It is remembered that it often appears when a player dies or finds a spy in the Palace of Stars.

**Comment by kwonjt2001** [comment]
TipTac-v23.01.28-release. Version also happens. It seems to appear when some event occurs in the dungeon. for example
It is remembered that it often appears when a player dies or finds a spy in the Palace of Stars.

**Comment by kwonjt2001** [comment]
> 팁택-v23.01.28 릴리스. 버전도 발생합니다. 던전에서 어떤 이벤트가 발생했을 때 나타나는 것 같습니다. 예를 들어 플레이어가 죽거나 별의 궁전에서 스파이를 찾을 때 자주 나타나는 것으로 기억됩니다.

**Comment by kwonjt2001** [comment]
Not sure, but In Azure Vault, the Umbrella Skull's Oppressive Miasma debuff seems to pop up on hover when displayed on the Blizzard nameplate. Let's check a little more.

**Comment by kwonjt2001** [comment]
It has been confirmed that when using the ally name tag display in a dungeon, a debuff pops up on the name tag and occurs when you mouse over it. This week's affix 'Bursting' also occurs.

**Comment by frozn** [comment]
In the meantime this has been fixed. I added several `IsForbidden()` checks to make shure, that the tooltip isn't accessed while it's protected.
