### ISSUE TITLE
ShoppingTooltip LUA error

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#203]
**Describe the bug**
https://github.com/frozn/TipTac/issues/194 is back, less frequently but more and more every day.
Pops up for any tooltip shortly after logging in.

3x ...libs/LibFroznFunctions-1.0-5/LibFroznFunctions-1.0.lua:268: attempt to perform arithmetic on a nil value
[string "@TipTac/libs/LibFroznFunctions-1.0-5/LibFroznFunctions-1.0.lua"]:268: in function `RefreshAnchorShoppingTooltips'
[string "@TipTac/ttCore.lua"]:2266: in function <TipTac/ttCore.lua:2262>
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@SharedXML/Tooltip/TooltipDataRules.lua"]:161: in function `func'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:49: in function <SharedXML/Tooltip/TooltipDataHandler.lua:44>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:71: in function <SharedXML/Tooltip/TooltipDataHandler.lua:67>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:135: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@FrameXML/ActionButton.lua"]:906: in function `SetTooltip'
[string "@FrameXML/ActionButton.lua"]:1185: in function <FrameXML/ActionButton.lua:1180>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:322: in function <FrameXML/SecureHandlers.lua:306>
[string "=(tail call)"]: ?

Locals:
self = <table> {
 CreatePushArray = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:598
 GetAverageItemLevel = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2151
 MixinDifferingObjects = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:733
 FormatText = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:390
 RegisterForGroupEvents = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:794
 GetValueFromObjectByPath = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:695
 MirrorAnchorPointCentered = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1158
 HookScriptOnTooltipSetItem = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:170
 IsAverageItemLevelAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2123
 CallFunctionAndSuppressErrorMessageAndSpeech = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:671
 AreTalentsAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1973
 GetItemQualityColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1006
 CanInspect = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1755
 IsInspectFrameOpen = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1747
 RegisterNewSlashCommands = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:866
 IsTableEmpty = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:414
 RecalculateSizeOfGameTooltip = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1280
 InspectUnit = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1647
 CreateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1548
 CreateMarkupForClassIcon = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1084
 UnitIsWildBattlePet = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:75
 UpdateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1585
 ExistsInTable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:607
 HookSecureFuncIfExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:764
 GetClassColorByClassFile = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:965
 UnitIsBattlePetCompanion = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:87
 GetUnitReactionIndex = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1448
 GetPowerColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:997
 FontExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1298
 TextureExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1325
 RemoveCallbackFromQueuedInspectCallbacks = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1693
 IsFrameBackInFrameChain = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1241
 CallFunctionDelayed = <function> defined @Interface

**To Reproduce**
1. Log in.
2. Hover over any button (maybe anything? I often get this for professions on action bars, hearthstones or icons on bag frame).
3. Observe the error above

**Expected behavior**
No LUA errors should be thrown.

**TipTac Reborn (please complete the following information):**
 - Version 23.02.06

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.0.5

**Comment by frozn** [comment]
I has been able to reproduce it. Will be included in the next release! 👍
