### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by kwonjt2001** [frozn/TipTac#204]
Report. Sometimes when connecting to WoW or reloading an Addon, the tooltip that appears for the first time sometimes shows the Blizzard basic health bar below.
 I've seen it several times. Looks like something needs to be checked.

 Using TipTac-v23.02.06-release.
![툴팁 아래 체력바](https://user-images.githubusercontent.com/98691652/219086437-76d97800-e183-4133-8b84-5dc4c59b0343.png)
![파티원](https://user-images.githubusercontent.com/98691652/219096768-be324fef-54dc-4ea3-b064-241114b9ffff.png)

**Comment by frozn** [comment]
You're right. I have seen it several times, too. But when I force to show it again, it didn't come up to reproduce it safely. 🤔

I'm on it...

**Comment by frozn** [comment]
I finally have been able to reproduce this, see #314. Fix will be included in the next release.
