### ISSUE TITLE
Error when loading TinyTip Template

### ISSUE THREAD

**Issue by VolleGH** [frozn/TipTac#206]
Hi,

I switched from version 22.12.15 to version 23.02.06. 
When clicking on loading the TinyTip Template the following error occurs, and the tooltip colours look different to what they were in 22.12.15.

1x TipTacOptions/ttLayouts.lua:235: attempt to index local 'TipTac' (a nil value)
[string "@TipTacOptions/ttLayouts.lua"]:235: in function `selectValueFunc'
[string "@TipTacOptions/libs/AzDropDown.lua"]:230: in function <TipTacOptions/libs/AzDropDown.lua:222>

Locals:
dropDown = Frame {
 0 = <userdata>
 SetText = <function> defined @TipTacOptions/libs/AzDropDown.lua:375
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 button = Button {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 option = <table> {
 }
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 ApplyOurBackdrop = <function> defined @TipTacOptions/libs/AzDropDown.lua:101
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 label = FontString {
 }
 selectedValue = "TinyTip"
 InitSelectedItem = <function> defined @TipTacOptions/libs/AzDropDown.lua:380
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 initFunc = <function> defined @TipTacOptions/ttLayouts.lua:244
 selectValueFunc = <function> defined @TipTacOptions/ttLayouts.lua:230
 class = <table> {
 }
 factory = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 text = FontString {
 }
 TopEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 isAutoSelect = true
 Center = Texture {
 }
 backdropInfo = <table> {
 }
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
entry = <table> {
 value = "TinyTip"
 text = "TinyTip"
 tip = "22 config variables will be applied"
}
index = 6
TipTac = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'TipTac' (a nil value)"
layout_presets = <table> {
 TipBuddy = <table> {
 }
 TipTac New Style = <table> {
 }
 TipTac Old Style = <table> {
 }
 Blizzard = <table> {
 }
 Solid Border = <table> {
 }
 TinyTip = <table> {
 }
}
cfg = <table> {
 classification_rare = "Level %s|cffff66ff Rare"
 classification_elite = "Level %s|cffffcc00 Elite"
 optionsBottom = 413
 tipBackdropEdge = "Interface\Tooltips\UI-Tooltip-Border"
 optionsLeft = 458.499908
 backdropEdgeSize = 16
 classification_trivial = "Level ~%s"
 showTarget = "last"
 backdropInsets = 4
 tipBackdropBG = "Interface\Tooltips\UI-Tooltip-Background"
 reactColoredBackdrop = true
 tipColor = <table> {
 }
 colorRace = <table> {
 }
 healthBar = false
 classification_rareelite = "Level %s|cffffaaff Rare Elite"
 classification_normal = "Level %s"
 tipBorderColor = <table> {
 }
 targetYouText = "<<YOU>>"
 powerBar = false
 top = 276.000031
 classification_worldboss = "Level %s|cffff0000 Boss"
 hideDefaultBar = false
 manaBar = false
 classification_minus = "Level -%s"
 left = 1356.000244
 colorLevel = <table> {
 }
 showTip = false
}

I switched back to the old version for the time being.
Thanks for your help.
Great work on the addon. :-)

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

I haven't stumbled across this yet, because I rarely select a layout. 🙂 

Will be fixed with the next release.
