### ISSUE TITLE
Missing Kalu'ak Whalebone Glider in Mount ID tooltips

### ISSUE THREAD

**Issue by Jeremy7600** [frozn/TipTac#208]
**Describe the bug**
This item is not presented in the Mount ID Tooltip feature:
https://www.wowhead.com/wotlk/item=192455/kaluak-whalebone-glider

**To Reproduce**
1. Find someone riding the Whalebone Glider
2. Hover over that player's nameplate or target frame
3. No mount is shown

**Expected behavior**
Should display "Kalu'ak Whalebone Glider (100%)" when a player is riding one

**Screenshots**
Globz riding Kalu'ak Bonewhale Glider, no mount presented in tooltip
![WoWScrnShot_021923_131742](https://user-images.githubusercontent.com/62718826/219970239-2764e8cc-62ea-4731-9812-9e53f7f93a98.jpg)

Tooltip on Globz mount icon
![WoWScrnShot_021923_131747](https://user-images.githubusercontent.com/62718826/219970262-0fb81da4-a617-4c48-9982-694f20ff7c59.jpg)

**TipTac Reborn (please complete the following information):**
 - Version 23.02.18

**WoW (please complete the following information):**
 - Flavor: WotLKC
 - Version 3.4.1

**Comment by Jeremy7600** [comment]
Same for Reawakened Phase Hunter
![WoWScrnShot_021923_164227](https://user-images.githubusercontent.com/62718826/219979753-a3b57ef7-07dc-4ee6-840b-5ca893bb9f56.jpg)
https://www.wowhead.com/tbc/item=184865/reawakened-phase-hunter

I'm guessing there might be another couple

Also, mount speed for these items is dependent on the riders skill. I'd at least like to see the mount, I don't have to see the mount speed since I already have the speed of the target shown (me personally).

**Comment by frozn** [comment]
The function `C_MountJournal.GetMountFromSpell()` isn't available in classic. As a fallback I created a plain table by outputting all spells by iterating through `C_MountJournal.GetMountIDs()` and calling the mentioned function.

Unfortunately some spell IDs of mounts aren't available in retail any more but exist in classic. To solve this I will add the missing spell IDs manually.

**Comment by frozn** [comment]
I finally added the missing spell IDs. Will be included with the next release. 👍
