### ISSUE TITLE
[Feature request] Adding some anchor point for icons

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#21]
Now some points of tooltip cannot be anchored by tiptac option. I marked with circle in next SC
https://imgur.com/a/4ItCYfl

I think it's good to add x,y offset or relative anchor points into option.

**Comment by frozn** [comment]
@NoBetaBoredom has made a pull request to add this feature. It's already merged to the main branch. What do you think?

**Comment by hobulian** [comment]
Think it's working really nice. Can you do same things for raid icon/faction/combat/class icons?

**Comment by hobulian** [comment]
This is not about icons but in my client,
When backdrop border size is "1" then some times some borders seems to have value of "0" by relative points of screen.
https://imgur.com/a/c90WFHJ

After setted border size "1.5" this stopped happening.

**Comment by NoBetaBoredom** [comment]
> Think it's working really nice. Can you do same things for raid icon/faction/combat/class icons?

I will check tomorrow, should be doable.

> This is not about icon anchors but in my client, When backdrop border size is "1" then some times some borders seems to have value of "0" by relative points of screen. https://imgur.com/a/c90WFHJ
> 
> After setted border size "1.5" this stopped happening.

Borders are currently broken, I have already made a PR that makes the borders perfect (as far as I tested it). Hopefully @frozn will merge it!

**Comment by frozn** [comment]
For adding some anchor points for raid/faction/combat/class icons I created a new issue: #50 

For the border issues, @NoBetaBoredom already created the PR #47 and #48. I really appreciate your input here! 👍
