### ISSUE TITLE
Option to hide (or re-anchor) tooltips during Dragonriding races

### ISSUE THREAD

**Issue by tflo** [frozn/TipTac#212]
My tooltips are mouse-anchored and have a fade-out delay. I have found that this can be a problem during dragon racing when a (huge) tooltip pops up and blocks your view. This is not a problem during normal flying, but in a race it can cost you precious seconds if you miss a circle or a Vigor bubble, or fail to dodge an obstacle.

So it would be great to have the option to either hide tooltips, or to re-anchor tooltips to their default non-mouse position, during a race. (Similar to the already existing combat checks.)

I don't know if there is an easy/elegant way to detect if we are in a Dragonriding race, but I guess there isn't. I haven't even found an API for "is dragonriding". WeakAuras, for their "Dragonriding" load condition, is using a combination of `IsMounted()` and aura detection for one of `C_MountJournal.GetCollectedDragonridingMounts()`. But I think this is too complex for tooltip checks.

So, probably, the most economic and elegant way would be a combination of `IsFlying()` and `IsAdvancedFlyableArea()`. Obviously this will also apply to non-race dragonflying, but I think this is acceptable.

Thanks for considering,

– Tom

**Comment by frozn** [comment]
I finally have had enough time to play DF for myself (and not only when developing this addon) and implemented this useful feature request. Better late than never. 🙂👍

Under "Anchors" I added options to override the anchor for world/frame units/tips during dragonriding. Under "Combat" I added options to hide frame/world unit tips or unit/spell/item/action bar tips during dragonriding.

This feature is included in the latest release [v24.03.23](https://github.com/frozn/TipTac/releases/tag/v24.03.23-release).

**Comment by frozn** [comment]
For interest, to determine if the player is currently dragonriding I check if the dragonriding action bar is visible like in blizzards `Blizzard_Tutorials_Dragonriding.lua`:

![image](https://github.com/frozn/TipTac/assets/5655881/51fd9e8a-66a0-4362-9484-485650155685)

**Comment by tflo** [comment]
> Better late than never. 🙂👍

Nah, if the average human lifespan was one hour, then barely a minute has passed since my post 😊

But no worries, in the meantime I made my own mod that hides certain UI elements, moves and scales the EncounterBar, **hides all tooltips,** and some other optimizations during a dragonride race.

Nonetheless, having a hide or reanchor option when dragonriding in TipTac is a welcome and useful addition, thank you!

>  I check if the dragonriding action bar is visible

Good idea!
