### ISSUE TITLE
LibFroznFunctions-1.0.lua:315: attempt to index global 'LFF_SPELLID_TO_MOUNTID_LOOKUP' (a nil value)

### ISSUE THREAD

**Issue by tlundse** [frozn/TipTac#215]
8x ...libs/LibFroznFunctions-1.0-7/LibFroznFunctions-1.0.lua:315: attempt to index global 'LFF_SPELLID_TO_MOUNTID_LOOKUP' (a nil value)
[string "@TipTacItemRef/libs/LibFroznFunctions-1.0-7/LibFroznFunctions-1.0.lua"]:315: in function `GetMountFromSpell'
[string "@TipTacItemRef/ttItemRef.lua"]:2332: in function `spell'
[string "@TipTacItemRef/ttItemRef.lua"]:1078: in function <TipTacItemRef/ttItemRef.lua:1069>
[string "@TipTacItemRef/libs/LibFroznFunctions-1.0-7/LibFroznFunctions-1.0.lua"]:271: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:269>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetAction'
[string "@FrameXML/ActionButton.lua"]:906: in function `SetTooltip'
[string "@FrameXML/ActionButton.lua"]:1185: in function <FrameXML/ActionButton.lua:1180>
[string "=[C]"]: ?

Locals:
self = <table> {
 CreatePushArray = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:628
 MixinDifferingObjects = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:763
 FormatText = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:420
 GetDifficultyColorForQuest = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1070
 GetItemQualityColor = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1036
 RegisterNewSlashCommands = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:896
 IsTableEmpty = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:444
 CreateMarkupForClassIcon = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1114
 GetDifficultyColorForUnit = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1044
 UpdateUnitRecord = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1848
 ExistsInTable = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:637
 HookSecureFuncIfExists = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:794
 UnitIsBattlePetCompanion = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:126
 CallFunctionDelayed = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:781
 ChainTables = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:509
 MixinMissingObjects = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:744
 HookScriptOnTooltipSetSpell = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:266
 HookScriptOnTooltipSetUnit = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:189
 GetItemFromTooltip = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:209
 CreateMarkupForRoleIcon = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1098
 removeAllFromTable = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:488
 RegisterTableVersion = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:36
 GetUnitFromTooltip = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:175
 GetMountFromTooltip = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:286
 FireGroupEvent = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:854
 GetClassColor = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:984
 MirrorAnchorPointCentered = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1188
 GetAverageItemLevel = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2498
 FontExists = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1529
 TableRegistry = <table> {
 }
 IsMountCollected = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:342
 UnitIsWildBattlePet = <function> defined @TipTacItemRef/libs/LibFroznFunctions-1.0/LibFroznFunct

**Comment by frozn** [comment]
Hm, haven't seen this on my side so far... 🤔
