### ISSUE TITLE
"PetActionID" lua error

### ISSUE THREAD

**Issue by kwonjt2001** [frozn/TipTac#216]
**To Reproduce**
Using pet action id show and hovering over a special action ability spell in a summons spellbook causes a lua error.

![error2](https://user-images.githubusercontent.com/98691652/223931697-17cedfb7-0432-41a5-a808-398d892d31c2.jpg)

TipTac-v23.03.07-release

**Comment by frozn** [comment]
Unfortunately I can't reproduce this. I think another addon is responsible for this. Can you disable your other addons one by one and find out the corresponding addon?

**Comment by kwonjt2001** [comment]
It happens even if I turn off all addons and only turn on TipTac and BugSack.
Activate "Show Pet Action ID" and only occurs on special ability spells.

**Comment by frozn** [comment]
I has been able to reproduce it. I haven't enabled "Show Pet Action ID"... 🙈

**Comment by frozn** [comment]
I fixed it. Will be included in the next release. 👍

**Comment by kwonjt2001** [comment]
> 
You are amazing. Thank you always!
