### ISSUE TITLE
Quality border for SetCollectionFrame

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#22]
Wardrobe collection frame tooltip now shows quality frame but not on set collection frame yet. Maybe good to add this functional.
https://imgur.com/a/Er0ALcf

**Comment by frozn** [comment]
3h lifetime invested and then there are beautiful border colors for set items in wardrobe... :upside_down_face:

:arrow_right: Committed to main-branch

**Comment by hobulian** [comment]
> 3h lifetime invested and then there are beautiful border colors for set items in wardrobe... 🙃
> 
> ➡️ Committed to main-branch

I've checked and it's working.
I will buy some coffee of beer for ya if you have donation link maybe.

**Comment by frozn** [comment]
Thank you for looking over and verifying! :smile::thumbsup:

In fact, I was finished here much earlier by hooking WardrobeSetsDetailsItemMixin:OnEnter(), but then I saw the "special feature" that you can press TAB to cycle through the items with the same visualID. After pressing TAB, the border color and itemID disappeared. :scream:

Then the journey began and I found out that function WardrobeSetsCollectionMixin:RefreshAppearanceTooltip() works for both scenarios, OnEnter for button and TAB for cycling. :hot_face:

**Comment by hobulian** [comment]
> Then the journey began and I found out that function WardrobeSetsCollectionMixin:RefreshAppearanceTooltip() works for both scenarios, OnEnter for button and TAB for cycling. 🥵

I found out that it only works in SetCollectionFrame with tab.. But not in ItemsCollectionFrame yet.
https://imgur.com/a/b55yN5f

**Comment by frozn** [comment]
Fixed 👍

**Comment by hobulian** [comment]
> Fixed 👍

Checked it fixed now :)
