### ISSUE TITLE
Expansion Icon/Text

### ISSUE THREAD

**Issue by SisrenWarrior** [frozn/TipTac#223]
Apologies for posting as an issue, but Curse comments are disabled.
First off, love the expansion icon feature! But wanted to note that Anything from Vanilla/BC/Wrath is being labeled as simply Classic, even on retail. Wasn't sure if that was intentional or not.
If so, disregard and again, apologies.

**Comment by frozn** [comment]
I've noticed some curious things here, too, but I only output the return value no. 15 (expacID - expansion id, available since expansion legion) from api function [GetItemInfo()](https://wowpedia.fandom.com/wiki/API_GetItemInfo) which comes directly from WoW.

**Comment by SisrenWarrior** [comment]
Very clearly something shared between retail and classic, given which expansions are affected. Odd that they have any kind of shared info though, what with retail having the stat squish and various other changes to the foundations. Though I suppose the squish is simply an algorithm and not an actual change to the items, and that's what allows timewalking gear to shift accordingly.
Aaaanyway, thanks for the response! It's still an awesome feature. Makes identifying things that much easier.

**Comment by frozn** [comment]
Glad to hear this! 😉
