### ISSUE TITLE
Feature suggestion: option to move player realm to another line to reduce tooltip length

### ISSUE THREAD

**Issue by Rezy942** [frozn/TipTac#224]
As title says, I would love this option...
I am constantly fighting with super long tooltips.
I want to see player realm, but same time some realms are just huge in letter count!
See example:
![image](https://user-images.githubusercontent.com/122007087/236580567-6d94df80-dab6-499b-a028-76e8e518612f.png)

It would be fanastic if we could move it to next line :)
Pretty please!!
Another option is reducing server names to first few letters - but i dont like when addons do this - most server names get very confusing and too hard to guess what they are.

Lastly, thank you for maintaing this amazing addon for so long!!

**Comment by frozn** [comment]
Good idea! 👍

The new option "Show realm in new line" under "General->Show Unit Realm" will be included in the next release. 🙂

**Comment by Rezy942** [comment]
I gotta say you are amazing at incorporating user feedback, + the addon is near flawless compared to almost any other addon out there.
They are all plagued with bugs that dev's usually dont want to fix, while tiptac ive never had any real issues with

Thank you for your work :)
