### ISSUE TITLE
LUA error on WotLKC PTR 3.4.2

### ISSUE THREAD

**Issue by sausje** [frozn/TipTac#228]
Following LUA error on PTR
```

6x TipTacItemRef/ttItemRef.lua:1729: hooksecurefunc(): EmbeddedItemTooltip_SetSpellByQuestReward is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@TipTacItemRef/ttItemRef.lua"]:1729: in function `ApplyHooksToTips'
[string "@TipTacItemRef/ttItemRef.lua"]:1835: in function `HookTips'
[string "@TipTacItemRef/ttItemRef.lua"]:389: in function `?'
[string "@TipTacItemRef/ttItemRef.lua"]:340: in function <TipTacItemRef/ttItemRef.lua:340>

Locals:

```

**TipTac Reborn (please complete the following information):**
 - Version 23.05.01

**WoW (please complete the following information):**
 - Flavor: wrath PTR
 - Version 3.4.2

**Additional context**
It's PTR so obviously bugs are to be expected. I've copied over my wtf from live, so idk if that causes it.

**Comment by frozn** [comment]
Confirmed, thanks for reporting this! 👍

Strange that only function `EmbeddedItemTooltip_SetSpellByQuestReward()` is missing in the `GameTooltip.lua`. I suspect, that it's a bug on blizzards side on PTR 3.4.2.

Let's see if this function will really be removed when 3.4.2 is officially released.

**Comment by frozn** [comment]
I added a workaround for WotLKC PTR 3.4.2 to fix this lua error. Will be included in the next release.

This issue will stay open until 3.4.2 arrived.

**Comment by frozn** [comment]
Strange... with the release of WotLKC 3.4.2 the function `EmbeddedItemTooltip_SetSpellByQuestReward()` is still missing, but it  existed in 3.4.1 and 10.1.0. 🤔

Nevertheless the check for existance of the mentioned function I included in the last release stays in place.
