### ISSUE TITLE
Hostile target Tooltip fadeout issue

### ISSUE THREAD

**Issue by itsSinba** [frozn/TipTac#229]
**Describe the bug**
The fade out settings do not work when targeting a hostile NPC. It takes about 3 seconds for the fade out to occur, regardless of the parameters in the Fadeout Time settings.

There's this "newish" tooltip behavior in the game client with targeting hostile NPC. It shows the tooltip right when targeting a hostile npc through, without hovering the cursor over it. This is where this "issue" comes from. A hostile NPC seems to have its own/new fadeout function. It'll probably need Tiptac to add it, as the Fadeout time settings do not overwrite it at the moment.

I haven't looked into it but I can probably help if you need it

**To Reproduce**
1. Enable Override Default GameTooltip fade for Units
2. Set Fade out to default 0.1 or 0.05
3. Target a hostile NPC by tabbing or clicking
4. Move cursor away and watch the fade out time

**Expected behavior**
The fadeout time should be of 0.1 or 0.05, depending on the settings set

**TipTac Reborn (please complete the following information):**
v23.05.01-release

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.1.0

**Comment by frozn** [comment]
Unfortunately I can't reproduce this on my side. I activated the automatic targetting of enemies in sight but there doesn't pop up a tooltip if the game autotargets a hostile NPC. The tooltip only appears if I hover over the unit or unitframe with correct fading times.

Am I missing a interface setting or somehting else?

**Comment by frozn** [comment]
I finally has been able to reproduce this. If this accessibility feature is enabled, the function `GameTooltip:FadeOut()` won't be triggered when the fading of the tooltip begins. I wasn't been able to find out the corresponding function to listen to yet.

**Comment by itsSinba** [comment]
Interesting. I think that it shares the same function as tooltips of braziers/fires. Mouse over a fire will have the same 3-second-ish fadeout time. I'll see if I can help find it

**Comment by frozn** [comment]
I further analyzed the OnShow, OnTooltipCleared and OnHide event for this accessibility feature. Indeed there's no function to hook to override the fading times. It seems that it's an internal GameTooltip thing.

Regarding the fire: In this case the function `GameTooltip:FadeOut()` will be called. Hooking this function for non-unit tooltips has been missing in TipTac. This will be included in the next release.
