### ISSUE TITLE
Tooltip for Plater aura frames

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#23]
Now tiptac seems not supporting plater nameplates aura tooltip. I tried to apply your WorldquestTracker tooltip hook but keep failing. It's frame is like this now.
https://imgur.com/a/ORyZMKq

You can test aura tooltip by enter "/plater" in chat and check [show tooltip] in at BUFF SETTINGS
https://imgur.com/a/xu80ALs

It's tooltip lua is at
https://github.com/Tercioo/Plater-Nameplates/blob/master/Plater_Auras.lua

**Comment by frozn** [comment]
I added the styling of auras from standard nameplate and addon Plater and committed my changes to main-branch.

**Comment by frozn** [comment]
Added additional changes due to regression. Now all seems fine.

**Comment by hobulian** [comment]
It seems fine to me. :)
