### ISSUE TITLE
Incorrect usage of GetItemInfo in QuestReward

### ISSUE THREAD

**Issue by tlundse** [frozn/TipTac#234]
When mousing over the reward on some quests, I get the following lua error:

```
TipTacItemRef/ttItemRef.lua:855: Usage: GetItemInfo(itemID|"name"|"itemlink")

Locals:
(*temporary) = nil

```

I am running TipTac 23.05.20 on retal wow 10.1.0

This isn't a new issue, its been like this for a while, but I have been to lazy to report it. :(

Using /fstack I found out that the frame MapQuestInfoRewardsFrameQuestInfoItem1 is the one that causes the error (or, at least one of them)

**Comment by tlundse** [comment]
soooo.. I was checking every single tiptac setting, tweaking stuff, and now I can't reproduce this issue any more. It wasn't a one-time thing, I've had it for several months, but now it's gone... I have no idea what setting might have caused this.

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

I added respective checks before calling `GetItemInfo()` to make shure that there's a valid item id/link/name. Will be included in the next release.
