### ISSUE TITLE
GetRewardLevelForDifficultyLevel on "Mythic Keystone" link in chat

### ISSUE THREAD

**Issue by tlundse** [frozn/TipTac#236]
While mousing over a "Mythic Keystone" link in chat, I got the following error:

3x TipTacItemRef/ttItemRef.lua:2358: bad argument #1 to 'GetRewardLevelForDifficultyLevel' (outside of expected range -2147483648 to 2147483647 - Usage: local weeklyRewardLevel, endOfRunRewardLevel = C_MythicPlus.GetRewardLevelForDifficultyLevel(difficultyLevel))

Locals:
(*temporary) = ""
(*temporary) = "outside of expected range -2147483648 to 2147483647 - Usage: local weeklyRewardLevel, endOfRunRewardLevel = C_MythicPlus.GetRewardLevelForDifficultyLevel(difficultyLevel)"

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

I added a check that the keystone level is a valid number. I think it probably comes from a corrupt chatlink. The fix will be included in the next release.
