### ISSUE TITLE
Several LUA Errors in case with new AFFIX ? Afflicted 

### ISSUE THREAD

**Issue by Vilogity** [frozn/TipTac#238]
Get this Errors when i dispel the ADDS and tanke them in target ?
TipTac Version 23.05.20 

6x TipTac/ttCore.lua:1530: calling 'GetScale' on bad self (Usage: local frameScale = self:GetScale())
[string "=[C]"]: in function `GetScale'
[string "@TipTac/ttCore.lua"]:1530: in function `SetScaleToTip'
[string "@TipTac/ttCore.lua"]:1650: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-10/LibFroznFunctions-1.0.lua"]:885: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1472: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1336: in function <TipTac/ttCore.lua:1335>
[string "=[C]"]: in function `Show'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:391: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `setFunction'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:860: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:853>

Locals:
Skipped (In Encounter)

Then:
3x TipTac/ttCore.lua:1375: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@TipTac/ttCore.lua"]:1375: in function <TipTac/ttCore.lua:1374>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetOwner'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:854: in function `UpdateTooltip'
[string "*Blizzard_NamePlates.xml:351_OnUpdate"]:8: in function <[string "*Blizzard_NamePlates.xml:351_OnUpdate"]:1>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
Skipped (In Encounter)
This:
3x TipTacItemRef/ttItemRef.lua:2487: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `AddLine'
[string "@TipTacItemRef/ttItemRef.lua"]:2487: in function `spell'
[string "@TipTacItemRef/ttItemRef.lua"]:631: in function <TipTacItemRef/ttItemRef.lua:619>
[string "=[C]"]: ?
[string "=[C]"]: in function `setFunction'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:860: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:853>

Locals:
Skipped (In Encounter)

**Comment by hollo6** [comment]
I get the following randomly in keys:

34x TipTac/ttCore.lua:2403: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@TipTac/ttCore.lua"]:2403: in function `ResetCurrentDisplayParamsForAnchoring'
[string "@TipTac/ttCore.lua"]:2441: in function <TipTac/ttCore.lua:2440>
[string "=[C]"]: in function `SetOwner'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:63: in function `SetTooltipOwner'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:69: in function `OnEnter'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:622: in function <...Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:621>

Locals:
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = EmbeddedItemTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @FrameXML/GameTooltip.lua:1108
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.l



And after that, when trying to mouseover a broker addon:
65x TipTac/ttCore.lua:1530: calling 'GetScale' on bad self (Usage: local frameScale = self:GetScale())
[string "=[C]"]: in function `GetScale'
[string "@TipTac/ttCore.lua"]:1530: in function `SetScaleToTip'
[string "@TipTac/ttCore.lua"]:1650: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-10/LibFroznFunctions-1.0.lua"]:885: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1472: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1336: in function <TipTac/ttCore.lua:1335>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:102: in function `OnEnter'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:622: in function <...Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:621>

Locals:
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = EmbeddedItemTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @FrameXML/GameTooltip.lua:1108
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.l

**Comment by hollo6** [comment]
This still exists :(

**Comment by frozn** [comment]
Is there an easy way to reproduce this outside of a dungeon?

**Comment by glassleo** [comment]
No, it only happens with the Afflicted mobs. Maybe TipTac can disable their tooltips if the mob is NPC ID ``204773``?

**Comment by Vilogity** [comment]
Yes is there and it's mostly in Dungeons with Afflicted MOBS.
They must be dispelled and when you take them in Target then this error is there.

**Comment by Vilogity** [comment]
New information
Last fight i was dead and had time to test what it is in M+
It's not targeting the add, it is the debuff (desease) you see over the cast line from this affix adds.
When I go with the mouse over this, i get the error.......

**Comment by hollo6** [comment]
Still happening :( any chance of a workaround?

**Comment by hollo6** [comment]
Still happening.
Also breaks every broker after this pops up, with this LUA error:

71x TipTac/ttCore.lua:1565: calling 'GetScale' on bad self (Usage: local frameScale = self:GetScale())
[string "=[C]"]: in function `GetScale'
[string "@TipTac/ttCore.lua"]:1565: in function `SetScaleToTip'
[string "@TipTac/ttCore.lua"]:1685: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:889: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1507: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1359: in function <TipTac/ttCore.lua:1358>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:102: in function `OnEnter'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:622: in function <...Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:621>

Locals:
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = EmbeddedItemTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @FrameXML/GameTooltip.lua:1108
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.l

**Comment by hollo6** [comment]
Could we please have at least a workaround for this, something like the one suggested above?

**Comment by frozn** [comment]
From: [BNS333](https://legacy.curseforge.com/wow/addons/tiptac-reborn?comment=396)

This error often occurs in the Retail, appears in the mythic+ combat.

After that, there will be a few Tiptac errors, but it may be affected by this.

```
1x SharedXML/Backdrop.lua:215: calling 'GetWidth' on bad self (Usage: local width = self:GetWidth([ignoreRect]))

[string "=[C]"]: in function `GetWidth'
[string "@SharedXML/Backdrop.lua"]:215: in function `SetupTextureCoordinates'
[string "@SharedXML/Backdrop.lua"]:184: in function <SharedXML/Backdrop.lua:182>
[string "=[C]"]: in function `Show'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:391: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `setFunction'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:886: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:879>

Locals:

(*temporary) = NamePlateTooltip {
0 = <userdata>
GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
SetHyperlink = <function> defined =[C]:-1
SetAzeriteEssence = <function> defined =[C]:-1
SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
ClearBackdrop = <function> defined =[C]:-1
SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetRecipeReagentItem = <function> defined =[C]:-1
SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
BottomOverlay = Texture {
}
SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
NineSlice = Frame {
}
SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
TopEdge = Texture {
}
SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
SetBackdropColor = <function> defined =[C]:-1
LeftEdge = Texture {
}
AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
SetSpellBookItem = <function> defined =[C]:-1
textLeft1Font = "GameTooltipHeaderText"
AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
textRight2Font = "GameTooltipText"
TopOverlay = Texture {
}
SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetUnitDebuff = <function> defined =[C]:-1
SetMountBySpellID = <function> defined =[C]:-1
SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
SetToyByItemID = <function> defined =[C]:-1
TextLeft1 = NamePlateTooltipTextLeft1 {
}
GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
StatusBar = NamePlateTooltipStatusBar {
}
SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetUnitAura = <function> defined =[C]:-1
SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
SetConduit = <function> defined =[C]:-1
SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
GetItem = <function> defined @FrameXML/GameTooltip.lua:1108
SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetQuestPartyProgress = <function> defined =[C]:-1
ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
```

**Comment by glassleo** [comment]
Can we please prioritze this a bit more? Makes the addon unusable during certain weeks.

**Comment by frozn** [comment]
I've been playing WoW the last year only if I have to develop something for TipTac, e.g. new features, fixes or fixes regarding WoW patches. Yesterday I setup my addons/talents and started with actual playing again.

I analyzed this specific error a few times ago, but I can't see any obvious with the coding here. To analyze it further, I have to debug this for myself, and that's only possible if I e.g. go in mythic dungeons. But my main char is currently at lvl 62, so I firstly have to level him up. 🙈

But I'm on it...

**Comment by glassleo** [comment]
Sorry if I sounded harsh, I just love the addon and I'm sad when it breaks. <3

**Comment by glassleo** [comment]
Sorry if I sounded harsh, I just love the addon and I'm sad when it breaks. I really appreciate your efforts. <3

> I analyzed this specific error several times, but I can't see any obvious error with the coding here. To analyze it further, I have to debug this for myself, and that's only possible if I e.g. go in mythic dungeons. But my main char is currently at lvl 62, so I firstly have to level him up. 🙈

I think what is going wrong is that those particular nameplates are completely protected and cannot be modified by addons in any way and since TipTac tries to attach a tooltip to them it throws protected errors at us.

I think there needs to be some kind of check to see if the frame is protected or not and then just cancel trying to attach/modify the tooltip attached to it. The NPC ID is ``204773`` but I'm not sure if that helps.

It will be 6 weeks until the affix is back again (it's up for two out of ten weeks in a set rotation of affixes) and you have to be in a +7 or higher key to see it. If you are on EU I would be happy to provide you with a key for testing next time it's up as long as you have a level 70 character by then.

**Comment by Dairyman** [comment]
So I don't now why I didn't see earlier that it only happens with the `NamePlateTooltip`; so fix fix for it is to not modify the `NamePlateTooltip`:
```diff
diff --git a/TipTac/ttCore.lua b/TipTac/ttCore.lua
index f2feeb1..f5c636e 100755
--- a/TipTac/ttCore.lua
+++ b/TipTac/ttCore.lua
@@ -418,7 +418,7 @@ TT_ExtendedConfig.tipsToModify = {
 				end
 			},
 			["EmbeddedItemTooltip"] = { applyAppearance = true, applyScaling = true, applyAnchor = true },
-			["NamePlateTooltip"] = { applyAppearance = true, applyScaling = true, applyAnchor = true },
+			-- ["NamePlateTooltip"] = { applyAppearance = true, applyScaling = true, applyAnchor = true },
 			["BattlePetTooltip"] = { applyAppearance = true, applyScaling = true, applyAnchor = true },
 			["FloatingBattlePetTooltip"] = { applyAppearance = true, applyScaling = true, applyAnchor = true },
 			["Flo
```
```diff
diff --git a/TipTacItemRef/ttItemRef.lua b/TipTacItemRef/ttItemRef.lua
index b6068e9..42fe87a 100644
--- a/TipTacItemRef/ttItemRef.lua
+++ b/TipTacItemRef/ttItemRef.lua
@@ -142,7 +142,7 @@ local tipsToModify = {
 	"ItemRefShoppingTooltip1",
 	"ItemRefShoppingTooltip2",
 	"EmbeddedItemTooltip",
-	"NamePlateTooltip",
+	-- "NamePlateTooltip",
 	"BattlePetTooltip",
 	"PetBattlePrimaryUnitTooltip",
 	"FloatingBattlePetTooltip",
```

Question now is how easy it is to add a check if a Tooltip is [Protected](https://warcraft.wiki.gg/wiki/API_ScriptRegion_IsProtected) or [Forbidden](https://warcraft.wiki.gg/wiki/API_FrameScriptObject_IsForbidden) and not to modify.

**Comment by hollo6** [comment]
This is still happening and the above change didn't fix it for me, in fact made it worse by causing several other addons having a lot of other LUA errors.

**Comment by hollo6** [comment]
Still happening 50 times every dungeon :(

**Comment by frozn** [comment]
I added several `IsForbidden()` checks in the last versions and the error messages I encounter on name plates during LFR raids are now gone. Can you post the latest error message here for further investigation? Thanks!

**Comment by hollo6** [comment]
12733x bad argument #1 to '?' (Usage: self:SetEdgeTexture(texture [, color]))
[string "=[C]"]: in function `SetEdgeTexture'
[string "@HideActionbarAnimations/HideActionbarAnimations.lua"]:23: in function <.../HideActionbarAnimations/HideActionbarAnimations.lua:22>
[string "=[C]"]: in function `CooldownFrame_Set'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:812: in function `callback'
[string "@SharedXML/TableUtil.lua"]:619: in function `Iterate'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:798: in function `UpdateBuffs'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:250: in function `OnUnitAuraUpdate'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:145: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: self:SetEdgeTexture(texture [, color]))"
