### ISSUE TITLE
Item tooltip border overlapped by elv-UI's default black tooltip border

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#24]
After applying recent update, this problem started to happen. Before, It was fine.

But now, Tiptac's function seems to be shown with elv-ui's default skinning function(not it's tooltip skinning function since i disable all of it's tooltip skinning function, So when you are just using elvui, even not using it's tooltip function this happens) at the same time. So you can see that in screen shot below, Elv-ui's black border and it's own half-transparent black backdrop color overlapping with those of tiptac's.
https://imgur.com/a/j3ECLCe

I checked every quality coloring border funcitons in tooltip. But this only happened with "item" tooltip border.

**Comment by hobulian** [comment]
found out that when i moved  

-- Quality Border
if (cfg.if_itemQualityBorder) then
	local itemQualityColor = CreateColorFromHexString(select(4, GetItemQualityColor(itemRarity or 0)));
	ttif:SetBackdropBorderColorLocked(self, true, itemQualityColor:GetRGBA());
end

to the end of 
LinkTypeFuncs:item(link,linkType,id) it's working fine

**Comment by frozn** [comment]
Fixed it in main-branch. This was a little bit tricky. 😎

**Comment by hobulian** [comment]
> Fixed it in main-branch. This was a little bit tricky. 😎

This dev totally disabling elv ui's default skinning functions.. that's another problem..

**Comment by hobulian** [comment]
12x ElvUI\Core\General\Toolkit.lua:207: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@ElvUI\Core\General\Toolkit.lua"]:207: in function `SetTemplate'
[string "@ElvUI\Core\Modules\Tooltip\Tooltip.lua"]:753: in function `SetStyle'
[string "@ElvUI\Mainline\Modules\Skins\PetBattle.lua"]:233: in function <...ceElvUI\Mainline\Modules\Skins\PetBattle.lua:40>
[string "=[C]"]: ?
[string "@ElvUI\Core\Modules\Skins\Skins.lua"]:1595: in function <ElvUI\Core\Modules\Skins\Skins.lua:1590>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@ElvUI\Core\General\Core.lua"]:1741: in function `CallLoadFunc'
[string "@ElvUI\Core\General\Core.lua"]:1756: in function `CallLoadedModule'
[string "@ElvUI\Core\General\Core.lua"]:1782: in function `InitializeModules'
[string "@ElvUI\Core\General\Core.lua"]:1891: in function <ElvUI\Core\General\Core.lua:1860>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI\Core\init.lua"]:208: in function <ElvUI\Core\init.lua:207>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by frozn** [comment]
Oh, I hadn't noticed that. 😱 I'll take a look at it tonight...

**Comment by frozn** [comment]
Fixed it. I hope, everything's fine now. :sweat:

**Comment by hobulian** [comment]
No errors now. It's working fine! :) Thanks

**Comment by frozn** [comment]
That are good news. 😉
