### ISSUE TITLE
Error due to Profession Master

### ISSUE THREAD

**Issue by darvoso** [frozn/TipTac#242]
Receiving below error (from swatter) when I login with new version (23.06.20).  Similar to #222, issue goes away if I disable ProfessionMaster, presumably leaking globals still.  Did a compare on the two versions, didn't see anything obvious to me to try and resolve, thought I'd ask.

```Date: 2023-06-20 21:30:41
ID: 2
Error occured in: Global
Count: 1
Message: Interface/AddOns/TipTac/ttCore.lua line 828:
   attempt to call method 'SetupConfig' (a nil value)
Debug:
   [string "=[C]"]: SetupConfig()
   [string "@Interface/AddOns/TipTac/ttCore.lua"]:828: ?()
   [string "@Interface/AddOns/TipTac/ttCore.lua"]:853:
      Interface/AddOns/TipTac/ttCore.lua:852
Locals:
(*temporary) = <function> defined =[C]:-1```

**Comment by frozn** [comment]
I also took a look into it and came to the following conclusion regarding ProfessionMaster:

![66851707](https://github.com/frozn/TipTac/assets/5655881/8c5e6ec4-bb0e-46d6-a281-55963024022c)

😄

Leaking global `Settings` in PM smashes WotLKC completely, because the new interface settings has been roled out with the new version 3.4.2.

> EDIT: Nothing can be done. Profession Master needs to stop doing what it's doing. Until then, users should uninstall Profession Master and switch to alternatives.

Indeed

**Comment by darvoso** [comment]
Well, apparently! It got resolved.  https://www.curseforge.com/wow/addons/profession-master/files/4601211 -> Notes: 1.6.4
Fixed global settings issue. Many thanks to @Ulidan
And now when I fire up the ol PM with tiptac and such, nothing splodes.  Thank you both for taking a look - i didn't realize there was a discord posted on the PM list to reach out to that dev.
