### ISSUE TITLE
Lua error when mouse on other players

### ISSUE THREAD

**Issue by helicdark** [frozn/TipTac#243]
152x ...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:277: attempt to call global 'CompactRaidFrameManager_UpdateShown' (a nil value)
[string "@FrameXML/SettingDefinitions/InterfaceOverrides.lua"]:277: in function <...e/FrameXML/SettingDefinitions/InterfaceOverrides.lua:274>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@SharedXML/CvarUtil.lua"]:114: in function <SharedXML/CvarUtil.lua:106>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@SharedXML/ClassicCvarUtil.lua"]:7: in function <SharedXML/ClassicCvarUtil.lua:3>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@TipTac/libs/LibFroznFunctions-1.0-11/LibFroznFunctions-1.0.lua"]:725: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:716>
[string "=(tail call)"]: ?
[string "@TipTac/libs/LibFroznFunctions-1.0-11/LibFroznFunctions-1.0.lua"]:2367: in function `InitiateInspectRequest'
[string "@TipTac/libs/LibFroznFunctions-1.0-11/LibFroznFunctions-1.0.lua"]:2270: in function `InspectUnit'
[string "@TipTacTalents/ttTalents.lua"]:143: in function <TipTacTalents/ttTalents.lua:112>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
compactFrames = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'CompactRaidFrameManager_UpdateShown' (a nil value)"

**TipTac Reborn :**
 - Version 23.06.20
**WoW :**
 - Flavor: WotLKC
 - Version 3.4.2

**Additional context**
it's kinda strange that not all of my characters are popping up this lua error (pally and warlock bugged, but priest not), and i guess tiptac doesn't support individual character settings?

**Comment by helicdark** [comment]
a setting error, not bug

**Comment by frozn** [comment]
I'm curious. What setting triggered this error?

**Comment by helicdark** [comment]
> I'm curious. What setting triggered this error?

Blizzard_CompactRaidFrames is somehow disabled in AddOns.txt. I corrected it to enable then the error no longer pops up.

**Comment by frozn** [comment]
Interesting. If I manually disable addon `Blizzard_CompactRaidFrames` in `AddOns.txt`, it will be auto-enabled if I log in with one of my chars.

Probably belongs to the unsolved mysteries... 😄
