### ISSUE TITLE
NPC ID Option

### ISSUE THREAD

**Issue by DaleHuntGB** [frozn/TipTac#244]
**Is your feature request related to a problem? Please describe.**
No, it isn't but we do have IDs for everything else (and unless I am blind), I cannot find the option to show NPC IDs.

**Describe the solution you'd like**
Add the option to get the NPC ID.

**Describe alternatives you've considered**
idTip AddOn does this but I would rather not have two AddOns for tooltips.

**Comment by frozn** [comment]
Good idea! Will be included in the next release. 👍
