### ISSUE TITLE
10.1.5 Redundant extra row in player tooltips

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#246]
**Describe the bug**
In 10.1.5, an extra row appeared in player tooltips:
![image](https://github.com/frozn/TipTac/assets/365584/59ffd6f3-3aaa-462d-b5a7-cf49f802fdb0)

**To Reproduce**
Hover over any player.

**Expected behavior**
The middle row should not be there as it wasn't before and is totally redundant.

**TipTac Reborn:**
 - Version 23.06.20

**WoW:**
 - Flavor: Retail
 - Version 10.1.5

**Additional context**
Reproducible with all other addons disabled.

**Comment by Zasz333** [comment]
Got the same issue. I thought its a bug that this line is visible since yesterday but I cant find a feature in the settings to disable a specialisation line. Might be an addition to the default interface. Which means we need an option to hide it.

**Comment by hollo6** [comment]
Works nicely in 23.07.14, thank you!
