### ISSUE TITLE
Specialization line not hidden on beast master hunters

### ISSUE THREAD

**Issue by Zasz333** [frozn/TipTac#247]
**Describe the bug**
Enabling hide specialization & class text does not hide the line on beast master hunters.

**TipTac Reborn (please complete the following information):**
 - Version 23.07.14

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.1.5

**Comment by frozn** [comment]
Thanks for reporting this! 👍

I have improved detecting the spec line. Will be included in the next release.
