### ISSUE TITLE
MAGameTooltip ??

### ISSUE THREAD

**Issue by Creepshow1168** [frozn/TipTac#248]
![WoWScrnShot_071723_110657](https://github.com/frozn/TipTac/assets/116711637/19f97ffd-c78b-4da4-a747-d9e0afc5e0e9)

Is this an issue with TipTac or do I need to find it elsewhere ?? if i right click on my character this pops up

**Comment by frozn** [comment]
Hm, I think it might come from another addon, e.g. MoveAnything. Please try to disable the mentioned or (all) other addons to check, if it comes from TipTac.
