### ISSUE TITLE
Automatic detection through WowUpHub

### ISSUE THREAD

**Issue by linaori** [frozn/TipTac#25]
Heya! 

I noticed the little install section for WowUp install from URL. As that is already working this repository seems to be compatible with WowUpHub, which makes it possible to detect the addon through WowUp, making it more discoverable. For more info: https://wowup.io/guide/wowup/hub

The adding process has a few manual steps for now, but if you're interested in having it on there, it can be arranged. As pretty much everything goes through github, it should be a minimal impact in terms of extra effort and maintenance from your side.

**Comment by frozn** [comment]
I know this link you mentioned. I used this informations to add corresponding zip-files to the release assets so the "install from url" in wowup works with this repository.

Which additional "manual steps" are required here?

**Comment by linaori** [comment]
This repository would need to be linked to the Hub, so that github can call webhooks when a new release is made

**Comment by frozn** [comment]
I would be okay with that. How do we proceed?

**Comment by linaori** [comment]
Now we wait for @jliddev to do some magic tricks 😄

**Comment by frozn** [comment]
Roger that :sunglasses::thumbsup:

**Comment by linaori** [comment]
There you go! https://wowup.io/addons/995110
