### ISSUE TITLE
Level, Race and Class keeps multiplying

### ISSUE THREAD

**Issue by Rastahunden** [frozn/TipTac#253]
The tooltip keeps adding level, race and class multiple times. Only happens on players who are in a guild.
This is what it looks like after a few seconds

![Tooltip2](https://github.com/frozn/TipTac/assets/13975144/44069259-fde4-4465-b886-822c00a7619d)

TipTac-v23.08.23
Classic Era
1.14.4

**Comment by frozn** [comment]
I can't reproduce this on my side. Does this error also occur if you disable all other addons?

**Comment by Rastahunden** [comment]
I had an issue with Threatplates too and that was fixed with turning off colourblind mode, and it fixed this problem as well. So it's all good now

**Comment by frozn** [comment]
Ah, with enabled colorblind mode I could reproduce this behaviour in classic era. Fix will be included in the next release. 👍
