### ISSUE TITLE
Gearscore

### ISSUE THREAD

**Issue by Suttekluden** [frozn/TipTac#256]
**Is your feature request related to a problem? Please describe.**
I find it annoying to have to use a WA to get the GS value that everyone is working by as the standard seems to be that of TacoTip.

**Describe the solution you'd like**
Change the formula to that of TacoTip.

**Describe alternatives you've considered**
I've tried to change it myself, but for some reason I get absolutely no effect when altering the formula, so I'm probably changing stuff in the wrong file or something.

**Additional context**
TipTac Gearscore:
![image](https://github.com/frozn/TipTac/assets/49807655/4ba1a3c3-1865-4531-9a18-247400adf55d)

TacoTip / WA Gearscore:
![image](https://github.com/frozn/TipTac/assets/49807655/d45a8b1b-865b-4381-b988-e0cddcf0e094)

**Comment by frozn** [comment]
In the past I added a simpler version of GearScore to also be compatible to retail version and to give "the player" (a better) indicator as the average item level to see the power of other players.

But in case of sharing the GearScore with other players this doesn't work if the calculation isn't the same. So I finally added the option "Talents/AIL->GearScore Algorithm" to switch between the de facto standard algorithm from addon TacoTip and TipTac's own implementation.
