### ISSUE TITLE
TipTac Ref Bug on mouseover

### ISSUE THREAD

**Issue by aromagnoli** [frozn/TipTac#257]
**Describe the bug**
Mouseover the progress bar at the portal after the speed gauntlet on Dawn of the Infinite Megadungeon.

**To Reproduce**
1. Click on the portal to start.
2. Mouseover the progress bar.

**Expected behavior**
I expected nothing to happened.

**Screenshots**
Didnt took a screenshot. =(

**TipTac Reborn (please complete the following information):**
 - Version 23.08.28

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.1.7
 - 
**Additional context**
Nothing to add.

**Comment by frozn** [comment]
Unfortunately I didn't have a character to go to this megadungeon. 🙈

To solve this issue I need the error log after mouseover the progress bar. Can you post this here the next time you encounter this error?

**Comment by hollo6** [comment]
I'm having the same issue, below is my LUA error. (You can go there on HC now btw :) )

5x TipTac/ttCore.lua:2440: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@TipTac/ttCore.lua"]:2440: in function `ResetCurrentDisplayParamsForAnchoring'
[string "@TipTac/ttCore.lua"]:2478: in function <TipTac/ttCore.lua:2477>
[string "=[C]"]: in function `SetOwner'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:63: in function `SetTooltipOwner'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:69: in function `OnEnter'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:622: in function <...Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:621>

Locals:
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = EmbeddedItemTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @FrameXML/GameTooltip.lua:1108
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.l

**Comment by hollo6** [comment]
Same bug is happening in Amirdrassil at the portal after Nymue.

**Comment by hollo6** [comment]
Seeing "fixed errors regarding "calling ... on bad self"" in release notes, but this is still happening.
Very easy to reproduce in LFR with the portal.

**Comment by frozn** [comment]
Implementing checks if e.g. the NameplateTooltip currently is forbidden in all TipTac functions adjusting the tooltip seems generally to be a good idea (see https://warcraft.wiki.gg/wiki/API_FrameScriptObject_IsForbidden). My hope was, that this probably fixes this "calling on bad self" problems too, bit I haven't seen this live for myself.

I will try reproducing this in LFR. Where exactly happened this error at this portal after Nymue? Hovering over it?

**Comment by hollo6** [comment]
You can click on the portal to channel it, that's fine. The error pops up when you hover over the progress bar above the portal.

**Comment by frozn** [comment]
Can I repeat this multiple times?

**Comment by hollo6** [comment]
I think the error pops every time you (re-)hover the progress bar. But it fills up pretty quickly so I don't know how many times you can actually do it per instance.

**Comment by frozn** [comment]
In the meantime this has been fixed. I added several `IsForbidden()` checks to make shure, that the tooltip isn't accessed while it's protected.
