### ISSUE TITLE
no quality-colored borders on item tooltips with Z-Perl unitframes installed

### ISSUE THREAD

**Issue by frozn** [frozn/TipTac#26]
ywfn666:
Ever since the 9.1.5 patch, even after applying the various TipTac fixes (currently using frozn's latest release), I'm not able to get quality-colored borders on my item tooltips anymore.  If I disable the Z-Perl unit frames addon that I use, they begin working again.   There's only a small few tooltip-related options in Z-Perl and I've tried screwing around with all of them, but it doesn't change anything.

Anyone else run into this?  Is there any potential solution for it in TipTac, or is it something that would have to be fixed in Z-Perl?

---
frozn45:
I temporarily disabled my unitframe addon Pitbull4 and installed Z-Perl unitframes. The quality-colored borders are working fine here with both addons (z-perl + tiptac) enabled. Can't reproduce it.

---
ywfn666:
Definitely seems to be coming from Z-Perl.  I tested it on 3 different characters, and on one of them, disabled virtually everything else other than TipTac and Z-Perl, and the problem is still only present when Z-Perl is loaded.  Hmm.....maybe it's some setting I have in either TipTac or Z-Perl that's required to reproduce it...will see if I can figure that out.

---
ywfn666:
@frozn45: Did more testing on the Z-Perl + TipTac problem I mentioned before.  Installed the latest Z-Perl and your latest TipTac version from scratch, and deleted their config files in my WTF directory so I got 100% fresh configurations of both.  No other addons enabled.  Still seeing the problem that way, so it doesn't appear to require any special configuration.  With any of the Z-Perl modules enabled (Player, Target, etc), none of TipTac's ItemRef stuff works - it's not just that items don't get quality colored borders either, but you also don't get the item level / item ID line (assuming you've turned that on), etc. Hmm......

Played around with it, and it seemed TipTacItemRef's hooks weren't getting set. What's happening is that, without Z-Perl present, the main TipTac addon's VARIABLES_LOADED() is getting called before TipTacItemRef's VARIABLES_LOADED().  But with Z-Perl present, TipTacItemRef's VARIABLES_LOADED() is being called before the main addon's.  No idea why Z-Perl would influence the order.  Anyway, TipTacItemRef's VARIABLES_LOADED() being called before the main addon's appears to lead to some tables not being setup properly yet inside the tipsToModify variable, which means TipTacItemRef's hooks never get installed.  I don't know what the "proper" fix is, but what I did as a quick hack is changed TipTacItemRef to use PLAYER_ENTERING_WORLD (which fires a bit later) instead of VARIABLES_LOADED, and that has fixed everything for me.

**Comment by frozn** [comment]
Fixed in main branch.

**Comment by ywfn** [comment]
I installed that dev version and it fixes the problem.  ItemRef works along with Z-Perl being loaded.  Thanks for your great work keeping TipTac going.

**Comment by frozn** [comment]
Thanks for your feedback! I am about to create a new release with various other bug fixes. This one will be included. 👍
