### ISSUE TITLE
LUA error and tooltips not shown

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#262]
**Describe the bug**
In version 23.10.15, getting the following LUA error when hovering over some brokers and they do not function.
Rolled back to 23.08.28 where the issue is not present.

14x TipTac/ttCore.lua:1565: calling 'GetScale' on bad self (Usage: local frameScale = self:GetScale())
[string "=[C]"]: in function `GetScale'
[string "@TipTac/ttCore.lua"]:1565: in function `SetScaleToTip'
[string "@TipTac/ttCore.lua"]:1685: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:889: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1507: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1359: in function <TipTac/ttCore.lua:1358>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:102: in function `OnEnter'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua"]:622: in function <...Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:621>

Locals:
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = EmbeddedItemTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @FrameXML/GameTooltip.lua:1108
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.l

**To Reproduce**
1. Hover over some brokers (e.g. Broker_DungeonDifficulty, Broker_LootSpec)
2. Observe LUA error
3. Brokers not functioning

**Expected behavior**
"Dropdowns" are supposed to appear to use.

**Screenshots**
N/A

**TipTac Reborn (please complete the following information):**
 - Version 23.10.15

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.1.7

**Additional context**
Working fine in previous version (23.08.28).

**Comment by frozn** [comment]
Which data broker display addon do you use? Under addon Bazooka dropdown from Broker_DungeonDifficulty and Broker_LootSpec are working fine under 23.10.15.

**Comment by hollo6** [comment]
I'm using Titan Panel.

**Comment by frozn** [comment]
Hm, under Titan Panel everything still works fine. 🤔

**Comment by frozn** [comment]
If you disable all addons except TipTac, Titan Panel and Broker_DungeonDifficulty / Broker_LootSpec, do you still get this error?

**Comment by hollo6** [comment]
I don't get the error after a /reload with this version either, so I'm not sure what triggers it.
It happened in DotI though, so it might have something to do with this one: [https://github.com/frozn/TipTac/issues/257](url), but with 23.08.28, I've never seen it happen.

**Comment by hollo6** [comment]
Maybe worth noting that the common thing in these 2 brokers is that they have a dropdown-style tooltip that has functionality when clicked, and the other brokers that don't have this issue are only info tips.

**Comment by hollo6** [comment]
Happened again in DotI but this time only Broker_LootSpec was affected.

**Comment by hollo6** [comment]
I just reproduced this in DotI, definitely has something to do with the issue linked above.
After getting that error, on the _second_ hover on Broker_LootSpec, this happens.

**Comment by frozn** [comment]
In the meantime this has been fixed. I added several `IsForbidden()` checks to make shure, that the tooltip isn't accessed while it's protected.
