### ISSUE TITLE
10.2 Errors

### ISSUE THREAD

**Issue by WuhbGaming** [frozn/TipTac#265]
Updated returned to the game and got a few.

**No. 1**

Message: Interface/AddOns/TipTac/ttCore.lua:2442: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
Time: Sat Nov 11 16:01:21 2023
Count: 4
Stack: Interface/AddOns/TipTac/ttCore.lua:2442: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:2442: in function `ResetCurrentDisplayParamsForAnchoring'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:2480: in function <Interface/AddOns/TipTac/ttCore.lua:2479>
[string "=[C]"]: in function `SetOwner'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:880: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:879>

Locals: (*temporary) = NamePlateTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = NamePlateTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = NamePlateTooltipStatusBar {
 }
 SetPossession = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <fu

**No. 2**

Message: Interface/AddOns/TipTac/ttCore.lua:1565: calling 'GetScale' on bad self (Usage: local frameScale = self:GetScale())
Time: Sat Nov 11 16:01:21 2023
Count: 4
Stack: Interface/AddOns/TipTac/ttCore.lua:1565: calling 'GetScale' on bad self (Usage: local frameScale = self:GetScale())
[string "=[C]"]: in function `GetScale'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:1565: in function `SetScaleToTip'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:1685: in function `?'
[string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:889: in function `FireGroupEvent'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:1507: in function `SetCurrentDisplayParams'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:1359: in function <Interface/AddOns/TipTac/ttCore.lua:1358>
[string "=[C]"]: in function `Show'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:391: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `setFunction'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:886: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:879>

Locals: (*temporary) = NamePlateTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 processingInfo = <table> {
 }
 i

**No. 3** 

Message: Interface/AddOns/TipTacItemRef/ttItemRef.lua:2674: Attempt to access forbidden object from code tainted by an AddOn
Time: Sat Nov 11 16:01:21 2023
Count: 4
Stack: Interface/AddOns/TipTacItemRef/ttItemRef.lua:2674: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `AddLine'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:2674: in function `spell'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:651: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:639>
[string "=[C]"]: ?
[string "=[C]"]: in function `setFunction'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:886: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:879>

Locals: (*temporary) = NamePlateTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 TextLeft1 = NamePlateTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = NamePlateTooltipStatusBar {
 }
 SetPossession = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.

**No. 4**

Message: Interface/AddOns/TipTac/ttCore.lua:2070: calling 'GetParent' on bad self (Usage: local parent = self:GetParent())
Time: Sat Nov 11 16:01:21 2023
Count: 4
Stack: Interface/AddOns/TipTac/ttCore.lua:2070: calling 'GetParent' on bad self (Usage: local parent = self:GetParent())
[string "=[C]"]: in function `GetParent'
[string "@Interface/AddOns/TipTac/ttCore.lua"]:2070: in function <Interface/AddOns/TipTac/ttCore.lua:2069>
[string "=[C]"]: in function `SetCenterColor'
[string "@Interface/SharedXML/SharedTooltipTemplates.lua"]:145: in function <Interface/SharedXML/SharedTooltipTemplates.lua:134>
[string "=[C]"]: in function `SharedTooltip_SetBackdropStyle'
[string "@Interface/FrameXML/GameTooltip.lua"]:550: in function <Interface/FrameXML/GameTooltip.lua:547>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:893: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:892>

Locals: (*temporary) = Frame {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined =[C]:-1
 GetCenterColor = <function> defined @Interface/SharedXML/NineSlice.lua:286
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetCenterColor = <function> defined =[C]:-1
 GetFrameLayoutTextureKit = <function> defined @Interface/SharedXML/NineSlice.lua:267
 SetVertexColor = <function> defined @Interface/SharedXML/NineSlice.lua:316
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 GetBorderColor = <function> defined @Interface/SharedXML/NineSlice.lua:304
 TopRightCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 0 = <userdata>
 OnLoad = <function> defined @Interface/SharedXML/NineSlice.lua:272
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 Center = Texture {
 }
 TopLeftCorner = Texture {
 }
 ClearBackdrop = <function> defined =[C]:-1
 GetFrameLayoutType = <function> defined @Interface/SharedXML/NineSlice.lua:263
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 SetBorderColor = <function> defined =[C]:-1
}

**Comment by frozn** [comment]
In the meantime this has been fixed. I added several `IsForbidden()` checks to make shure, that the tooltip isn't accessed while it's protected.
