### ISSUE TITLE
Mouseover on hunter in Classic Season of Discovery error

### ISSUE THREAD

**Issue by Jeremy7600** [frozn/TipTac#268]
**Describe the bug**
62x SharedXML/Color.lua:61: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@SharedXML/Color.lua"]:61: in function <SharedXML/Color.lua:60>
[string "=(tail call)"]: ?
[string "@TipTacTalents/ttTalents.lua"]:308: in function `callback'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:2558: in function `FinishInspect'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:2549: in function `FinishInspectDataAvailable'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:2523: in function `callbackForItemData'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:3019: in function `LFF_GetAverageItemLevelFromItemData'
[string "@TipTac/libs/LibFroznFunctions-1.0-15/LibFroznFunctions-1.0.lua"]:2795: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2791>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/Item.lua"]:298: in function `FireCallbacks'
[string "@FrameXML/ObjectAPI/Item.lua"]:260: in function <FrameXML/ObjectAPI/Item.lua:256>

Locals:
(*temporary) = "|c%s%s|r"
(*temporary) = "ff000000"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**To Reproduce**
1. Mouse over hunter character (not all hunters, but I've only noticed it with hunters)
2. See error

**Expected behavior**
No error when mousing over a player in the world or their frame. 

**TipTac Reborn (please complete the following information):**
 - Version 23.11.06

**WoW (please complete the following information):**
 - Flavor: Classic Season of Discovery
 - Version 1.15.0

**Additional context**
Can't tell what is triggering it, could be a hunter rune in the new Season.

**Comment by Jeremy7600** [comment]
Had it happen on a druid just now, so not just hunters

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

I changed the code to consider situations where a player's GearScore couldn't be determined properly.

Will be included in the next release.
