### ISSUE TITLE
[Flickering] It Shortly flickers when click transmogs in Transmogrifying window

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#27]
It's shortly flickering like this. Seems it went to original anchor and came right back to tiptac's anchor
https://imgur.com/a/FKhXEb8

**Comment by frozn** [comment]
Is this related to ElvUI? I can't reproduce this. :raised_eyebrow:

**Comment by frozn** [comment]
I couldn't reproduce this one, but I think my fix for #28 can resolve it, too. Can you test with main-branch?

**Comment by hobulian** [comment]
No. this one still happen.. Dunno why. When clicking other transmog at transmog window it still happen.

**Comment by hobulian** [comment]
And also fount out that WardrobeCollectionFrame.SetsTransmogFrame's set's tooltip border isn't quality colored yet..

**Comment by frozn** [comment]
> And also found out that WardrobeCollectionFrame.SetsTransmogFrame's item set's tooltip border isn't quality colored yet..

How do I get to frame WardrobeCollectionFrame.SetsTransmogFrame?

**Comment by frozn** [comment]
Ah... it's the transmogrifier on your mount. I will have a look at it...

**Comment by frozn** [comment]
Can reproduce both issues! 👍

**Comment by frozn** [comment]
Fixed. I added/changed the following things:

- fixed flickering of tooltip when selecting an item or illusion at transmogrifier if "Anchors->Frame Tip Type = Mouse Anchor"
- added border color and infos for sets at transmogrifier
- fixed disappearing border color and infos when selecting an illusion at transmogrifier
- added mouseover tooltip for transmog items and sets chatlinks

Seems good now! 👍

**Comment by hobulian** [comment]
Wow. I will check it out when back to home. So excepted!

**Comment by frozn** [comment]
Fixed all errors (and 2 more):

- fixed disappearing border color and infos if scrolling through illusions in wardrobe
- fixed disappearing border color and infos on first mouseover if scrolling through toys in toy box
- fixed sometimes disappearing border color and infos on first selecting on some sets at transmogrifier if waiting for set data
- fixed flickering if scrolling through runecarving powers in "Adventure Guide->Powers" if "Anchors->Frame Tip Type" = "Mouse Anchor"
- fixed flickering if scrolling through toys in toy box from last page to previous page and "Anchors->Frame Tip Type" = "Mouse Anchor"

Committed to main-branch. Looks fine to you, too? 😉

**Comment by hobulian** [comment]
It's all fine now. All the problems are fixed now!
Among all found flickering issue Only #7 is left now.

**Comment by frozn** [comment]
I excluded the ItemRefTooltip from re-anchoring (as it has already been for ShoppingTooltip1/2 and ItemRefShoppingTooltip1/2). Re-anchoring of FloatingBattlePetTooltip and FloatingPetBattleAbilityTooltip has never been applied. Changes are in main branch.

I think it seems fine now. What do you think?

**Comment by hobulian** [comment]
All is good now :)

**Comment by frozn** [comment]
Ah, good to hear. 😎
