### ISSUE TITLE
frameForDelayedInspection:HookNotifyInspect has an incorrect check

### ISSUE THREAD

**Issue by Dairyman** [frozn/TipTac#271]
https://github.com/frozn/TipTac/blob/5e91acb2b1ec917365a825762e38eeab11829ec5/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua#L2604-L2606

should that not be 
```Lua
if (frameForDelayedInspection.NotifyInspectHooked) then 
 	return; 
 end 
```

`frameForDelayedInspection.NotifyInspectHooked` initial value is `false`.

**Comment by frozn** [comment]
Thanks for this hint! 👍

I'm currently refactoring some parts before I add the next feature requests. I already pushed them to the repository but I haven't tested them yet.

But this hooking thing isn't obvious to recognize during testing and might have slipped through if you haven't mentioned this. 😉
