### ISSUE TITLE
Faction text visible despite disabled

### ISSUE THREAD

**Issue by Zasz333** [frozn/TipTac#276]
As the title says. Since the retail update last week the faction text is visible despite the option to hide them is enabled.

**Comment by frozn** [comment]
I think you have to disable "Colors->Show the unit's Faction Text" too to disable TipTac's own faction text.

Does this solve your issue?

**Comment by Zasz333** [comment]
Yes. That fixes it. Thanks. I would have never guessed.

It works the same way as "Special -> Hide Faction Text" it seems. Why is one option working and the other does not? Why are there two options for the same feature?

**Comment by frozn** [comment]
You're right. It doesn't make sense to have this two options in parallel. I removed "Special -> Hide Faction Text" and combined this function with option "Colors->Show the unit's Faction Text".

This fix is included in the latest release [v24.03.23](https://github.com/frozn/TipTac/releases/tag/v24.03.23-release).
