### ISSUE TITLE
I am getting multiple LUA  errors all the time 

### ISSUE THREAD

**Issue by rionshin** [frozn/TipTac#278]
**Describe the bug**
My bug sack is flooded with this error:

51x TipTac/ttCore.lua:1698: calling 'GetScale' on bad self (Usage: local frameScale = self:GetScale())
[string "=[C]"]: in function `GetScale'
[string "@TipTac/ttCore.lua"]:1698: in function `SetScaleToTip'
[string "@TipTac/ttCore.lua"]:1382: in function `SetAppearanceToTip'
[string "@TipTac/ttCore.lua"]:1311: in function `ApplyConfig'
[string "@TipTac/ttCore.lua"]:1822: in function `AddModifiedTipExtended'
[string "@TipTac/ttCore.lua"]:471: in function `Acquire'
[string "@SavedInstances/Core/Tooltip.lua"]:43: in function `AcquireTooltip'
[string "@SavedInstances/Core/Core.lua"]:3315: in function `ShowTooltip'
[string "@SavedInstances/Core/Core.lua"]:2498: in function `OnEnter'
[string "@AutoCombatLogger/Libs/LibDBIcon-1.0-52/LibDBIcon-1.0.lua"]:76: in function `oenter'
[string "@MBB/MBB.lua"]:493: in function <MBB/MBB.lua:475>

also :

8x TipTacItemRef/ttItemRef.lua:2671: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `AddLine'
[string "@TipTacItemRef/ttItemRef.lua"]:2671: in function `spell'
[string "@TipTacItemRef/ttItemRef.lua"]:656: in function <TipTacItemRef/ttItemRef.lua:644>
[string "=[C]"]: ?
[string "=[C]"]: in function `setFunction'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:898: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:891>

Also : 
11x TipTac/ttCore.lua:2594: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@TipTac/ttCore.lua"]:2594: in function `ResetCurrentDisplayParamsForAnchoring'
[string "@TipTac/ttCore.lua"]:2632: in function <TipTac/ttCore.lua:2631>
[string "=[C]"]: in function `SetOwner'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:892: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:891>

Locals:
(*temporary) = NamePlateTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1076
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1114
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetWorldLootObject = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextLeft1 = NamePlateTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetEnhancedConduit = <function> defined =[C]:-1
 StatusBar = NamePlateTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @FrameXML/GameTooltip.lua:1110
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:53

**To Reproduce**
 Its generated all the time in Bugsack on any Tooltip event 
this is happening when 10.2.6 hit and latest version of tiptac was released 

**Expected behavior**
No bugs captured in  BugSack

**Screenshots**

**TipTac Reborn (please complete the following information):**
 24.03.23 

**WoW (please complete the following information):**
Retail 10.2.6.53913

**Additional context**

**Comment by frozn** [comment]
In the meantime this has been fixed. I added several `IsForbidden()` checks to make shure, that the tooltip isn't accessed while it's protected.
