### ISSUE TITLE
Error when mousing over other players

### ISSUE THREAD

**Issue by Bronsin** [frozn/TipTac#279]
I get the below error when I mouse over other players. Happens on all characters, multiple classes. Just started happening today.
 
173x TipTac/ttStyle.lua:562: attempt to index a nil value
[string "@TipTac/ttStyle.lua"]:562: in function `ModifyUnitTooltip'
[string "@TipTac/ttStyle.lua"]:764: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-19/LibFroznFunctions-1.0.lua"]:1038: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:2814: in function `SetUnitAppearanceToTip'
[string "@TipTac/ttCore.lua"]:2917: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-19/LibFroznFunctions-1.0.lua"]:1038: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1640: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1515: in function <TipTac/ttCore.lua:1514>
[string "@TipTac/libs/LibFroznFunctions-1.0-19/LibFroznFunctions-1.0.lua"]:344: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:342>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:1094: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1527: in function <FrameXML/UIParent.lua:1450>
[string "=[C]"]: ?

Locals:
self = <table> {
 GenerateTargetLines = <function> defined @TipTac/ttStyle.lua:203
 OnTipResetCurrentDisplayParams = <function> defined @TipTac/ttStyle.lua:767
 OnConfigLoaded = <function> defined @TipTac/ttStyle.lua:731
 GenerateNpcLines = <function> defined @TipTac/ttStyle.lua:452
 GeneratePetLines = <function> defined @TipTac/ttStyle.lua:420
 OnTipSetCurrentDisplayParams = <function> defined @TipTac/ttStyle.lua:737
 GeneratePlayerLines = <function> defined @TipTac/ttStyle.lua:341
 ModifyUnitTooltip = <function> defined @TipTac/ttStyle.lua:474
 GenerateTargetedByLines = <function> defined @TipTac/ttStyle.lua:229
 OnTipStyle = <function> defined @TipTac/ttStyle.lua:745
 HighlightTipTacDeveloper = <function> defined @TipTac/ttStyle.lua:261
 RemoveUnwantedLinesFromTip = <function> defined @TipTac/ttStyle.lua:151
}
tip = GameTooltip {
 SetATTReferenceForTexture = <function> defined @AllTheThings/src/UI/Game Tooltip.lua:272
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 ClearATTReferenceTexture = <function> defined @AllTheThings/src/UI/Game Tooltip.lua:265
 AllTheThingsOnTooltipClearedHook = true
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1076
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1114
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined @Altoholic/Services/Tooltip.lua:621
 SetMerchantItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetWorldLootObject = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipD

**Comment by srhinos** [comment]
Ran into the same issue. Looks like `GetDungeonScoreRarityColor` isnt working? Super weird 

Anyway, in the interim I just disabled [these lines](https://github.com/frozn/TipTac/blob/main/TipTac/modules/ttStyle.lua#L557-L563) in `ttStyle.lua`

**Comment by itsSinba** [comment]
It's indeed _C_ChallengeMode.GetDungeonScoreRarityColor_ that now returns nil since today's update. I'm also trying to figure it out, in the meantime you only need to uncheck the option "**Show Mythic+ Dungeon Score**" option in General, no need to comment out the code

**Comment by acx-nvstar** [comment]
uncheck this and everything will be back to normal
![image](https://github.com/frozn/TipTac/assets/13439803/59f162b6-800f-4ca6-9e5c-c8bc98cc68dd)

**Comment by frozn** [comment]
Thanks for reporting this! 👍

It's now considered that C_ChallengeMode.GetDungeonScoreRarityColor() to determine the mythic+ dungeon score color may return nil:
https://github.com/frozn/TipTac/blob/af15500f780bd8bc523e76e3f8a7f2c3e50751b6/TipTac/modules/ttStyle.lua#L557-L564

Will be included in the next release.

**Comment by Ookami313** [comment]
Not sure if it makes a difference, I was getting the same error, but when I moused over items in my bag as well. I updated my ttStyle.lua file using a copy of the one above ("Save link as" and overwrote the one in the main directory) with what I assumed contained the fixes in it. I'm now getting the following errors when I log into the game. The addon seems to work fine, just keep getting errors if I log out to switch characters and such. Thanks.

1x TipTac/ttStyle.lua:7: unexpected symbol near '<'


Locals:


2x TipTac/ttStyle.lua:1 TipTac/ttStyle.lua:7: unexpected symbol near '<'

**Comment by frozn** [comment]
"Save link as" doesn't work for downloading individual files. You have to navigate to "ttStyle.lua" and click on it (https://github.com/frozn/TipTac/blob/main/TipTac/modules/ttStyle.lua). On the screen now displaying the contents of "ttStyle.lua" you have to click on button "Download raw file":

![image](https://github.com/frozn/TipTac/assets/5655881/0015930b-2d90-40d1-986a-4e39519bdb15)

**Comment by Ookami313** [comment]
Awesome, thank you very much.

> "Save link as" doesn't work for downloading individual files. You have to navigate to "ttStyle.lua" and click on it (https://github.com/frozn/TipTac/blob/main/TipTac/modules/ttStyle.lua). On the screen now displaying the contents of "ttStyle.lua" you have to click on button "Download raw file":
> 
> ![image](https://private-user-images.githubusercontent.com/5655881/323182000-0015930b-2d90-40d1-986a-4e39519bdb15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjY3MTcsIm5iZiI6MTcxMzM2NjQxNywicGF0aCI6Ii81NjU1ODgxLzMyMzE4MjAwMC0wMDE1OTMwYi0yZDkwLTQwZDEtOTg2YS00ZTM5NTE5YmRiMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMTUwNjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdmYmZmZjVkNDQ4ZjlkNTAzNTcwOGZkZDFlZDMzZjIyZTEyZDRmM2ZhOGZmNDY0MzY5NWM0YzdhOGMxZDE1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fh5OyzlilpdCc0AF96QDeoIP8DA3oiNXbpL9_NsXqI0)

Awesome, thank you very much.
