### ISSUE TITLE
[Flickering] When player is flying(with mounts). Some object's tooltips at world map flickers

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#28]
This is example. Other examples are anima-conductor's daily quests on map and great vault's vigneette at oribos map
https://imgur.com/a/fN9Tl1c

Dunno why it happens only when player fly.

**Comment by frozn** [comment]
Is this related to ElvUI? I can't reproduce this. :raised_eyebrow:

**Comment by hobulian** [comment]
> Is this related to ElvUI? I can't reproduce this. 🤨

https://www.youtube.com/watch?v=3cJ33dDPpCE&ab_channel=%EC%A0%84%EC%9A%B0%EC%A7%84

**Comment by frozn** [comment]
Crazy... I will check this :muscle:

**Comment by frozn** [comment]
I think I got it. Can you test with main-branch?

**Comment by hobulian** [comment]
Now it's fine. Working!
