### ISSUE TITLE
HP text often cut off when using "Values & Percent"

### ISSUE THREAD

**Issue by 0xjc** [frozn/TipTac#281]
HP text is often cut off. I use "Values & Percent" and I would prefer for the tooltip to be wider to show all of it. I think this is a recent issue.

![image](https://github.com/frozn/TipTac/assets/5281913/a8e570c6-c442-4ce2-a060-6c7137a50c89)

My font settings for HP text if relevant:

![image](https://github.com/frozn/TipTac/assets/5281913/f4e5e0eb-eace-41c1-8ba8-8995fe383664)

As a workaround I can make the font size smaller, but it has to be really small to work reliably.

Font size 10 (still cut off):

![image](https://github.com/frozn/TipTac/assets/5281913/f4726ba9-37ba-4950-a7f6-f586e20eb9ee)

Font size 9 (works, but hard to read):

![image](https://github.com/frozn/TipTac/assets/5281913/5366d574-1342-4727-8b67-06132ad69561)

**TipTac Reborn (please complete the following information):**
 - Version 24.04.27

**WoW (please complete the following information):**
 - Flavor: Retail
 - Version 10.2.6

**Comment by frozn** [comment]
Thanks for reporting this! 👍

With the latest release [v24.04.27](https://github.com/frozn/TipTac/releases/tag/v24.04.27-release) I adjusted the bar text to not go out of bounds. A while ago I added a fixed minum width if bars are enabled, but I made this minimum width now adjustable by moving this to settings under tab "Bars":

![image](https://github.com/frozn/TipTac/assets/5655881/6a6ba070-43dc-4fdb-a9a6-8070a1409781)

Will be included in the next release.
