### ISSUE TITLE
Collections bug/errors

### ISSUE THREAD

**Issue by AutolycusWolf** [frozn/TipTac#282]
**Describe the bug**
When opening the Collections the first time, a number of errors pop up (no other addons are loaded).

**To Reproduce**
1. Go to 'Collections'
or
2. Click on 'SHIFT-P'
3. See error

**TipTac Reborn**
- Version 24.05.02

**WoW**
- Flavor: Cataclysm Classic
- Version 4.4.0

**Additional context**
1x TipTacItemRef/ttItemRef.lua:2050: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@TipTacItemRef/ttItemRef.lua"]:2050: in function `?'
[string "@TipTacItemRef/ttItemRef.lua"]:357: in function <TipTacItemRef/ttItemRef.lua:357>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Cata/UIParent.lua"]:247: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Cata/UIParent.lua"]:395: in function `CollectionsJournal_LoadUI'
[string "@Blizzard_UIParent/Cata/UIParent.lua"]:606: in function `SetCollectionsJournalShown'
[string "@Blizzard_UIParent/Cata/UIParent.lua"]:600: in function `ToggleCollectionsJournal'
[string "@Blizzard_ActionBar/Cata/MainMenuBarMicroButtons.lua"]:503: in function <.../Blizzard_ActionBar/Cata/MainMenuBarMicroButtons.lua:501>

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.
