### ISSUE TITLE
LUA Errors on different tooltips

### ISSUE THREAD

**Issue by rionshin** [frozn/TipTac#283]
### Describe the bug

It block opening some Addon as SavedInstances  and generate following errors :

25x TipTac/ttCore.lua:1890: calling 'SetGradient' on bad self (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "@TipTac/ttCore.lua"]:1890: in function `SetGradientToTip'
[string "@TipTac/ttCore.lua"]:1471: in function `SetAppearanceToTip'
[string "@TipTac/ttCore.lua"]:1399: in function `ApplyConfig'
[string "@TipTac/ttCore.lua"]:1933: in function `AddModifiedTipExtended'
[string "@TipTac/ttCore.lua"]:498: in function `Acquire'
[string "@SavedInstances/Core/Tooltip.lua"]:43: in function `AcquireTooltip'
[string "@SavedInstances/Core/Core.lua"]:3316: in function `ShowTooltip'
[string "@SavedInstances/Core/Core.lua"]:2499: in function `OnEnter'
[string "@AutoCombatLogger/Libs/LibDBIcon-1.0-52/LibDBIcon-1.0.lua"]:76: in function `oenter'
[string "@MBB/MBB.lua"]:493: in function <MBB/MBB.lua:475>

Locals:
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = "VERTICAL"
(*temporary) = <table> {
 a = 0
 b = 0
 g = 0
 GetRGBA = <function> defined @Blizzard_SharedXML/Color.lua:31
 IsRGBEqualTo = <function> defined @Blizzard_SharedXML/Color.lua:13
 SetRGB = <function> defined @Blizzard_SharedXML/Color.lua:46
 GetRGB = <function> defined @Blizzard_SharedXML/Color.lua:23
 r = 0
 GenerateHexColorMarkup = <function> defined @Blizzard_SharedXML/Color.lua:58
 WrapTextInColorCode = <function> defined @Blizzard_SharedXML/Color.lua:62
 GenerateHexColor = <function> defined @Blizzard_SharedXML/Color.lua:50
 IsEqualTo = <function> defined @Blizzard_SharedXML/Color.lua:19
 OnLoad = <function> defined @Blizzard_SharedXML/Color.lua:9
 GenerateHexColorNoAlpha = <function> defined @Blizzard_SharedXML/Color.lua:54
 SetRGBA = <function> defined @Blizzard_SharedXML/Color.lua:39
 GetRGBAsBytes = <function> defined @Blizzard_SharedXML/Color.lua:27
 GetRGBAAsBytes = <function> defined @Blizzard_SharedXML/Color.lua:35
}
(*temporary) = <table> {
 a = 0.150000
 b = 0.800000
 g = 0.800000
 GetRGBA = <function> defined @Blizzard_SharedXML/Color.lua:31
 IsRGBEqualTo = <function> defined @Blizzard_SharedXML/Color.lua:13
 SetRGB = <function> defined @Blizzard_SharedXML/Color.lua:46
 GetRGB = <function> defined @Blizzard_SharedXML/Color.lua:23
 r = 0.800000
 GenerateHexColorMarkup = <function> defined @Blizzard_SharedXML/Color.lua:58
 WrapTextInColorCode = <function> defined @Blizzard_SharedXML/Color.lua:62
 GenerateHexColor = <function> defined @Blizzard_SharedXML/Color.lua:50
 IsEqualTo = <function> defined @Blizzard_SharedXML/Color.lua:19
 OnLoad = <function> defined @Blizzard_SharedXML/Color.lua:9
 GenerateHexColorNoAlpha = <function> defined @Blizzard_SharedXML/Color.lua:54
 SetRGBA = <function> defined @Blizzard_SharedXML/Color.lua:39
 GetRGBAsBytes = <function> defined @Blizzard_SharedXML/Color.lua:27
 GetRGBAAsBytes = <function> defined @Blizzard_SharedXML/Color.lua:35
}

### Steps to Reproduce

Clicking to open SavedInstances add-on

### Expected behavior

Open the add-on and no LUA errors from TipTac

### Version of TipTac Reborn

v 24.05.07

### Flavor/Version of WoW

Retail

**Comment by frozn** [comment]
In the meantime this has been fixed. I added several `IsForbidden()` checks to make shure, that the tooltip isn't accessed while it's protected.
