### ISSUE TITLE
CPU spikes when mouse over certain types of items

### ISSUE THREAD

**Issue by Road-block** [frozn/TipTac#284]
### Describe the individual topic

For some time I've been experiencing significant FPS drops when mouse over items in bags, some types of items more significant than others.

Logic says if it happens with mouseover it must be a tooltip addon.

In the end I enabled cpu tracking and used addonusage to quantify it.

CPU tracking itself causes an even greater performance hit but even accounting for that the results are pretty clear.

FPS drop without cpu tracking enabled is 128 (capped) > 20-30 fps, with cpu tracking the game becomes a slideshow 128 > 2-3 fps.

As you can see in the attached screenshot TipTac is the biggest offender.
![tiptac-cpu](https://github.com/frozn/TipTac/assets/109839/5e135764-20e4-4427-b866-19019ab17174)
Example item
![tiptac-cpu-2](https://github.com/frozn/TipTac/assets/109839/18ce4e94-c575-4bc5-95d7-4f2443932c7f)

**Comment by Road-block** [comment]
I will do some isolation tests with TipTac the only addon running and then try with some of its optional modules disabled, but this is _not good_ 😞

**Comment by Road-block** [comment]
I disabled every addon that touches the tooltip (RatingBuster and its Statlogic library, Pawn, Bag addon tooltip additions, Auction addon tooltip additions, all the addons that would put anything on the tooltip.

The situation improved somewhat - as expected, any addon that does something wtth the tooltip will use _some cpu_ can't have functionality with zero cost, but I still lose 20-25 FPS when mouse over certain item types with TipTac and TipTacItemRef being the only relevant addons.

![tiptac-cpu-3](https://github.com/frozn/TipTac/assets/109839/691abe19-b0bb-4083-af2d-f12c7011f2d4)

**Comment by frozn** [comment]
I reviewed TipTacs coding but I don't see anything special here which would improve the cpu load significantly. 🤔

I installed addon [AddOns CPU Usage](https://www.curseforge.com/wow/addons/addons-cpu-usage) to check it for myself. CPU tracking for myself. With CPU tracking enabled I currently have 110 fps, and when I hover over a item in my bag where the 2 compare tooltips pop up too, I have 104fps. So on my side the fps only drop by 6 fps or 94% of the original fps.

**Comment by Road-block** [comment]
It's probably compounded with more addons adding stuff to the tooltip.
Thanks for taking a look 😃 

_If you ever want to come back to this, maybe test a bit with some of the very popular addons that add to the tooltip (Rating Buster + Pawn that I already mentioned come to mind)_

**Comment by frozn** [comment]
Screenshot of addon profiler from date 21.07.25:
https://www.reddit.com/r/wow/comments/1m5wjb1/ui_question_tooltip_addon_for_nonelvui_user/

<img width="2179" height="774" alt="Image" src="https://github.com/user-attachments/assets/6005ca5e-319d-45e2-8fc6-87ace73c7b7c" />

**Comment by frozn** [comment]
Relates to #474.
