### ISSUE TITLE
TipTac does not load if it's the only addon enabled.

### ISSUE THREAD

**Issue by Kolmarwow** [frozn/TipTac#289]
### Describe the bug

If you only have TipTac & its dependencies enabled then TipTac doesn't work at all. But if you have some other addons enabled then TipTac works fine, some notable ones listed as an example:

Leatrix Maps
Leatrix Plus
Omnicc
Prat
Threat Plates
Questie
BugSack/BugGrabber

And others, having any of those enabled fixes the problem. Presumably some kind of library issue but I don't know enough to troubleshoot further. 

### Steps to Reproduce

1. Disable all addons except for TipTac & its dependencies (ItemRef/Options/Talents).
2. Addon doesn't work at all.
3. Enable some other addons and TipTac starts working.

### Expected behavior

TipTac should work.

### Version of TipTac Reborn

24.05.18

### Flavor/Version of WoW

Primarily tested on 4.4.0 but seems to be present on 1.15.2 & 10.2.7 as well.

**Comment by frozn** [comment]
You're right, thanks for reporting this! 👍

The dependent lib "CallbackHandler-1.0" for lib "LibDataBroker-1.1" has been missing. Fix will be included in the next release.
