### ISSUE TITLE
[Feature request] Adding hook for SetEnhancedConduit

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#29]
Adding 
hooksecurefunc(tip, "SetEnhancedConduit",SetConduit_Hook);
to the next line of
hooksecurefunc(tip, "SetConduit", SetConduit_Hook);
can fix problem that tiptac's function not working on enhanced conduit's tooltip.

**Comment by frozn** [comment]
Since I have not yet been able to actually play the game because of all the development, I pre-implemented this hook. I have added on my todo-list, that I test it when I unlock them. Can you take a look at version from main branch? 👍

**Comment by hobulian** [comment]
It's working fine. 👍

**Comment by frozn** [comment]
Thanks for testing this!
