### ISSUE TITLE
[Cataclysm Classic] Show Spell ID & Rank shows Spell ID & random stuff

### ISSUE THREAD

**Issue by Kolmarwow** [frozn/TipTac#290]
### Describe the bug

If you enable "Show Spell ID & Rank" in ItemRef, it'll show Spell ID & random stuff related to the tooltip, usually stance/form requirements. This presumably happens as spell ranks were removed in Cataclysm.

![image](https://github.com/frozn/TipTac/assets/28187000/f39d08a3-dda7-43f3-9fde-de3fbf9eaff3)
![image](https://github.com/frozn/TipTac/assets/28187000/b0107a76-1b54-4d00-8e30-927f218e6f81)

Briefly checked Retail/Vanilla and all looks fine there so just a Cataclysm issue, hopefully not another one on Blizzard's end :sweat_smile:

### Steps to Reproduce

1. Enable "Show Spell ID & Rank" in ItemRef
2. Mouseover a warrior / feral druid spell tooltip (possibly others)
3. It'll show form/stance as rank

### Expected behavior

Shouldn't show anything other than Spell ID on Cataclysm (afaik)

### Version of TipTac Reborn

24.05.18

### Flavor/Version of WoW

4.4.0

**Comment by frozn** [comment]
It's not a bug, it's a feature! 😅

In fact the spell id and the "spell subtext" will be displayed, where the subtext originally contains the spell rank. But in newer flavors this now contains other infos:

![image](https://github.com/frozn/TipTac/assets/5655881/ca49c53e-cf5b-4ac6-9cc5-851b0f11286b)

I clarified this in options:

![image](https://github.com/frozn/TipTac/assets/5655881/6f94cafd-b878-4555-a92e-0c99e8a64d13)
