### ISSUE TITLE
Adding a profile sharing function with importing and exporting settings

### ISSUE THREAD

**Issue by frozn** [frozn/TipTac#293]
### Is your feature request related to a problem? Please describe.

From: **Tinter**

Any chance of adding a profile sharing function with importing and exporting settings? Similar to what a lot of other addons do.

Especially with how many different versions of the game there are now. It's a pain to set everything up again without it. As well as just being able to share profiles with other people.

Unless I've missed this functionality lol. Wouldn't be the first time

Source: https://legacy.curseforge.com/wow/addons/tiptac-reborn?comment=481

**Comment by frozn** [comment]
Feeature added. Will be included in the next release.

**Comment by maisonaustyn** [comment]
WoW. Thank you so much. Was literally just looking for this
