### ISSUE TITLE
Breaking Rendering of Addon Bulk Mail Inbox

### ISSUE THREAD

**Issue by polocabbit** [frozn/TipTac#295]
### Describe the bug

When TipTac Reborn and [Bulk Mail Inbox](https://www.curseforge.com/wow/addons/bulkmail-inbox) are both installed and enabled, the rendering of the Bulk Mail Inbox addon is broken. Disabling TipTac fixes the rendering issue.

### Steps to Reproduce

1. Install TipTac Reborn
2. Install [Bulk Mail Inbox](https://www.curseforge.com/wow/addons/bulkmail-inbox)
3. Enable both
![image](https://github.com/frozn/TipTac/assets/6994842/d5f97147-208b-4680-a6e8-23d904f6a6ac)
![image](https://github.com/frozn/TipTac/assets/6994842/c57705fa-f172-4555-a938-22b315938e00)
4. Open Mail Inbox
5. Verify that the inbox rendering **is broken**
6. Disable TipTac Reborn and reload UI
7. Open mail inbox
8. Verify that the inbox rendering is **no longer broken**.

### Expected behavior

When TipTac Reborn is enabled, I expect [Bulk Mail Inbox](https://www.curseforge.com/wow/addons/bulkmail-inbox) to render properly.

### Additional context

I've also verified that no additional addons that I am using are causing [Bulk Mail Inbox](https://www.curseforge.com/wow/addons/bulkmail-inbox)'s rendering to break.

I've recorded a video showing what I see and what I expect it to look like as well: https://youtu.be/p6GDEHGbD9M

### Version of TipTac Reborn

24.05.26

### Flavor/Version of WoW

4.4.0

**Comment by frozn** [comment]
Thanks for reporting this and the detailed error description! 👍

This has been a tricky one. The reason for this error has been setting tip's scale by TipTac and Bulk Mail simultaneously. I have been able to fix this, will be included in the next release.
