### ISSUE TITLE
scale of tooltip too small

### ISSUE THREAD

**Issue by blecaplol** [frozn/TipTac#297]
### Describe the individual topic

When I compare against a gear the scale for the equip gear is smaller, hence the font is also smaller, can u adjust it bigger or let it have option to do so ?

**Comment by frozn** [comment]
Can you provide a screenshot?

By wow default the comparison tooltips are slightly smaller than the original item tooltip to be able to distinguish them.

**Comment by blecaplol** [comment]
actually nvm about this. i just adjusted myself for bigger.
