### ISSUE TITLE
TipTacItemRef/ttItemRef.lua:2695: attempt to index upvalue 'TT_ExtendedConfig' (a nil value)

### ISSUE THREAD

**Issue by TheHalfYeti** [frozn/TipTac#299]
### Describe the bug

212x TipTacItemRef/ttItemRef.lua:2695: attempt to index upvalue 'TT_ExtendedConfig' (a nil value)
[string "@TipTacItemRef/ttItemRef.lua"]:2695: in function `spell'
[string "@TipTacItemRef/ttItemRef.lua"]:646: in function <TipTacItemRef/ttItemRef.lua:637>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetUnitAura'
[string "@ElkBuffBars/EBB_Bar.lua"]:113: in function `OnEnter'
[string "@ElkBuffBars/ElkBuffBars.lua"]:591: in function <ElkBuffBars/ElkBuffBars.lua:591>

Locals:
self = GameTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetTraitEntry = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @Blizzard_GameTooltip/Mainline/GameTooltip.lua:1055
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @Blizzard_GameTooltip/Mainline/GameTooltip.lua:1093
 SetQuestLogSpecialItem = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 TopRightCorner = Texture {
 }
 SetSocketedRelic = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:335
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 ZGV_ShowManyLines = <function> defined @ZygorGuidesViewer/Functions.lua:364
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 hasMoney = 1
 SetArtifactPowerByID = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetWorldLootObject = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:444
 SetEnhancedConduit = <function> defined =[C]:-1
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @Blizzard_GameTooltip/Mainline/GameTooltip.lua:1089
 SetRecipeResultItem = <function> defined =[C]:-1
 SetQuestPartyProgress = <function> defined =[C]:-1
 processingInfo = <table

### Steps to Reproduce

Exist in world? Not sure. Maybe when I cast spells. Specifically, I am on a Lightforged Paladin. Level 11 so spell options are limited.

### Version of TipTac Reborn

24.05.26

### Flavor/Version of WoW

Retail 10.2.7

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Fix will be included in the next release.
