### ISSUE TITLE
[Quality Border] For Essences of  the Heart of Azeroth

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#30]
https://imgur.com/a/doFb5qg

Not using HoA except timewalking But, It's not quality bordered yet.

**Comment by frozn** [comment]
I played battle for azeroth for 3 hours at the time. :see_no_evil: So I haven't unlocked anything about the heart of azeroth.

I added a hook to GameTooltip:SetAzeriteEssence() : 

- added border color and infos for azerite essences
- added mouseover for azerite essences

Is everything working here, or is something still missing?

**Comment by hobulian** [comment]
First time it seemed to working well but have 2 problems.

First is that It worked on AzeriteEssenceUIScrollChild but didn't on AzeriteEssenceUI.~~.UnlockedState(Socket Frame).
https://imgur.com/a/4D3pEKg

Second one is quite serious problem. After clicking chat linked Azerite Essence and popping up ItemRefTooltip For azerite essence, every clicking on default UI(Except ActionBar) such as minimap, chat window, player unit frame or pet's or objective window(quest, etc..) goes broken. You cannot right or left click them, while you can click action bar or bag items or other window's clickable objectives.

**Comment by frozn** [comment]
I fixed the problem after clicking chatlink of azerite essence. Additionally I added a hook to GameTooltip:SetAzeriteEssenceSlot(). Because I haven't unlocked a slot yet, can you test if it works? 👍

**Comment by hobulian** [comment]
> I fixed the problem after clicking chatlink of azerite essence. Additionally I added a hook to GameTooltip:SetAzeriteEssenceSlot(). Because I haven't unlocked a slot yet, can you test if it works? 👍

It worked on clicking problem but I think on Azerite Slot quality border problem it's still same.

**Comment by frozn** [comment]
Strange, because "milstoneInfo.rank is used here (a few lines later): https://www.townlong-yak.com/framexml/live/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua#110

**Comment by frozn** [comment]
Works fine with actual version?

**Comment by hobulian** [comment]
Working perfect!
