### ISSUE TITLE
11.0 LUA error and wrong tooltip position

### ISSUE THREAD

**Issue by hollo6** [frozn/TipTac#303]
### Describe the bug

Getting the following LUA error on every login/reload and almost any tooltip related action:

3x TipTac/modules/ttAuras.lua:55: attempt to call method 'EnumerateInactive' (a nil value)
[string "@TipTac/modules/ttAuras.lua"]:55: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-24/LibFroznFunctions-1.0.lua"]:1175: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1448: in function `ApplyConfig'
[string "@TipTac/ttCore.lua"]:1000: in function `?'
[string "@TipTac/ttCore.lua"]:1012: in function <TipTac/ttCore.lua:1011>

Locals:
self = <table> {
 aurasPool = <table> {
 }
}
TT_CacheForFrames = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
cfg = <table> {
 nameType = "title"
 hideSpecializationAndClassText = true
 classification_elite = "+%s "
 barHeight = 6
 if_showExpansionName = true
 aurasAtBottom = true
 backdropEdgeSize = 16
 hideFactionText = true
 powerBar = false
 anchorFrameUnitPoint = "TOPLEFT"
 enableColorName = true
 barTexture = "Interface\AddOns\ShadowedUnitFrames\media\textures\Aluminium"
 healthBarClassColor = true
 t_showTalentText = true
 barFontFlags = "OUTLINE"
 classification_rare = "%s|r (Rare) "
 colorGuildByReaction = true
 barsCondenseValues = true
 optionsBottom = 332.000092
 t_talentFormat = 2
 reactColoredBackdrop = false
 classification_trivial = "~%s "
 showBattlePetTip = false
 manaBar = false
 gradientColor = <table> {
 }
 minimapConfig = <table> {
 }
 anchorFrameUnitType = "normal"
 fadeTime = 0.100000
 targetYouText = "<<YOU>>"
 tipBorderColor = <table> {
 }
 showGuildRank = true
 fontFace = "Interface\Addons\SharedMediaAdditionalFonts\fonts\calibri.ttf"
 barFontFace = "Fonts\ARIALN.TTF"
 if_showQuestLevelAndId = true
 fontSizeDelta = 2
 barFontSize = 11
 colorReactText8 = <table> {
 }
 showGuild = true
 hideWorldTips = false
 gttScale = 0.950000
 colRace = "|cffffffff"
 modifyFonts = true
 t_showTalentIcon = true
 healthBar = true
 overrideFade = true
 colorReactText7 = <table> {
 }
 preFadeTime = 0.100000
 optionsLeft = 777.999817
 reactIcon = false
 reactText = false
 showTarget = "last"
 mouseOffsetY = 10
 classColoredBorder = true
 t_showAverageItemLevel = true
 tipColor = <table> {
 }
 hideDefaultBar = true
 mouseOffsetX = 5
 healthBarText = "full"
 colLevel = "|cffc0c0c0"
 colorNameByClass = true
 classification_normal = "%s "
 if_showMountId = true
 anchorOverrideCFPoint = "BOTTOMRIGHT"
 anchorWorldTipPoint = "BOTTOMLEFT"
 reactColoredBorder = false
 if_showAuraCaster = true
 factionText = false
 t_showRoleIcon = true
 top = 1019.999878
 t_enable = true
 fontSize = 11
 enableBars = true
 anchorWorldTipType = "mouse"
 anchorFrameTipType = "mouse"
 fontSizeDeltaHeader = 1
 showBuffs = true
 gradientTip = true
 left = 245.000061
 colSameGuild = "|cffff32ff"
 auraSize = 12
 anchorWorldUnitPoint = "TOPLEFT"
 if_showItemLevelAndId = false
 classification_worldboss = "%s|r (Boss) "
 fontFlags = ""
 showPlayerGender = true
 classification_minus = "-%s "
 showMinimapIcon = false
 if_iconSize = 27
 colorNameByReaction = true
 classification_rareelite = "+%s|r (Rare) "
 anchorWorldUnitType = "normal"
 healthBarColor = <table> {
 }
 if_showSpellIdAndRank = true
 if_showItemLevel = false
 t_showTalents = true
 colorReactText10 = <table> {
 }
 if_showItemId = true
 mythicPlusDungeonScoreFormat = "both"
 colorReactText9 = <table> {
 }
 if_showAuraSpellIdAndRank = true
 anchorFrameTipPoint = "BOTTOMLEFT"
 enableColorFaction = false
}
TT_ExtendedConfig = <table> {
 tipBackdrop = <table> {
 }
 tipsToModify = <table> {
 }
 customClassColors = <table> {
 }
 oldGameTooltipTextSmall = <table> {
 }
 backdropBorderColor = <table> {
 }
 defaultAnchorType = "normal"
 tipPaddingForGameTooltip = <table> {
 }
 oldGameTooltipText = <table> {
 }
 oldGameTooltipFontsRemembered = true
 defaultAnchorPoint = "BOTTOMRIGHT"
 backdropColor = <table> {
 }
 oldGameTooltipHeaderText = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to call method 'EnumerateInactive' (a nil value)"

Also, all the tooltips moved to a random position on the right edge of the screen instead of where they should be.
I have checked the anchor settings on the GUI and also in WTF and they seem to be right, yet all the tooltips are being displayed on the right edge.

### Version of TipTac Reborn

24.05.26

### Flavor/Version of WoW

11.0

**Comment by hollo6** [comment]
I just commented all the calls in all modules that used this function and I'm no longer getting the LUA errors and the tooltips have returned to their intended place, but I have no idea what I just broke. Nothing stands out so far.

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fixed with the latest release [v24.07.25](https://github.com/frozn/TipTac/releases/tag/v24.07.25-release).
