### ISSUE TITLE
Error without functionality #3

### ISSUE THREAD

**Issue by Zasz333** [frozn/TipTac#307]
### Describe the bug

Updated to the latest version, not seeing any change to the tooltip but errors pop up. Tooltip remains default retail tooltip.

### Steps to Reproduce

No interaction happening.

### Expected behavior

I expect the addon to use my settings again.

### Additional context

3x TipTacItemRef/ttItemRef.lua:1916: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@TipTacItemRef/ttItemRef.lua"]:1916: in function `ApplyHooksToTips'
[string "@TipTacItemRef/ttItemRef.lua"]:1983: in function `HookTips'
[string "@TipTacItemRef/ttItemRef.lua"]:409: in function `?'
[string "@TipTacItemRef/ttItemRef.lua"]:360: in function <TipTacItemRef/ttItemRef.lua:360>

Locals:
(*temporary) = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 783
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 421
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 375
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 RematchGameTooltipTexture13 = RematchGameTooltipTexture13 {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 SLASH_LibQTip1 = "/qtip"
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 MasqueBlizzBars = <table> {
 }
 SLASH_STOPATTACK1 = "/stopattack"
 MAP_LEGEND_RARE_TOOLTIP = "A special creature that provides various rewards"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 NarciSoulbindsActivateButtonMixin = <table> {
 }
 EMOTE69_CMD1 = "/nosepick"
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 SPELL_FAILED_CUSTOM_ERROR_152 = "You must choose a specialization to use Ascendance."
 AutoFollowStatus = AutoFollowStatus {
 }
 ARENA_CASUAL = "Skirmish"
 STABLE_PET_ABILITIES_LIST_HEADER = "Special Abilities"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 MultiBarLeftButton11Name = MultiBarLeftButton11Name {
 }
 KEY_ABBR_PADLSTICK = "|A:Gamepad_Gen_LStickIn_32:14:14|a"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 POSTMASTER_PIPE_KALIMDOR = "Kalimdor"
 UIWidgetCenterDisplayFrameText = UIWidgetCenterDisplayFrameText {
 }
 OPTION_TOOLTIP_SHOW_ACCOUNT_ACHIEVEMENTS = "Turning this option on will only display your character achievements when people inspect you or use the Blizzard website or mobile app."
 SPIRIT_HEALER_RELEASE_RED = "|cffff2020Spirit Healer|r"
 PET_BATTLE_COMBAT_LOG_AURA_APPLIED = "%s applied %s to %s %s."
 ARTIFACT_XP_FULL = "%s is at max level."
 VOICEMACRO_8_Tr_1_FEMALE = "Cure me!"
 RAF_REMOVE_RECRUIT_CONFIRM = "Are you sure you want to remove|n|cffffd200%s|r|n from yo

### Version of TipTac Reborn

24.07.24

### Flavor/Version of WoW

Retail

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fixed with the latest release [v24.07.25](https://github.com/frozn/TipTac/releases/tag/v24.07.25-release).
