### ISSUE TITLE
Lua error when in pet battles

### ISSUE THREAD

**Issue by Rebel-Kat** [frozn/TipTac#308]
### Describe the bug

Mousing over vs battle pets at the top of the battle pet ui

### Steps to Reproduce

Mousing over the pet icons and the top of the battle pet ui when in battle

### Expected behavior

show information on battle pets

### Additional context

Still a little new at reporting this stuff, but here is the Lua

Message: Interface/AddOns/TipTacItemRef/ttItemRef.lua:3045: bad argument #1 to 'GetItemQualityColor' (outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality))
Time: Wed Jul 24 20:24:32 2024
Count: 2
Stack: Interface/AddOns/TipTacItemRef/ttItemRef.lua:3045: bad argument #1 to 'GetItemQualityColor' (outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality))
[string "=[C]"]: in function `GetItemQualityColor'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:3045: in function `battlepet'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1177: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1157>
[string "=[C]"]: ?
[string "=[C]"]: in function `PetBattleUnitTooltip_UpdateForUnit'
[string "*Blizzard_PetBattleUI.xml:355_OnEnter"]:2: in function <[string "*Blizzard_PetBattleUI.xml:355_OnEnter"]:1>
[string "=[C]"]: ?

Locals: (*temporary) = -1
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality)"

### Version of TipTac Reborn

v24.07.25-release

### Flavor/Version of WoW

retail

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.

**Comment by Rebel-Kat** [comment]
Thanks, again I am new at this, this evening I am getting this error now. I looked at the one I posted yesterday and they do seem to be different. Hoping just adding this here is ok to keep it sort of combined for the issue. The main thing I noticed is the second to last line where the number changes from 355 and 1245.

Screenshot of the avatars that I am mentioning
![Screenshot 2024-07-25 200320](https://github.com/user-attachments/assets/626d271d-e079-4fc8-83fd-ff191433bf96)

This one when mousing over the larger of the 3 pet images or avatars of the wild battle pets (if that makes sense)

Message: Interface/AddOns/TipTacItemRef/ttItemRef.lua:3056: bad argument #1 to 'GetItemQualityColor' (outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality))
Time: Thu Jul 25 19:54:24 2024
Count: 3
Stack: Interface/AddOns/TipTacItemRef/ttItemRef.lua:3056: bad argument #1 to 'GetItemQualityColor' (outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality))
[string "=[C]"]: in function `GetItemQualityColor'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:3056: in function `battlepet'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1188: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1168>
[string "=[C]"]: ?
[string "=[C]"]: in function `PetBattleUnitTooltip_UpdateForUnit'
[string "*Blizzard_PetBattleUI.xml:1245_OnEnter"]:2: in function <[string "*Blizzard_PetBattleUI.xml:1245_OnEnter"]:1>
[string "=[C]"]: ?

This one when mousing over the two smaller images or avatars of the wild battle pets (if that makes sense)

Locals: (*temporary) = -1
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality)"


Message: Interface/AddOns/TipTacItemRef/ttItemRef.lua:3056: bad argument #1 to 'GetItemQualityColor' (outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality))
Time: Thu Jul 25 19:52:44 2024
Count: 2
Stack: Interface/AddOns/TipTacItemRef/ttItemRef.lua:3056: bad argument #1 to 'GetItemQualityColor' (outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality))
[string "=[C]"]: in function `GetItemQualityColor'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:3056: in function `battlepet'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:1188: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:1168>
[string "=[C]"]: ?
[string "=[C]"]: in function `PetBattleUnitTooltip_UpdateForUnit'
[string "*Blizzard_PetBattleUI.xml:355_OnEnter"]:2: in function <[string "*Blizzard_PetBattleUI.xml:355_OnEnter"]:1>
[string "=[C]"]: ?

Locals: (*temporary) = -1
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local r, g, b, qualityString = C_Item.GetItemQualityColor(quality)"

Mousing over my battle pet images or avatars does not pop an error
Again I hope this makes sense, again being new lol

**Comment by frozn** [comment]
Everythings fine with reporting this issue. The more details I get, the better I can fix it. 😉

This error will pop up only on pets with special quality. Blizzards function `C_PetBattles.GetBreedQuality()` doesn't return wrong values any more, so my workaround is no longer needed.

The fix will be included in the next release.
