### ISSUE TITLE
[Feature request] Separate option for Colored Border/ID of transmog collection items and sets

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#31]
Like Transmog Illusions have now. For those who just want item ids but not transmog collection items or sets.

**Comment by frozn** [comment]
Transmog illusions have their own settings, because they aren't items or spells. But transmog items or sets are all some kind of "item". I think it's better here not to generate too many options.

**Comment by hobulian** [comment]
I suggest this cuz tips with icon and id sometimes hindering to see what's transmog items or set look like. So hope there just be linktype for "collection" at least. Maybe for auras also linktype for "aura".

**Comment by frozn** [comment]
The LinkTypeFuncs:xxx functions represent the different linktypes in the chatlink. Transmog collection items and other items are currently handled by their corresponding link-function (LinkTypeFuncs:item). Same for auras: Auras are spells, therefore they aren't currently handled separately from spells (LinkTypeFuncs:spell).

I would be rather uncomfortable splitting this up at the moment, as it would then no longer be consistent with the rest of the functions.

**Comment by hobulian** [comment]
What i meant was not separate LinkTypeFuncs for them but just assign their linktype as "collection" or "aura".  Still they can use item or spell linktypefunc but if they are classified as other category, users can easily setting their status in option by adding some conditions(like linktype ~= "aura") in LinkTypeFuncs.

**Comment by frozn** [comment]
I have taken a look at this: As it seems I think I can implement different settings for auras and transmog items/sets relatively uncomplicated. I will try to finish it this weekend.

**Comment by frozn** [comment]
I splitted options for auras from spells and transmog items and sets from items (committed to main-branch) . What do you think?

**Comment by hobulian** [comment]
Looks much better!

**Comment by frozn** [comment]
According to this, you would actually have to split the options...

- Show Icon Texture and Stack Count
- Smart Icon Appearance
- Borderless Icons
- Icon Size

... per linktype to have every individual option available. Seems a little bit like overkill. One solution would be to leave the last two options standalone, and make available the first two options for every linktype.

**Comment by hobulian** [comment]
Yeah. What i meant was first option for every linktype. That's all. Having all of those 4 is too much overkill.

**Comment by frozn** [comment]
I fixed the splitting auras from spells thing in main branch.

**Comment by frozn** [comment]
I moved the additional enhancements to separate issues, because when we close this issue, I want to create another release.

- Icon per link (sub) type: #40 
- Options for different actual fixed border colors, e.g. flyout, petaction, battlePetAbility, mawpower, spell: #41 
- Different border colors for auras based on type (magic, curse, disease, poison): #42

**Comment by frozn** [comment]
Is this issue resolved in your eyes? Splitting auras from spells now also ok? 😎
