### ISSUE TITLE
ttItemRef.lua:800: attempt to call global 'GetSpellBookItemInfo' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [frozn/TipTac#310]
### Describe the bug

After pre-patch, opening and mousing over an ability in the spell book causes an error to occur.

4x TipTacItemRef/ttItemRef.lua:800: attempt to call global 'GetSpellBookItemInfo' (a nil value)
[string "@TipTacItemRef/ttItemRef.lua"]:800: in function <TipTacItemRef/ttItemRef.lua:798>
[string "=[C]"]: in function `SetSpellBookItem'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:471: in function `OnIconEnter'
[string "@Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua"]:700: in function <...rd_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:699>

Locals:
self = GameTooltip {
 ItemTooltip = Frame {
 }
 AllTheThingsOnTooltipClearedHook = true
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 TopEdge = Texture {
 }
 LeftEdge = Texture {
 }
 textLeft1Font = "GameTooltipHeaderText"
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 waitingForData = false
 updateTooltipTimer = 0.190000
 TopLeftCorner = Texture {
 }
 Center = Texture {
 }
 RightEdge = Texture {
 }
 BottomEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
 supportsDataRefresh = true
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 ttCount = FontString {
 }
 backdropInfo = <table> {
 }
 CIMI_tooltipWritten = false
 ttIcon = Texture {
 }
 supportsItemComparison = true
 shoppingTooltips = <table> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 textRight1Font = "GameTooltipHeaderText"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
slot = 5
bookType = 0
(*temporary) = nil
(*temporary) = 5
(*temporary) = 0
(*temporary) = "attempt to call global 'GetSpellBookItemInfo' (a nil value)"
cfg = <table> {
 classification_normal = "%s "
 if_iconSize = 113
 classification_rare = "%s|r (Rare) "
 minimapConfig = <table> {
 }
 classification_elite = "+%s "
 left = 2370.501465
 optionsBottom = 773.500000
 targetYouText = "<<YOU>>"
 showGuildRank = true
 optionsLeft = 784.666870
 classification_worldboss = "%s|r (Boss) "
 classification_trivial = "~%s "
 classification_minus = "-%s "
 top = 85.333206
 showPlayerGender = true
 classification_rareelite = "+%s|r (Rare) "
}
tipDataAdded = <table> {
}
CustomTypeFuncs = <table> {
}

### Steps to Reproduce

Open Spell Book
Mouse over an ability.

### Expected behavior

No error.

### Version of TipTac Reborn

24.07.25

### Flavor/Version of WoW

Retail 11.0.2

**Comment by lowpita** [comment]
Im also getting this error from the same file:
``1x TipTacItemRef/ttItemRef.lua:837: attempt to call global 'HasPetSpells' (a nil value)
[string "@TipTacItemRef/ttItemRef.lua"]:837: in function <TipTacItemRef/ttItemRef.lua:814>
[string "=[C]"]: in function `SetPetAction'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:294: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:273>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:95: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:87>
[string "=[C]"]: ?

Locals:
self = GameTooltip {
 BottomLeftCorner = Texture {
 }
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 RightEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 NineSlice = Frame {
 }
 TopEdge = Texture {
 }
 LeftEdge = Texture {
 }
 textLeft1Font = "GameTooltipHeaderText"
 shouldRefreshData = false
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 shoppingTooltips = <table> {
 }
 StatusBar = GameTooltipStatusBar {
 }
 ttWorkaroundForFirstMouseoverStatus = 0
 BottomEdge = Texture {
 }
 numMoneyFrames = 1
 PixelSnapDisabled = true
 ItemTooltip = Frame {
 }
 ttIcon = Texture {
 }
 ttCount = FontString {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 supportsItemComparison = true
 supportsDataRefresh = true
 TextRight1 = GameTooltipTextRight1 {
 }
 BottomOverlay = Texture {
 }
 BottomRightCorner = Texture {
 }
 textLeft2Font = "GameTooltipText"
 TopLeftCorner = Texture {
 }
 Center = Texture {
 }
 waitingForData = false
 updateTooltipTimer = 0.065000
 textRight1Font = "GameTooltipHeaderText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 backdropInfo = <table> {
 }
}
slot = 3
name = "PET_ACTION_MOVE_TO"
texture = "PET_MOVE_TO_TEXTURE"
isToken = 1
isActive = false
autoCastAllowed = false
autoCastEnabled = false
spellID = nil
_name = "Move To"
icon = "Interface\Icons\Ability_Hunter_Pet_Goto"
(*temporary) = nil
(*temporary) = "attempt to call global 'HasPetSpells' (a nil value)"
cfg = <table> {
 if_showExpansionName = false
 showMount = true
 showMountCollected = true
 powerBar = false
 hideTipsFrameTips = false
 anchorFrameTipTypeInCombat = "mouse"
 powerBarText = "percent"
 if_iconAnchor = "CENTER"
 t_showTalentText = true
 colorLevel = <table> {
 }
 hideTipsInCombat = "fwu"
 classification_rare = "%s|r (Rare) "
 barsCondenseValues = true
 optionsBottom = 595.166931
 reactColoredBackdrop = false
 hideAllTipsInCombat = false
 classification_trivial = "%s "
 iconSize = 30
 minimapConfig = <table> {
 }
 targetYouText = "<<YOU>>"
 showGuildRank = true
 gradientTip = true
 if_modifyAchievementTips = true
 hideTips = "none"
 showCurrentUnitSpeed = false
 selfAurasOnly = false
 if_achievmentColoredBorder = true
 reactIcon = false
 showTarget = "last"
 anchorFrameTipPointInCombat = "TOPLEFT"
 if_iconOffsetX = 22
 if_showPetActionId = false
 healthBar = true
 hideTipsActionTips = false
 auraMaxRows = 4
 t_showRoleIcon = true
 anchorOverrideCFPoint = "TOPLEFT"
 enableAnchor = true
 if_iconTooltipAnchor = "TOPLEFT"
 anchorWorldTipPointInCombat = "TOPLEFT"
 iconCombat = false
 fontSize = 12
 if_stackCountToTooltip = "always"
 hideTipsInCombatFrameUnits = true
 showTargetedBy = true
 anchorFrameUnitPointInCombat = "TOPLEFT"
 anchorWorldUnitPoint = "TOPLEFT"
 classification_worldboss = "%s|r (Boss) "
 showPlayerGender = false
 showMountIcon = true
 anchorWorldTipPoint = "TOPLEFT"
 if_iconSize = 46
 iconClass = false
 auraSize = 20
 hideTipsWorldTips = false
 anchorWorldUnitPointInCombat = "TOPLEFT"
 anchorFrameTipPoint = "TOPLEFT"
 anchorFrameUnitTypeInCombat = "mouse"
 fontFace = "Interface\AddOns\ElvUI\Core\Media\Fonts\Expressway.ttf"
 hideSpecializationAndClassText = true
 classification_elite = "+%s "
 if_showCurrencyId = false
 tipBackdropEdge = "Interface\Buttons\WHITE8X8"
 aurasAtBottom = true
 backdropEdgeSize = 1
 showMountText = true
 hideFactionText = false
 anchorFrameUnitPoint = "TOPLEFT"
 barTexture = "Interface\AddOns\BigWigs\Media\Textures\Smoother"
 hideTipsWorldUnits = false
 enableColorFaction = true
 left = 2017.666260
 t_talentFormat = 2
 updateFreq = 1
 anchorOverrideCFType = "mouse"
 manaBar = true
 hidePvpText = true
 pixelPerfectBackdrop = true
 top = 291.166626
 hideTipsInCombatWorldTips = false
 barFontSize = 14
 anchorWorldUnitTypeInCombat = "mouse"
 if_showFlyoutId = false
 t_colorTalentTextByClass = true
 fontFlags = "OUTLINE"
 if_showIconId = true
 if_showExpansionIcon = false
 t_showTalentIcon = true
 iconFaction = false
 anchorFrameUnitType = "mouse"
 hideRealmText = false
 nameType = "title"
 optionsLeft = 1268.833740
 showMythicPlusDungeon``

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

Fix will be included in the next release.
