### ISSUE TITLE
Minimap icon shows up after a /reload

### ISSUE THREAD

**Issue by MaximusPM** [frozn/TipTac#311]
### Describe the bug

Even if I untick "enable minimap icon", when I do a /reload it shows up again in the minimap. Clicking it makes it go away again, and I know it's not a game breaking bug, but it's a minor annoyance. Doesn't happen upor login/relog, just after a /reload

### Steps to Reproduce

untick "Enable minimap icon", close the window, do a /reload

### Version of TipTac Reborn

24.07.25-release

### Flavor/Version of WoW

Retail (TWW pre-patch)

**Comment by frozn** [comment]
Unfortunately I can't reproduce this on my side. Did this error also occur if you disable all other addons except TipTac?

**Comment by frozn** [comment]
I could reproduce this with addon SexyMap. If SexyMap is set to always show the TipTac's minimap icon and in TipTac the minimap icon is disabled, then it is like you said.

This is two settings are conflicting each other and a fix isn't possible.
