### ISSUE TITLE
Bars (health or Mana) flashing when unit hovered is dead/OOM

### ISSUE THREAD

**Issue by Xarano-GIT** [frozn/TipTac#313]
### Describe the bug

With the TipTac Health Bars enabled and the default disabled, hovering over a unit that is dead (0 HP) or OOM will cause the bar to rapidly flash

### Steps to Reproduce

1. Kill something with tooltip bars enabled
2. Hover over dead unit
3. Observe

### Expected behavior

I would expect the bars to remain static

### Version of TipTac Reborn

v24.05.26

### Flavor/Version of WoW

Retail TWW Prepatch

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

I noticed this too, but it seems a little bit tricky to solve it. So far I don't know what causes this issue. But I'm on it...

**Comment by Spiderkeg** [comment]
I noticed this occurring if the "Show Bar for other Power Types" is checked, and you hover over a warrior, etc.  The bar blinks.  I don't know what the issue is, but you can certainly use that as a reliable way to test.

**Comment by frozn** [comment]
Repeatedly setting the bar's texture with `SetStatusBarTexture()` oddly creates this flickering. I have been able to implement a workaround to fix this.

Will be included in the next release.

**Comment by Spiderkeg** [comment]
> Repeatedly setting the bar's texture with `SetStatusBarTexture()` oddly creates this flickering. I have been able to implement a workaround to fix this.
> 
> Will be included in the next release.

I think everyone would agree just how amazing you are!
