### ISSUE TITLE
[Classic (SoD)] SpellID always show 0

### ISSUE THREAD

**Issue by Amanthuul** [frozn/TipTac#316]
### Describe the bug

SpellID: 0 on any spell

### Steps to Reproduce

1) hover over any spell
2) tooltip says SpellId: 0

### Additional context

![image](https://github.com/user-attachments/assets/648278ea-41aa-4336-8de9-6b12dbd498d0)

### Version of TipTac Reborn

since 24.07.25

### Flavor/Version of WoW

Classic SoD

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.
