### ISSUE TITLE
[Request] Add tiling toggle for background texture

### ISSUE THREAD

**Issue by Amanthuul** [frozn/TipTac#317]
### Is your feature request related to a problem? Please describe.

I use one big background texture for tooltips which doesn't need to be tiled and every time I need to change ttcore.lua:331 from tile = true, to tile = false.

Can it be just a toggle inside settings?

### Describe the solution you'd like

Toggle for BG tiling

**Comment by frozn** [comment]
I added an option for this:

![image](https://github.com/user-attachments/assets/db6450ef-dc7f-4901-a424-41b591e01268)

Will be included in the next release. 👍

**Comment by Amanthuul** [comment]
Thanks!
