### ISSUE TITLE
Error with GetQuestCurrencyInfo; apparently this has been removed

### ISSUE THREAD

**Issue by Spiderkeg** [frozn/TipTac#319]
### Describe the bug

```
3x TipTacItemRef/ttItemRef.lua:921: attempt to call global 'GetQuestCurrencyInfo' (a nil value)
[string "@TipTacItemRef/ttItemRef.lua"]:921: in function <TipTacItemRef/ttItemRef.lua:918>
[string "=[C]"]: in function `SetQuestCurrency'
[string "@Blizzard_UIPanels_Game/Mainline/QuestInfo.lua"]:1250: in function <Blizzard_UIPanels_Game/Mainline/QuestInfo.lua:1229>
```

### Steps to Reproduce

The bug popped when I turned in a quest, receiving a reward that was also a currency.  In this case, Dream Infusion.

### Additional context

According to https://warcraft.wiki.gg/wiki/Patch_11.0.0/API_changes

GetNumQuestLogRewardCurrencies
GetNumRewardCurrencies
GetQuestCurrencyInfo
GetQuestLogRewardCurrencyInfo

These have all been removed with the update.  I didn't dig too deeply into ttItemRef.lua, but likely being used.  Unfortunately, I'm not sure what the suitable replacements are.

### Version of TipTac Reborn

24.07.28

### Flavor/Version of WoW

War Within Patch, 11.0.0

**Comment by frozn** [comment]
Thanks for reporting this! 👍

These two functions have been moved:

[GetQuestCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_GetQuestCurrencyInfo) -> [C_QuestOffer.GetQuestRewardCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_C_QuestOffer.GetQuestRewardCurrencyInfo)
[GetQuestLogRewardCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_GetQuestLogRewardCurrencyInfo) -> [C_QuestLog.GetQuestRewardCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_C_QuestLog.GetQuestRewardCurrencyInfo)

I moved calling these functions to classic compatibility section of `LibFroznFunction` returning the new `QuestRewardCurrencyInfo` structure.

Fix will be included in the next release. With this, finally all changes regarding tww 11.0.0 and the upcoming patch 11.0.2 are considered in TipTac.

Phew... applying changes after releasing a new expansion is often time consuming. 🥵

**Comment by Spiderkeg** [comment]
> Thanks for reporting this! 👍
> 
> These two functions have been moved:
> 
> [GetQuestCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_GetQuestCurrencyInfo) -> [C_QuestOffer.GetQuestRewardCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_C_QuestOffer.GetQuestRewardCurrencyInfo) [GetQuestLogRewardCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_GetQuestLogRewardCurrencyInfo) -> [C_QuestLog.GetQuestRewardCurrencyInfo()](https://warcraft.wiki.gg/wiki/API_C_QuestLog.GetQuestRewardCurrencyInfo)
> 
> I moved calling these functions to classic compatibility section of `LibFroznFunction` returning the new `QuestRewardCurrencyInfo` structure.
> 
> Fix will be included in the next release. With this, finally all changes regarding tww 11.0.0 and the upcoming patch 11.0.2 are considered in TipTac.
> 
> Phew... applying changes after releasing a new expansion is often time consuming. 🥵

Well the community at large thanks you for your efforts in keeping this great addon alive.
