### ISSUE TITLE
lua error when opening mounts menu, pulling out random mount button and hovering over it

### ISSUE THREAD

**Issue by Addonman** [frozn/TipTac#322]
### Describe the bug

Message: Interface/AddOns/TipTacItemRef/ttItemRef.lua line 2699:
   bad argument #&#x2060;1 to 'UnitExists' (Usage: local result = UnitExists([unit]))
Debug:
   [string "=[C]"]: UnitExists()
   [string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:2699: spell()
   [string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:691:
      Interface/AddOns/TipTacItemRef/ttItemRef.lua:683
   [string "=[C]"]: SetMountBySpellID()
   [string "@Interface/AddOns/Blizzard_Collections/Blizzard_MountCollection.lua"]:1004:
      ...ns/Blizzard_Collections/Blizzard_MountCollection.lua:1002

### Steps to Reproduce

Opening mounts menu an dpulling out random mount button

### Expected behavior

not producing bug

### Additional context

no

### Version of TipTac Reborn

24.07.31-release

### Flavor/Version of WoW

retail

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.
