### ISSUE TITLE
Feature Request: Disable Tooltips Altogether in M+ Dungeons

### ISSUE THREAD

**Issue by s2kallday** [frozn/TipTac#326]
### Is your feature request related to a problem? Please describe.

I want to be able to have the beautiful and useful tooltips in all untimed and out of combat situations, but i'd rather not have them at all in timed content.

### Describe the solution you'd like

Either a Seperate timer for Fading in instanced content or just the ability to toggle it off in instanced content altogether.

### Describe alternatives you've considered

There aren't many decent tooltip alternatives outside of ELVui so i'd probably go back to basic blizzard tips.`

### Additional context

None really =)

**Comment by frozn** [comment]
Seems like a good idea to implement this feature. Will be included in the next release! 👍
