### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ciolouse** [frozn/TipTac#33]
I get this error while playing :

`1x [ADDON_ACTION_BLOCKED] L'AddOn 'TipTac' a tenté d'appeler la fonction protégée 'MultiBarRightButton10:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>`

**Comment by frozn** [comment]
probably same problem as #32

**Comment by frozn** [comment]
In which situations do you get this error? Does this also occur if you have disabled all addons except TipTac (TipTac, TipTacItemRef, TipTacOptions, TipTacTalents)?

**Comment by frozn** [comment]
This is only a shot in the dark, but can you test with this development build?

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/7954064/TipTac-dev.zip)

**Comment by Ciolouse** [comment]
I get this error when entering in fight, I'll test your dev build, thanks !

**Comment by Ciolouse** [comment]
I do have this error with dev build : 

`1x [ADDON_ACTION_BLOCKED] L'AddOn 'TipTac' a tenté d'appeler la fonction protégée 'ActionButton10:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>`

**Comment by frozn** [comment]
Fixed with release [v22.03.30](https://github.com/frozn/TipTac/releases/tag/v22.03.30).
