### ISSUE TITLE
Lua Error: Cannot find a library instance of "LibDropDownMenu"

### ISSUE THREAD

**Issue by BlueNightSky** [frozn/TipTac#337]
### Describe the bug

1x TipTac/ttCore.lua:613: Cannot find a library instance of "LibDropDownMenu".
[string "=[C]"]: in function `error'
[string "@!Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@TipTac/ttCore.lua"]:613: in function <TipTac/ttCore.lua:528>
[string "@TipTac/ttCore.lua"]:1678: in function `fn'
[string "@TipTac/libs/LibFroznFunctions-1.0-31/LibFroznFunctions-1.0.lua"]:1272: in function `CallFunctionDelayed'
[string "@TipTac/ttCore.lua"]:1677: in function `ResolveTipsToModify'
[string "@TipTac/ttCore.lua"]:1566: in function `ApplyConfig'
[string "@TipTac/ttCore.lua"]:1106: in function `?'
[string "@TipTac/ttCore.lua"]:1118: in function <TipTac/ttCore.lua:1117>

Locals:
(*temporary) = "Cannot find a library instance of "LibDropDownMenu"."

### Version of TipTac Reborn

v24.08.25

### Flavor/Version of WoW

11.02.56311

**Comment by frozn** [comment]
Thanks for reporting this! I haven't seen it... 🙈

Fix will be included in the next release.
