### ISSUE TITLE
Context menu is not on cursor since update

### ISSUE THREAD

**Issue by ianv88** [frozn/TipTac#338]
### Describe the bug

After the update from 08.19 to 08.25 the standard context menu is anchored on the left side of the screen.
![grafik](https://github.com/user-attachments/assets/db07fb25-07bc-4808-a30a-ec7341b61352)
![grafik](https://github.com/user-attachments/assets/f47f7a1f-01c1-44fa-adad-41b857a98f78)

I play classic SOD

Thank you for you app :)

### Steps to Reproduce

Change the Version or disable the addon

### Expected behavior

first picture

### Version of TipTac Reborn

24.08.25 and 26. Works with 19

### Flavor/Version of WoW

Season of Discovery

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.
