### ISSUE TITLE
Can't set tooltip come out only for <mouse over>

### ISSUE THREAD

**Issue by DeadlyPewPeww** [frozn/TipTac#340]
### Describe the bug

![1](https://github.com/user-attachments/assets/a1f51689-67fa-4743-8168-524f45eb1f89)
![2](https://github.com/user-attachments/assets/8c6d1eec-65ca-414c-9ab2-6923f1117577)

### Version of TipTac Reborn

V24.08.26

### Flavor/Version of WoW

v11

**Comment by frozn** [comment]
You need to disable the following setting in WoW options:

![image](https://github.com/user-attachments/assets/0df58f3f-7ed4-43a9-aed9-269b7af92045)

With this setting on, a tooltip will be triggered if changing targets by pressing tab or soft targeting ("Gameplay->Combat->Enable Action Targeting" is enabled) without hovering over with your mouse.

The duration of the tooltip can be adjusted with chat command `/run SetCVar("SoftTargetTooltipDurationMs", x)` with `x = duration in ms (default: 2000)`.
