### ISSUE TITLE
Error pops when opening ElvUI minimap menu

### ISSUE THREAD

**Issue by bl4kd3th** [frozn/TipTac#341]
### Describe the bug

Error thrown and minimap menu doesn't open.

29x TipTac/ttCore.lua:751: attempt to perform arithmetic on global 'Offset' (a nil value)
[string "@TipTac/ttCore.lua"]:751: in function <TipTac/ttCore.lua:607>
[string "@TipTac/ttCore.lua"]:760: in function <TipTac/ttCore.lua:758>
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@Blizzard_FrameXML/EasyMenu.lua"]:22: in function `EasyMenu'
[string "@ElvUI/Core/General/API.lua"]:1009: in function `ComplicatedMenu'
[string "@ElvUI/Core/Modules/Maps/Minimap.lua"]:268: in function <ElvUI/Core/Modules/Maps/Minimap.lua:258>

Locals:
prefixName = "DropDownList"
level = 1
dropDownFrame = MinimapRightClickMenu {
 BottomLeftCorner = Texture {
 }
 Right = MinimapRightClickMenuRight {
 }
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 Middle = MinimapRightClickMenuMiddle {
 }
 template = "Transparent"
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 menuList = <table> {
 }
 PixelSnapDisabled = true
 displayMode = "MENU"
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 Icon = MinimapRightClickMenuIcon {
 }
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 Center = Texture {
 }
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 RightEdge = Texture {
 }
 0 = <userdata>
 TopEdge = Texture {
 }
 Text = MinimapRightClickMenuText {
 }
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 Left = MinimapRightClickMenuLeft {
 }
 BottomRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 Button = MinimapRightClickMenuButton {
 }
 initialize = <function> defined @Blizzard_FrameXML/EasyMenu.lua:25
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 TopRightCorner = Texture {
 }
}
anchorName = "cursor"
xOffset = 1834.166610
yOffset = 1095.000101
_level = 1
tip = DropDownList1 {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 template = "Default"
 ApplyBackdrop = <function> defined =[C]:-1
 SetBackdrop = <function> defined =[C]:-1
 ClearBackdrop = <function> defined =[C]:-1
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 PixelSnapDisabled = true
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 numButtons = 16
 SetScale = <function> defined =[C]:-1
 Center = Texture {
 }
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 0 = <userdata>
 BottomEdge = Texture {
 }
 TopEdge = Texture {
 }
 isSkinned = true
 BottomRightCorner = Texture {
 }
 maxWidth = 140.833359
 backdropInfo = <table> {
 }
 dropdown = MinimapRightClickMenu {
 }
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 shouldRefresh = true
}
frameParams = <table> {
 originalBottomOffsetForPreventingOffScreen = 0
 frameName = "DropDownList1"
 originalLeft

### Steps to Reproduce

1: with ElvUI enabled, middle-mouse-button click on minimap
2: see error in bugsack

### Expected behavior

expecting to see the popup menu at cursor

### Additional context

Offset variable doesn't exist, tried changing it to xOffset on line 751 and the menu did pop up but it wasn't relative to cursor, it was inversely relative to my tooltip anchor.

### Version of TipTac Reborn

24.08.28

### Flavor/Version of WoW

Cata Classic

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.
