### ISSUE TITLE
Player context menu overflows window border

### ISSUE THREAD

**Issue by LemonKnight** [frozn/TipTac#343]
### Describe the bug

When the chat is at the bottom of your screen/window and you right click on a name in the chat, the menu overflows the border and becomes unusable.

![image](https://github.com/user-attachments/assets/fdd8b492-bcf1-47ab-982b-8e8cfd4e8f8e)

Tested in Windowed/Windowed (Fullscreen).

### Steps to Reproduce

1. setup chatbox at the bottom of the screen
2. right click playername in chatbox

### Expected behavior

the menu should not overflow the window/screen and be fully visible on screen.

example with tiptac not loaded:
![image](https://github.com/user-attachments/assets/1fc42f80-2811-487e-a558-48f25794b30a)

### Version of TipTac Reborn

24.08.28

### Flavor/Version of WoW

WoW Classic SoD - 1.15.3

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.
