### ISSUE TITLE
Tooltip scale bug.

### ISSUE THREAD

**Issue by mwmadify** [frozn/TipTac#347]
### Describe the bug

This bug only appears while playing a hunter. If my tooltip scale in TipTac is not 1.15 or higher the hunter foldout menu for tracking opens to the right and thereby outside of the screen. This is with default minimap.
![Scale 1 1](https://github.com/user-attachments/assets/518bfe49-b643-4e77-b594-7abc31eaae3d)
![Scale 1 15](https://github.com/user-attachments/assets/cb5153f8-1f07-42f8-8a2e-f40ac7d3fbb2)

### Version of TipTac Reborn

24.08.29

### Flavor/Version of WoW

4.4.0

**Comment by mwmadify** [comment]
Seems to be related to UI scale. Mine is at 80%.

**Comment by frozn** [comment]
Your're right, thanks for reporting! 👍

Fixed with the latest release.
