### ISSUE TITLE
Backdrop settings changes not saving

### ISSUE THREAD

**Issue by jmdaku** [frozn/TipTac#349]
### Describe the bug

My backdrop settings are currently not enabled. If I do enable them by selecting the checkmark in the menu and changing the settings within that section, my tooltips do change. But as soon as I reload or log out and back in, the changes reset and my border settings are disabled again.
The color settings within the border menu have saved. It's just the initial checkmark to enable the menu, the background texture and border texture that reset over and over.

### Steps to Reproduce

Steps to reproduce:
1. Have backdrop unselected in the main TipTac menu.
2. Check the box to enable editing the backdrop
3. Change the background texture and border texture
4. Mouseover something and see the changes
5. Use /reload or /rl
6. Open the menu at /tiptac and it will be back to the settings at step #&#8203;1

### Expected behavior

The settings should save upon logout or reload.

### Version of TipTac Reborn

24.09.02

### Flavor/Version of WoW

11.0.2

**Comment by frozn** [comment]
Unfortunately I can't reproduce this behavior. Can you upload your settings (`\World of Warcraft\_retail_\WTF\Account\<your account>\SavedVariables\TipTac.lua`) here in this ticket to further analyze this?

**Comment by jmdaku** [comment]
[TipTac.lua.txt](https://github.com/user-attachments/files/16931645/TipTac.lua.txt)

GitHub didn't like attaching it as a .lua for some reason.

**Comment by frozn** [comment]
I tested it with your settings file, but enabling the backdrop checkbox and reloading the ui works as expected. The checkbox for enabling the backdrop stays in place, and also if I disabled it afterwards including a reload.

Or maybe your installation of TipTac is corrupt. To eliminate this possibility, we should apply a clean install of TipTac by deleting the 4 folders `TipTac`, `TipTacItemRef`, `TipTacOptions` and `TipTacTalents` under folder `\World of Warcraft\_retail_\Interface\AddOns`, manually downloading the latest release [here](https://github.com/frozn/TipTac/releases) (TipTac-vxx.xx.xx-release.zip) and extracting this file to `\World of Warcraft\_retail_\Interface\AddOns`.

**Comment by jmdaku** [comment]
I deleted all 4 addon 4 folders and reinstalled manually and the issue still occurs. I even then fully uninstalled including clearing all settings and reinstalled and it still occurs. I suspect it might be a conflict with some other addon or something else on my end.

**Comment by frozn** [comment]
Maybe try disabling all other addons except TipTac and check if the error still occurs.

**Comment by jmdaku** [comment]
I disabled all other addons and TipTac's settings then save correctly. After enabling and disabling a bunch, I have it narrowed down to Skinner as the conflict. Even with no tooltip-related settings enabled, it breaks TipTac.

**Comment by frozn** [comment]
Skinner also styles the tooltips including TipTac's config frame, see `\Skinner\AddonSkins\TipTac.lua`. The following TipTac backdrop options will be disabled by Skinner:

![image](https://github.com/user-attachments/assets/39b6f2cc-22c0-4b5c-845f-c5ee0e2e5be6)

The following actions need to be applied in order to prevent this and use TipTac's backdrop again:

1. Disable TipTac module in Skinner by commenting out this line in `\Skinner\AddonSkins\_AddonSkins.xml`:
![image](https://github.com/user-attachments/assets/215ec701-b90b-4f01-ae2c-103fe060df75)

2. Disable "Skinner->UI Frames->Unit Popups" in Skinner's options.

**Comment by jmdaku** [comment]
I commented out that line and disabled "Unit Popups" in the in game Skinner options. My tooltip settings now do persist through a reload and TipTac's backdrop settings aren't switching back to disabled. It's using Skinner's border settings but I can live with that. Thank you for all of your help!
