### ISSUE TITLE
Hiding in combat do not work on mm+

### ISSUE THREAD

**Issue by Barruchou** [frozn/TipTac#353]
### Describe the bug

The feature to hide tooltips during combat doesn't seem to work within Mythic dungeons.
That being said, the tooltips do hide properly in the open world and in raids

### Steps to Reproduce

Enable, for example, hiding spell tooltips during combat
Enter a dungeon
Engage a combat
The tooltips are still displayed

### Expected behavior

The tooltips should be hidden during any combat in any zone.

### Version of TipTac Reborn

24.09.02

### Flavor/Version of WoW

Retail - 11.0.2

**Comment by frozn** [comment]
Several tooltips during combat in raid or mythic+ are sometimes protected by the game client and interaction with them by any addons are forbidden at this time. E.g. calling `Hide()` for this temporary protected tooltips isn't possible.

I'm unshure how to deal with this topic. I could extend the tooltips in TipTac's options to describe this behavior, or I could show something on-screen if tooltip interaction is currently forbidden.

**Comment by Barruchou** [comment]
Ok thanks for the answer but it's strange because it works well in raid 🤔

**Comment by frozn** [comment]
Ah, maybe you haven't checked the section "Hiding->Hide Tips During Challenge Mode". Haven't thought about it that it has been introduced with v24.08.18. 🙂

**Comment by Barruchou** [comment]
Yes it works now, thanks 😋
