### ISSUE TITLE
Lua error on mouse over of pet action bar.

### ISSUE THREAD

**Issue by Odaxis** [frozn/TipTac#354]
### Describe the bug

Getting this error on Classic Season on a hunter when ever i Mouse over one of my pets active abilities on the pet bar.

Message: bad argument #&#x2060;1 to '?' (Usage: local mountID = C_MountJournal.GetMountFromSpell(spellID))
Time: Sun Sep 29 00:19:21 2024
Count: 24
Stack: bad argument #&#x2060;1 to '?' (Usage: local mountID = C_MountJournal.GetMountFromSpell(spellID))
[string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:471: in function `GetMountFromSpell'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:2697: in function `spell'
[string "@Interface/AddOns/TipTacItemRef/ttItemRef.lua"]:834: in function <Interface/AddOns/TipTacItemRef/ttItemRef.lua:824>
[string "=[C]"]: in function `SetPetAction'
[string "@Interface/AddOns/Blizzard_ActionBar/Classic/PetActionBarFrame.lua"]:423: in function `PetActionButton_OnEnter'
[string "*PetActionBarFrame.xml:59_OnEnter"]:1: in function <[string "*PetActionBarFrame.xml:59_OnEnter"]:1>

Locals: self = <table> {
 hasWoWFlavor = <table> {
 }
 TableRegistry = <table> {
 }
 isWoWFlavor = <table> {
 }
}
spellID = nil

### Steps to Reproduce

Mouse over one of my pets active abilities on the pet bar.

### Version of TipTac Reborn

TipTac 24.09.02

### Flavor/Version of WoW

Wow 1.15.4

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fix will be included in the next release.
