### ISSUE TITLE
game crash after installed v24.09.29

### ISSUE THREAD

**Issue by Iambookz** [frozn/TipTac#355]
### Describe the bug

1x [ADDON_ACTION_FORBIDDEN] 插件 'TipTac' 嘗試調用保護功能 'CameraOrSelectOrMoveStart()'。
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CameraOrSelectOrMoveStart'
[string "CAMERAORSELECTORMOVE"]:2: in function <[string "CAMERAORSELECTORMOVE"]:1>
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellSubtext'
[string "@TipTac/libs/LibFroznFunctions-1.0-34/LibFroznFunctions-1.0.lua"]:606: in function `GetSpellSubtext'
[string "@TipTacItemRef/ttItemRef.lua"]:2682: in function `spell'
[string "@TipTacItemRef/ttItemRef.lua"]:648: in function <TipTacItemRef/ttItemRef.lua:639>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetUnitBuff'
[string "@ZPerl/ZPerl.lua"]:2607: in function `XPerl_TooltipSetUnitBuff'
[string "@ZPerl_PlayerBuffs/ZPerl_PlayerBuffs.lua"]:338: in function <...rfaceZPerl_PlayerBuffs/ZPerl_PlayerBuffs.lua:327>
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellSubtext'
[string "@TipTac/libs/LibFroznFunctions-1.0-34/LibFroznFunctions-1.0.lua"]:606: in function `GetSpellSubtext'
[string "@TipTacItemRef/ttItemRef.lua"]:2682: in function `spell'
[string "@TipTacItemRef/ttItemRef.lua"]:648: in function <TipTacItemRef/ttItemRef.lua:639>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetUnitBuff'
[string "@ZPerl/ZPerl.lua"]:2607: in function `XPerl_TooltipSetUnitBuff'
[string "@ZPerl_PlayerBuffs/ZPerl_PlayerBuffs.lua"]:338: in function <...rfaceZPerl_PlayerBuffs/ZPerl_PlayerBuffs.lua:327>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

### Version of TipTac Reborn

v24.09.29

### Flavor/Version of WoW

ERA

**Comment by frozn** [comment]
I added a workaround until it's fixed on blizzards side. Pushed out a new release for this.

**Comment by Iambookz** [comment]
issue cleared. v24.09.30.. thank you so much.

**Comment by skyler-code** [comment]
This issue also exists on the Cataclysm PTR. The fix in https://github.com/frozn/TipTac/commit/cf9eed6fb85b1bccc29b5a0cf569c03faef5a812 applies there as well.

**Comment by frozn** [comment]
Thanks, good to know. The workaround I added is currently only active in classic era. I would add this workaround for CataC if the error later would hit the live servers, if it hasn't been fixed until then.
