### ISSUE TITLE
Offset for mouseover

### ISSUE THREAD

**Issue by Kingpatzer** [frozn/TipTac#358]
### Is your feature request related to a problem? Please describe.

I would like to be able to more clearly see what I'm mousing over when getting a tooltip,

### Describe the solution you'd like

I'd like to be able to set the mouse anchor with an x,y offset from the mouse rather than anchoring at the mouse

### Additional context

This is how EvlUI tooltip works for reference.

**Comment by frozn** [comment]
It's already there:

![image](https://github.com/user-attachments/assets/b1094103-8c56-4e21-8d5c-4f73b56fbe2d)

😉
