### ISSUE TITLE
Usage: local name, hyperlink, sourceText = C_TransmogCollection.GetIllusionStrings(illusionID)

### ISSUE THREAD

**Issue by Ookami313** [frozn/TipTac#38]
Was crafting some old patterns for transmog and when I went to look at the item in the Dressing Room Panel if I moused over an item in the new item list panel attached to the dressing room, I would receive the following error. Thanks.

8x Usage: local name, hyperlink, sourceText = C_TransmogCollection.GetIllusionStrings(illusionID)
[string "=[C]"]: in function `GetIllusionStrings'
[string "@TipTacItemRef\ttItemRef.lua"]:946: in function <TipTacItemRef\ttItemRef.lua:932>
[string "=[C]"]: ?

Locals:
(*temporary) = "Usage: local name, hyperlink, sourceText = C_TransmogCollection.GetIllusionStrings(illusionID)"

**Comment by frozn** [comment]
Thanks for reporting this. Fixed in main branch. Here's the actual development version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/7965860/TipTac-dev.zip)

Everything's fine with this version?

**Comment by Ookami313** [comment]
Sorry, initially missed the update. Yea, so far it looks like the dev version fixed the issue, no errors at this point in time. I'll post again if they start up again. Thanks.

**Comment by frozn** [comment]
Thanks for your feedback! 👍
