### ISSUE TITLE
retails issues related errors and border issues

### ISSUE THREAD

**Issue by k1ck3r** [frozn/TipTac#4]
Hey fronz,

first of all, thanks for all your effort!

This error is quite consistent - on every login, once get out of combat, and hover something. I've tried your new version as well, nothing changed, BUT now i'm able to skin the tooltip using some other way - creating an overlay trigger - otherwise:

- styling doesn't work at all, i can't even set  the background to a solid color
- the most annoying thing is the border (!) can't do anything with it.
- what i've tried (so i can provide some descent checks before reporting:
   - 0 addons - 0 configuration - only TT
   - installed the game on a different location/disk - only TT - no result whatsoever
   - at this point i've thought "it might be my pc" and installed the game on my work laptop. same was done through my wife's account. Nothing really can be done via TT - Even changing the size/style of the tooltip's text makes my pc (and my wife's!) to stutter for few seconds

````
7x ...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:870: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:870: in function `GarrisonLandingPageReportMission_OnEnter'
[string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:828: in function `GarrisonLandingPageReportList_UpdateMouseOverTooltip'
[string "@Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua"]:281: in function <...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:281>
[string "=[C]"]: ?

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:12
 textLeft1Font = "GameTooltipHeaderText"
 SetAction = <function> defined =[C]:-1.
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 hasMoney = 1
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
 BottomOverlay = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 updateTooltipTimer = 0.072000
 HasBackdropInfo = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:18
 ClearLines = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 SetupTextureCoordinates = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:16
 comparing = false
 SetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:27
 ClearBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:34
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 default = 1
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetQuestItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 waitingForData = false
 FadeOut = <function> defined @TipTac\ttCore.lua:877
 numMoneyFrames = 1
 ApplyBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:22
 PixelSnapDisabled = true
 SetRecipeReagentItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = GameTooltipTextLeft1 {
 }
 Show = <function> defined =[C]:-1
 GetBackdrop = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:19
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:13
 SetUnitBuff = <function> defined =[C]:-1
 GetBackdropCoordValue = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:15
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
 textRight1Font = "GameTooltipHeaderText"
 ttIcon = <unnamed> {
 }
 GetEdgeSize = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:14
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 ttGradient = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 SetUnitAura = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:17
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 ttCount = <unnamed> {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
(*temporary) = "LEFT"
(*temporary) = GarrisonLandingPageReportListListScrollFrameButton2 {
 EncounterIcon = <unnamed> {
 }
 MissionTypeIcon = <unnamed> {
 }
 id = 3
 Rewards = <table> {
 }
 BG = <unnamed> {
 }
 MissionType = <unnamed> {
 }
 0 = <userdata>
 Title = <unnamed> {
 }
 Reward2 = <unnamed> {
 }
 Status = <unnamed> {
 }
 Reward3 = <unnamed> {
 }
 TimeLeft = <unnamed> {
 }
 Reward1 = <unnamed> {
 }
}
(*temporary) = "RIGHT"
(*temporary) = 0
(*temporary) = 0
````

@alphabitnz wow, i'm really impressed by your remark on _how i should open new issue_. You've literally replied with my huge error log just to say this. Let me just "suggest" you "silently".. i've tagged in your message, tho if think i should just fuckoff, well close the god damn ticket _**silently**_ and make me shutup. Stand your side, you if you play "nice homie" by just "go open ur issue somewhere else" just  looks, well you decide - i don't care.

**Comment by alphabitnz** [comment]
> @alphabitnz wow, i'm really impressed by your remark on _how i should open new issue_. You've literally replied with my huge error log just to say this. Let me just "suggest" you "silently".. i've tagged in your message, tho if think i should just fuckoff, well close the god damn ticket _**silently**_ and make me shutup. Stand your side, you if you play "nice homie" by just "go open ur issue somewhere else" just looks, well you decide - i don't care.

Hey man, you will see I closed the issue 2 days ago without any comment.
Just didn't want my ticket dragging on & getting notifications as etiquette is to log new issues as new tickets.
Sorry that it included your whole post, that was not at all intentional but this attitude is not at all necessary.

**Comment by frozn** [comment]
Unfortunately I can't reproduce your errors with the function SetPoint(). In the bug tracker on CurseForge I have seen that other people also have these problems. I build a possible fix, because I think it's the missing ClearAllPoints() before using SetPoint().

Can you do a test with this?

[possible_fix.zip](https://github.com/frozn/TipTac/files/7657025/possible_fix.zip)

**Comment by frozn** [comment]
I added it in the actual version as a "shot in the dark": [v21.12.20](https://github.com/frozn/TipTac/releases/tag/v21.12.20)

**Comment by k1ck3r** [comment]
Wasn't able to reply sooner. Actually this version fixes many issues!!! 
But some are still at large - eg. tooltips are widened when hovering WorldQuestTracker's icon on world/zone map. The thing which mostly bothers me is, when hovering ANY trooper/follower from the garrison's UI - the tooltip starts to flicker for 3-4 seconds, then stops. If i found any reasonable errors will post them in a new issue. Thank you very much for your work!!!

Bazooka and Broker_everything had their issues, but i don't care for those two to be honest.

**Comment by k1ck3r** [comment]
Below is a small video of the above issue

https://imgur.com/vn3unYT

There isn't any errors from Bugsack, when this appears.
Not sure why i closed the issue, i may auto-clicked. Feel free to close it again.

**Comment by k1ck3r** [comment]
Ok, i'm a bit stupid, just saw the new issue which describes precisely this issue ;)
