### ISSUE TITLE
[Feature request] Adding Reward ID info for quests.

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#44]
Now, tiptac only shows quest id info of quest tips that has embedded items.
Hope it will also shows reward id someday like SC
https://cdn.imweb.me/upload/S201903225c9441f9db892/c342b6297d7e1.jpg

**Comment by frozn** [comment]
In the current release I added the item/spell/currency id to embedded tooltips.

Looks fine to you, too? :monocle_face:

**Comment by hobulian** [comment]
Played about 10mins but seemed fine. Will check it more today :)

**Comment by frozn** [comment]
And? 😉

**Comment by hobulian** [comment]
Oh sorry. There was no issue until now. Think it's working fine.

**Comment by frozn** [comment]
Perfect!
