### ISSUE TITLE
[Bug] DropDownList styling is overlapped with ELV UI's styling.

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#45]
https://imgur.com/a/cQxjvjM

I think recently added styling is somehow darker than other tips

"DropDownList1MenuBackdrop",
"DropDownList2MenuBackdrop",
I think they are overlapped with ELV UI's style for them so it's double back grounded.

Hope there be some options for user's preference for these tips maybe.

**Comment by frozn** [comment]
I fixed this issue. The locking feature to prevent backdrop changes hasn't been applied to the frames. Seems fine now. Do you agree?

**Comment by hobulian** [comment]
Agreed!

**Comment by frozn** [comment]
Faster than light responses... nice! 😎👍

**Comment by hobulian** [comment]
Hmm has problem with this again
https://imgur.com/a/JCvJ6I8
Sometimes tiptac border seems dimmed and sometimes not. Reloading causes this problem. Think it's priority problem between addons.

**Comment by frozn** [comment]
Hm, can't reproduce it with ElvUI installed, even after multiple /reload ... :thinking:

**Comment by hobulian** [comment]
Oh.. I think it was not elv. 
It was Windtools, Addon using with Elv(https://www.curseforge.com/wow/addons/elvui-windtools) causes problem.
When I use Windtool's skinning shadow function 
https://imgur.com/a/XQ8tI7a
It sometimes causes problem.

**Comment by frozn** [comment]
This is out of TipTacs scope. ElvUI_WindTools creates a new shadow frame at the original frame (frame.shadow) and sets it the following way:

```
    local shadow = CreateFrame("Frame", nil, frame, "BackdropTemplate")
    shadow:SetFrameStrata(frame:GetFrameStrata())
    shadow:SetFrameLevel(frame:GetFrameLevel() or 1)
    shadow:SetOutside(frame, size, size)
    shadow:SetBackdrop({edgeFile = LSM:Fetch("border", "ElvUI GlowBorder"), edgeSize = size + 1})
    shadow:SetBackdropColor(r, g, b, 0)
    shadow:SetBackdropBorderColor(r, g, b, 0.618)
```

The frame strata and level is the same, so it's random which frame is in front. In my opinion, the following adjustment in ElvUI_WindTools is needed:

```
    local shadowFrameLevel = 1
    if frame:GetFrameLevel() then
        shadowFrameLevel = frame:GetFrameLevel() - 1
        if shadowFrameLevel < 0 then
            shadowFrameLevel = 0
        end
    end
    shadow:SetFrameLevel(shadowFrameLevel)
```

**Comment by hobulian** [comment]
WOW. That was quite a lot of help. Will tell WindTool's author about this. Thanks

**Comment by frozn** [comment]
np 😉
