### ISSUE TITLE
Item Comparison tooltip flickering and border problem

### ISSUE THREAD

**Issue by tstlssk** [frozn/TipTac#5]
Hello! Big fan of your fixed Tiptac, Thanks a lot.

My client version is 9.1.5, 41488.

1. Flickering Item comparison tooltip
Whenever I press [shift] to compare gear, item comparison tooltip is flickering and overlepped with main tooltip.
My current anchor setting is 'mouse bottom', left anchor'

2. Border Texture does not change at all
Under Backdrop option, there's dropdown menu for changing border texture, but it does not work.
Also, Backdrop edge size is not configurable.

Thanks again for your effort to keep this up. You're a real life saver.

**Comment by frozn** [comment]
Thanks for reporting this. Both issues fixed with [v21.12.22](https://github.com/frozn/TipTac/releases/tag/v21.12.22).

**Comment by tstlssk** [comment]
Thanks for super fast fix!

I'll try new version as soon as possible.

**Comment by tstlssk** [comment]
I just tested new version and it's perfect.
Thanks a lot!
