### ISSUE TITLE
Right Click Menu Style Temporarily Missing

### ISSUE THREAD

**Issue by Amatyr** [frozn/TipTac#51]
After the last update, my right click menus look like this:

![image](https://user-images.githubusercontent.com/13810860/152848031-666a56d4-0c26-4541-b18d-8fc0df0113db.png)

Until I do a /tiptac and then just press close to get them to look like this.

![image](https://user-images.githubusercontent.com/13810860/152848134-3863ebae-e9d5-4d3c-b8b6-2f715f805a89.png)

This happens every time I log onto a character.

**Comment by frozn** [comment]
In the last update I included the styling of DropDownList1. This is the one from the screenshot. But on my side everything works fine.

Perhaps it has something to do in combination with other addons. The blue arrows for example: Which addon sets this style?

**Comment by Amatyr** [comment]
I think that's probably coming from ElvUI's menus.

**Comment by frozn** [comment]
I could reproduce it under BCC with ElvUI enabled. Fixed it in the development version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8027896/TipTac-dev.zip)

Is it working fine for you with this dev version?

**Comment by Amatyr** [comment]
Dev version has fixed it for me.

**Comment by frozn** [comment]
That are good news! 👍
