### ISSUE TITLE
conduit link error

### ISSUE THREAD

**Issue by kwonjt2001** [frozn/TipTac#56]
An error seems to appear when you mouse over a link to a conduit other than your own. For example, when hovering over a Death Knight Conduit link with a Druid, an error occurred. Attach a screenshot
![마우스 오버 오류](https://user-images.githubusercontent.com/98691652/153648587-6fc6da15-2b42-49e2-afb1-c4058f844464.jpg)

**Comment by frozn** [comment]
Hey, you're right. Conduit collection data with item level is only available for own conduits. Fixed it in the current dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8051045/TipTac-dev.zip)

**Comment by kwonjt2001** [comment]
Thank you for always!
