### ISSUE TITLE
Mousing over currency causes an error to occur.

### ISSUE THREAD

**Issue by Ookami313** [frozn/TipTac#58]
Mousing over the Sightless Eye currency within the crafting frame (was looking up missing patters and where to find them) I received the following error. Thanks.

3x TipTacItemRef\ttItemRef.lua:2112: Usage: local isCurrencyContainer = C_CurrencyInfo.IsCurrencyContainer(currencyID, quantity)
[string "=[C]"]: in function `IsCurrencyContainer'
[string "@TipTacItemRef\ttItemRef.lua"]:2112: in function `?'
[string "@TipTacItemRef\ttItemRef.lua"]:451: in function `SetHyperlink_Hook'
[string "@TipTacItemRef\ttItemRef.lua"]:1327: in function <TipTacItemRef\ttItemRef.lua:1326>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@FrameXML\UIPanelTemplates.lua"]:276: in function <FrameXML\UIPanelTemplates.lua:272>

Locals:
(*temporary) = "1149"
(*temporary) = nil

**Comment by frozn** [comment]
I was able to reproduce this error. I fixed it in the current dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8064426/TipTac-dev.zip)

Works fine for you, too?

**Comment by Ookami313** [comment]
Looks good. No issues from what I can see, Thanks.
