### ISSUE TITLE
Please inquire about MawPowerID.

### ISSUE THREAD

**Issue by kwonjt2001** [frozn/TipTac#61]
Hello. I write because I have a question.
Other buffs are fine, but only the battle cry (spellID 6673) is displayed with MawPowerID and the border is expressed in gray. Did you mean by any chance?
![전투의 외침](https://user-images.githubusercontent.com/98691652/154993985-94051f6a-06e8-43aa-bcfd-4ff756861a7a.jpg)

**Comment by frozn** [comment]
Strange... I think it's probably an internal blizzard bug. The function GetMawPowerLinkBySpellID() returns mawPowerID 1453 for battle shout with spellID 6673, which doesn't exist in table MawPower (from https://wow.tools/dbc/?dbc=mawpower).

I added a workaround to check the determined mawPowerID from spellID against the table MawPower. Here's the current dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8111627/TipTac-dev.zip)

Works fine for you, too?

**Comment by kwonjt2001** [comment]
That's great too! Thank you every time.
