### ISSUE TITLE
Multiple ADDON_ACTION_BLOCKED errors.

### ISSUE THREAD

**Issue by Ookami313** [frozn/TipTac#62]
Unsure what is causing these, if it's something with TipTac itself, Blizz changed a variable, or it's an issue with another addon I'm using, but over the last week I've compiled a large list of Blocked errors that have occurred. Most of these seem to pop up while in combat if that helps with investigating them. I tried to remove any duplicates, but one may have been left in. Thanks.

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton3:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\OverrideActionBar.lua"]:225: in function `OverrideActionBar_Setup'
[string "@FrameXML\OverrideActionBar.lua"]:115: in function `OverrideActionBar_UpdateSkin'
[string "@FrameXML\ActionBarController.lua"]:115: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'MultiBarBottomRightButton2:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton2:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\OverrideActionBar.lua"]:225: in function `OverrideActionBar_Setup'
[string "@FrameXML\OverrideActionBar.lua"]:118: in function `OverrideActionBar_UpdateSkin'
[string "@FrameXML\ActionBarController.lua"]:115: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton6:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:760: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:218: in function <FrameXML\ActionButton.lua:215>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton1:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\OverrideActionBar.lua"]:225: in function `OverrideActionBar_Setup'
[string "@FrameXML\OverrideActionBar.lua"]:115: in function `OverrideActionBar_UpdateSkin'
[string "@FrameXML\ActionBarController.lua"]:115: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton1:Hide()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\ActionButton.lua"]:364: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\OverrideActionBar.lua"]:222: in function `OverrideActionBar_Setup'
[string "@FrameXML\OverrideActionBar.lua"]:118: in function `OverrideActionBar_UpdateSkin'
[string "@FrameXML\OverrideActionBar.lua"]:88: in function <FrameXML\OverrideActionBar.lua:79>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton5:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'MultiBarBottomLeftButton3:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton3:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

Locals:
Skipped (In Encounter)

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'ActionButton7:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:329: in function `UpdateAction'
[string "@FrameXML\ActionBarController.lua"]:147: in function `ActionBarController_ResetToDefault'
[string "@FrameXML\ActionBarController.lua"]:136: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'ActionButton12:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:329: in function `UpdateAction'
[string "@FrameXML\ActionBarController.lua"]:147: in function `ActionBarController_ResetToDefault'
[string "@FrameXML\ActionBarController.lua"]:136: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'ActionButton4:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'ActionButton10:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:329: in function `UpdateAction'
[string "@FrameXML\ActionBarController.lua"]:147: in function `ActionBarController_ResetToDefault'
[string "@FrameXML\ActionBarController.lua"]:136: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton6:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:760: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:218: in function <FrameXML\ActionButton.lua:215>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'ActionButton12:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:329: in function `UpdateAction'
[string "@FrameXML\ActionBarController.lua"]:147: in function `ActionBarController_ResetToDefault'
[string "@FrameXML\ActionBarController.lua"]:136: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'ActionButton2:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:855: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'OverrideActionBarButton2:Hide()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\ActionButton.lua"]:364: in function <FrameXML\ActionButton.lua:333>
[string "=[C]"]: in function `Update'
[string "@FrameXML\ActionButton.lua"]:329: in function `UpdateAction'
[string "@FrameXML\ActionBarController.lua"]:147: in function `ActionBarController_ResetToDefault'
[string "@FrameXML\ActionBarController.lua"]:136: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>
[string "=[C]"]: in function `ChangeActionBarPage'
[string "@FrameXML\ActionButton.lua"]:194: in function `ActionBar_PageDown'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
[string "=[C]"]: ?

**Comment by frozn** [comment]
Same problem as #32 and #33.

I have done some research on this: It may have something to do with "taint" in wow. Here is a description: https://www.townlong-yak.com/taint.log/about

Unfortunately I have not been able to reproduce this issue so far. Maybe you can find out something with the mentioned taint log?

**Comment by laki28** [comment]
Here is the taint log. I hope it will help fix the taint bug.
[taint.zip](https://github.com/frozn/TipTac/files/8308117/taint.zip)

**Comment by frozn** [comment]
Perfect, I will have a look! 👍

**Comment by frozn** [comment]
Can you try this possible fix?

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8346022/TipTac-dev.zip)

**Comment by Ookami313** [comment]
Installed the provided dev version the other day. So far in the last two days I have not seen any Blocked errors so the changes you made very well may have resolved the problem. I would say that you can close this issue and if anything arises again I can either reopen this ticket to create another. Thanks for your hard work.

**Comment by frozn** [comment]
Fixed with release [v22.03.30](https://github.com/frozn/TipTac/releases/tag/v22.03.30).
