### ISSUE TITLE
Background and position looks off compared to original

### ISSUE THREAD

**Issue by Talimar** [frozn/TipTac#63]
As mentioned on Curse. Some comparison shots. Verified that settings were the same.

![Wow_Hwi4zexs3G](https://user-images.githubusercontent.com/21211868/155015483-0fa163b9-cd62-4e22-be62-4d0263609eb9.png)
![Wow_kufCPpnJyk](https://user-images.githubusercontent.com/21211868/155015500-0533b75e-e0e9-4584-9a9d-abc7861191e3.png)
![Wow_MQ3YeqsdtN](https://user-images.githubusercontent.com/21211868/155015532-6ef00714-7ed1-4099-a070-5d86c147df4b.png)
![Wow_rWb9RFxOC9](https://user-images.githubusercontent.com/21211868/155015553-363dad02-2c6b-4ece-8b7d-fe377d049722.png)

**Comment by frozn** [comment]
The tooltips in screenshot 2 and 4 are the default tooltips from wow. It seems that TipTac isn't even enabled. Please check this. Also check if you have installed the [latest release v22.02.19](https://github.com/frozn/TipTac/releases/tag/v22.02.19). It's probably a good idea to reinstall this version.

**Comment by Talimar** [comment]
That is how I want it. Here you can see what unit tooltip looks like in the same setup.
![Wow_U92N3RB5CM](https://user-images.githubusercontent.com/21211868/155020838-30d2e8b9-38c8-4d8d-9a02-9ee030d07e8f.png)

**Comment by frozn** [comment]
Did you read my last comment?

**Comment by Talimar** [comment]
Of course it's enabled otherwise I wouldn't be able to verify the settings are the same. This is the default unit tooltip:
![Wow_QULtQ1qNzD](https://user-images.githubusercontent.com/21211868/155068936-3fc339c9-8db7-44c7-8b16-542ef5ed409c.png)

And yes I used the latest version, twice.

**Comment by frozn** [comment]
It's still not clear to me where exactly the problem is. For example the 4 screenshots in your first comment: Which of them represents the "old correct state" and which of the them the "new wrong state"? What exactly seems wrong to you?

The appearance of the backdrop can be configured in "Backdrop". The anchoring, where the tooltip should appear (normal or mouse anchoring for example), can be configured under "Anchors".

The section "Special Tip Modification" in the description on curseforge is old I guess. The option "Hook Special Tips" doesn't even exist in the old version of TipTac on CF.

I would like to help you to solve your problem, but actually I don't have the necessary informations from you.

**Comment by Talimar** [comment]
Sure. So basically what I want is TipTac not hooking into any tooltip other than unit tooltip, like in my second post. Which is how it behaves with Curse version. 
I did not realize my other tooltips were default as I've been using this addon for who knows how long.

I forgot to take a picture of unit tooltip with your version but I assume it looked the same as Curse.

**Comment by frozn** [comment]
The standard GameTooltip is used in many places: Units, buttons on action bars, inventory, buffs, etc. Because the styling is applied to the standard GameTooltip, all places which uses this tooltip are affected.

**Comment by Talimar** [comment]
I don't know what to tell you then. I've been using it since Legion and it has never applied any styling to items and buffs before.
I'm pretty sure it always only applied to units and actionbuttons for me. Though I have always kept the itemref module disabled along with talents.

But I can live it the styling if you could help me with how to get the group finder and buff tooltips to appear in the same position as default instead of covering them. Thanks.

**Comment by frozn** [comment]
In this case make shure, that "Anchors->Frame Tip Type" is set to "Normal Anchor" and "Anchors->Frame Tip Point" is set to "Bottom Right".

**Comment by hobulian** [comment]
Also using this addon from WoD. Styling for buffs(for it's icon and border) added recently i think. But backdrop and border styling for items and spells was in legion too.

**Comment by Talimar** [comment]
Ok I deleted the savedvariables file and reinstalled. Seems to work fine now.
