### ISSUE TITLE
Patch day error

### ISSUE THREAD

**Issue by fraerie** [frozn/TipTac#64]
1x TipTacItemRef\ttItemRef.lua:1557: hooksecurefunc(): OnEnter is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@TipTacItemRef\ttItemRef.lua"]:1557: in function `?'
[string "@TipTacItemRef\ttItemRef.lua"]:198: in function <TipTacItemRef\ttItemRef.lua:198>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:531: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:712: in function `PlayerChoice_LoadUI'
[string "@FrameXML\UIParent.lua"]:2229: in function <FrameXML\UIParent.lua:1324>
[string "=[C]"]: ?

Locals:

**Comment by glassleo** [comment]
``PlayerChoiceTorghastOptionTemplateMixin:OnEnter()`` was removed in 9.2 so there's no need to hook the script to it...

(See [Blizzard_PlayerChoiceTorghastOptionTemplate.lua](https://github.com/Gethe/wow-ui-source/blob/978a1677c7825f6ddbf6a3f276ed61e61c6c970a/Interface/AddOns/Blizzard_PlayerChoice/Blizzard_PlayerChoiceTorghastOptionTemplate.lua))

Removing lines 1347-1349 in TipTacItemRef/ttItemRef.lua fixes this.

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

`PlayerChoiceTorghastOptionTemplateMixin:OnEnter()` has been moved to `PlayerChoicePowerChoiceTemplateMixin:OnEnter()`.

Fixed with release [v22.02.23](https://github.com/frozn/TipTac/releases/tag/v22.02.23)
