### ISSUE TITLE
[BUG] Player Tooltips are missing informations in the guild window if Raider.IO is active

### ISSUE THREAD

**Issue by JanRogge** [frozn/TipTac#67]
When using the Raider.IO Addon the player tooltips are missing everything except the Raider.IO information.

Normally over the score there should be the players name with guildrole and guild note.

![image](https://user-images.githubusercontent.com/11475491/155706643-47fb5831-fabb-47c6-92de-aab7766a831b.png)

**Comment by frozn** [comment]
I analyzed it so far that It think, the problem comes from RaiderIO. I created a bug in their repository: https://github.com/RaiderIO/raiderio-addon/issues/203

**Comment by frozn** [comment]
I implemented a workaround for this bug. The member list in guild & communities won't be mouse anchored if RaiderIO is present.
