### ISSUE TITLE
Aurora integration

### ISSUE THREAD

**Issue by JimJoyyy** [frozn/TipTac#68]
Greetings
in the old, shelved version it was possible to let Aurora overwrite tiptac styles by making sure it loads after it
![image](https://user-images.githubusercontent.com/100526962/155889387-d2460eb6-c627-43b9-a871-c8da73c9d9c0.png)

however, in this release tiptac always takes styling priority
![image](https://user-images.githubusercontent.com/100526962/155889455-e042e560-21df-4d64-9d5e-2ca2bd762d28.png)

I'm not gonna lie, im lazy, and making tiptac look good is a pain. Is there any sort of toggle that would allow style addons to overwrite tiptac? Is it just an aurora problem? (very likely). Am i just blind and cant find a setting? (also very likely)

My question in tl;dr is: how to make it look like the top one without having to pull my hair out for 5 hours 
OR, how to simply fix the setbackdrop in the abandoned version since it was the only major issue with it

While issues tab aint the best place for it, im out of ideas. Thanks in advance for any sort of answers

**Comment by frozn** [comment]
What is not quite clear to me: Why do you need/installed TipTac at all, if you want Aurora's styling?

**Comment by JimJoyyy** [comment]
im using tiptac mainly for the anchor and some additional information it provides

**Comment by NoBetaBoredom** [comment]
All you have to do to get TipTac to look like the first screenshot is to go to the "Backdrop" settings, choose "solid" for both background and border, tick the pixel perfect option, set insets to 1 and 1 and then set the background and border color to black (background to like 0.75 alpha).

**Comment by frozn** [comment]
Even though the problem is solved here, I opened (and solved) a feature request to disable all backdrop modifications: #70
