### ISSUE TITLE
ADDON_ACTION_BLOCKED error

### ISSUE THREAD

**Issue by Mordeaur** [frozn/TipTac#71]
It appears in combat.

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'DominosActionButton14:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:350: in function `Update'
[string "@FrameXML\ActionButton.lua"]:856: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

1x [ADDON_ACTION_BLOCKED] AddOn 'TipTac' tried to call the protected function 'MultiBarBottomLeftButton3:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:350: in function `Update'
[string "@FrameXML\ActionButton.lua"]:856: in function `OnEvent'
[string "@FrameXML\ActionButton.lua"]:266: in function <FrameXML\ActionButton.lua:258>

**Comment by frozn** [comment]
Same problem as #32.

In which case does the error occur? Do you mouseover a spell or something else in action bar? Can you reproduce this on a training dummy?

**Comment by Mordeaur** [comment]
> Same problem as #32.
> 
> In which case does the error occur? Do you mouseover a spell or something else in action bar? Can you reproduce this on a training dummy?

Hello, tried on dummy and yes error occurs when i mouseover a spell/ability in combat.

**Comment by frozn** [comment]
Do you use the standard action bars or do you use an addon to custimize these bars?

**Comment by Mordeaur** [comment]
> Hello again, i'm using dominos addon.

**Comment by frozn** [comment]
I installed Dominos and tested it on dummy. No errors on my side during combat during mouseover spells. Probably another addon or setting is involved here to trigger these error messages. 🤔

**Comment by Mordeaur** [comment]
Sorry I can't provide more data. Disabled every addon except dominos and error occured only with dominos. Even deleted some suspected weak auras to be sure but nothing has changed. It's nothing like game breaking bug so we can let it go i guess. :)

**Comment by frozn** [comment]
Can you try this possible fix?

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8346022/TipTac-dev.zip)

**Comment by frozn** [comment]
Fixed with release [v22.03.30](https://github.com/frozn/TipTac/releases/tag/v22.03.30).
