### ISSUE TITLE
Error occuring on login. 

### ISSUE THREAD

**Issue by gelsbern** [frozn/TipTac#72]
1x TipTacItemRef\ttItemRef.lua:186: Usage: <unnamed>:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[string "=[C]"]: in function `SetPoint'
[string "@TipTacItemRef\ttItemRef.lua"]:186: in function `CreateTooltipIcon'
[string "@TipTacItemRef\ttItemRef.lua"]:1529: in function `ApplyHooksToTips'
[string "@TipTacItemRef\ttItemRef.lua"]:1567: in function `HookTips'
[string "@TipTacItemRef\ttItemRef.lua"]:243: in function `?'
[string "@TipTacItemRef\ttItemRef.lua"]:198: in function <TipTacItemRef\ttItemRef.lua:198>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetSpellBookItem = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetHyperlink = <function> defined =[C]:-1
 SetShapeshift = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 ttIcon = <unnamed> {
 }
 SetAction = <function> defined =[C]:-1
 SetCraftItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetQuestRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 BottomOverlay = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 Show = <function> defined =[C]:-1
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 SetPetAction = <function> defined =[C]:-1
 SetUnitDebuff = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetLootItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetQuestItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 SetTrainerService = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 TopOverlay = <unnamed> {
 }
 SetMerchantCostItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 FadeOut = <function> defined @TipTac\ttCore.lua:1421
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 SetTradeTargetItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetTalent = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetTradePlayerItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetBuybackItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetSendMailItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 NineSlice = <unnamed> {
 }
 SetInventoryItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetTradeSkillItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetGuildBankItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 SetUnitAura = <function> defined =[C]:-1
 SetLootRollItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetAuctionSellItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 SetBagItem = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 updateTooltip = 0.200000

**Comment by frozn** [comment]
Please check the following options under "ItemRef":

- Icon Anchor (Default: BOTTOMLEFT)
- Icon Tooltip Anchor (Default: TOPLEFT)
- Icon Offset X (Default: 2.5)
- Icon Offset Y (Default: -2.5)

Are correct values specified here?

**Comment by gelsbern** [comment]
Yes, those are the values in ItemRef

**Comment by frozn** [comment]
I need more informations to reproduce this:

- Which version of TipTac do you use?
- Which WoW client do you use (Classic/BCC/SL)?
- Upload your file "TipTacItemRef\ttItemRef.lua" here on github.
- Upload your file "WTF\Account\<account name>\SavedVariables\TipTac.lua" with your settings here on github.

**Comment by gelsbern** [comment]
TicTac Version: 22:02:26
WoW BCC

Here are the files,  I had to rename them with a .txt extension to attach them.
[ttItemRef.lua,txt](https://github.com/frozn/TipTac/files/8346061/ttItemRef.lua.txt)
[TipTac.lua.txt](https://github.com/frozn/TipTac/files/8346065/TipTac.lua.txt)

**Comment by frozn** [comment]
Your "ttItemRef.lua" doesn't match the one in release 22.02.26.

Please redownload the latest version and replace the 4 folders: https://github.com/frozn/TipTac/releases
