### ISSUE TITLE
issue with tooltips when handynotes enabled

### ISSUE THREAD

**Issue by waggz81** [frozn/TipTac#74]
I have an issue with TipTac whenever I enable Handynotes and hover over certain quest rewards in the quest log. It does not happen with  anima items or other currencies like honor/conquest. It happens with items like gear and the rep items from weekly dungeon quests. I disabled all addons except TicTac, confirmed the tooltips worked, then enabled HandyNotes and the following LUA error occurs:

```Message: Interface\AddOns\TipTacItemRef\ttItemRef.lua:649: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: Tue Mar 29 22:48:46 2022
Count: 4
Stack: Interface\AddOns\TipTacItemRef\ttItemRef.lua:649: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfo'
[string "@Interface\AddOns\TipTacItemRef\ttItemRef.lua"]:649: in function <Interface\AddOns\TipTacItemRef\ttItemRef.lua:636>
[string "=[C]"]: in function `SetQuestLogItem'
[string "@Interface\FrameXML\QuestInfo.lua"]:1070: in function <Interface\FrameXML\QuestInfo.lua:1059>

Locals: (*temporary) = nil
```

This is using TipTac v22.02.23-release and HandNotes v1.6.5.

**Comment by waggz81** [comment]
Same applies with TomTom v3.0.6

**Comment by frozn** [comment]
Can't reproduce it e.g. with weekly dungeon quests with rep items in oribos. I also use HandyNotes, but this error didn't pop up. Curious, HandyNotes should have no impact on mouseover in questlog.

**Comment by waggz81** [comment]
Sorry, I can't reproduce with HandyNotes any longer either. I am guessing I had TomTom enabled still, because it is definitely the cause. Without TipTac enabled it won't even show any errors or tooltips when I mouseover with only TomTom enabled. I'll follow up with them.
