### ISSUE TITLE
v22.03.30 error report

### ISSUE THREAD

**Issue by Mariecle** [frozn/TipTac#75]
WoW ver. SL 9.2.0
use addon
Broker_Everything v4.2.9 , ChocolateBar v3.8.3 , Tiptac [v22.03.30]

Thank you

==================================================
1x TipTacItemRef\ttItemRef.lua:186: Usage: <unnamed>:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[string "=[C]"]: in function `SetPoint'
[string "@TipTacItemRef\ttItemRef.lua"]:186: in function `CreateTooltipIcon'
[string "@TipTacItemRef\ttItemRef.lua"]:1522: in function `ApplyHooksToTips'
[string "@TipTacItemRef\ttItemRef.lua"]:1560: in function `HookTips'
[string "@TipTacItemRef\ttItemRef.lua"]:243: in function `?'
[string "@TipTacItemRef\ttItemRef.lua"]:198: in function <TipTacItemRef\ttItemRef.lua:198>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 SetQuestPartyProgress = <function> defined =[C]:-1
 SetSpellBookItem = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 textLeft1Font = "GameTooltipHeaderText"
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 ItemTooltip = <unnamed> {
 }
 SetCurrencyToken = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 updateTooltipTimer = 0.200000
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 SetAzeriteEssence = <function> defined =[C]:-1
 SetToyByItemID = <function> defined =[C]:-1
 SetCompanionPet = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetQuestCurrency = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 TopOverlay = <unnamed> {
 }
 ClearLines = <function> defined =[C]:-1
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 Show = <function> defined =[C]:-1
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 SetUnitDebuff = <function> defined =[C]:-1
 SetAzeriteEssenceSlot = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetEnhancedConduit = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 FadeOut = <function> defined @TipTac\ttCore.lua:1445
 SetConduit = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetPetAction = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 BottomOverlay = <unnamed> {
 }
 SetSpellByID = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 textRight1Font = "GameTooltipHeaderText"
 ttIcon = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetHyperlink = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 SetQuestLogCurrency = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined @SmexyMats\SmexyCore.lua:66
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = nil

===================================================================================

7x TipTacItemRef\ttItemRef.lua:258: attempt to index field 'ttCount' (a nil value)
[string "@TipTacItemRef\ttItemRef.lua"]:258: in function `?'
[string "@TipTac\ttCore.lua"]:426: in function `SendElementEvent'
[string "@TipTac\ttCore.lua"]:748: in function `ApplySettings'
[string "@TipTac\ttCore.lua"]:522: in function `?'
[string "@TipTac\ttCore.lua"]:556: in function <TipTac\ttCore.lua:556>

Locals:
self = TipTacItemRef {
 0 = <userdata>
 ApplyHooksToTips = <function> defined @TipTacItemRef\ttItemRef.lua:1406
 ADDON_LOADED = <function> defined @TipTacItemRef\ttItemRef.lua:1564
 ApplyWorkaroundForFirstMouseover = <function> defined @TipTacItemRef\ttItemRef.lua:285
 SetBackdropBorderColorLocked = <function> defined @TipTacItemRef\ttItemRef.lua:1825
 HookTips = <function> defined @TipTacItemRef\ttItemRef.lua:1559
 name = "ItemRef"
 VARIABLES_LOADED = <function> defined @TipTacItemRef\ttItemRef.lua:231
 CreateTooltipIcon = <function> defined @TipTacItemRef\ttItemRef.lua:184
 OnApplyConfig = <function> defined @TipTacItemRef\ttItemRef.lua:252
 ApplyHooksToCFGDFI = <function> defined @TipTacItemRef\ttItemRef.lua:1532
 ApplyHooksToGIFIC = <function> defined @TipTacItemRef\ttItemRef.lua:1546
 SetHyperlink_Hook = <function> defined @TipTacItemRef\ttItemRef.lua:421
}
gameFont = "Fonts\2002.TTF"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = GameTooltip {
 }
 2 = ShoppingTooltip1 {
 }
 3 = ShoppingTooltip2 {
 }
 4 = ItemRefTooltip {
 }
 5 = ItemRefShoppingTooltip1 {
 }
 6 = ItemRefShoppingTooltip2 {
 }
 7 = EmbeddedItemTooltip {
 }
 8 = NamePlateTooltip {
 }
 9 = BattlePetTooltip {
 }
 10 = FloatingBattlePetTooltip {
 }
 11 = false
 12 = false
 13 = FloatingPetBattleAbilityTooltip {
 }
 14 = FriendsTooltip {
 }
 15 = false
 16 = LibDBIconTooltip {
 }
 17 = false
 18 = false
 19 = false
 20 = false
 21 = DropDownList1 {
 }
 22 = DropDownList2 {
 }
}
(for control) = 1
index = 1
tip = GameTooltip {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ttSetBackdropBorderColorLocked = true
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 Show = <function> defined =[C]:-1
 SetPetAction = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 FadeOut = <function> defined @TipTac\ttCore.lua:1445
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 SetSpellByID = <function> defined =[C]:-1
 ttIcon = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 NineSlice = <unnamed> {
 }
 SetCompanionPet = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetAction = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @TipTac\ttCore.lua:1648
 LeftEdge = <unnamed> {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 updateTooltipTimer = 0.200000
 SetBackdropBorderColor = <function> defined @TipTac\ttCore.lua:1656
 textRight2Font = "GameTooltipText"
 ClearLines = <function> defined =[C]:-1
 SetBackdrop = <function> defined @TipTac\ttCore.lua:1640
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 SetUnitDebuff = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetQuestItem = <function> defined =[C]:-1
 Center = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 SetToyByItemID = <function> defined =[C]:-1
 BottomEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 BottomLeftC
=========================================================================

5x ...s\Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0-49.lua:756: attempt to perform arithmetic on local 'topside' (a nil value)
[string "@Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0-49.lua"]:756: in function `UpdateScrolling'
[string "@Broker_Everything\shared.lua"]:412: in function `roundupTooltip'
[string "@Broker_Everything\modules/volume.lua"]:233: in function <Broker_Everything\modules/volume.lua:135>
[string "@Broker_Everything\modules/volume.lua"]:400: in function `OnEnter'
[string "@ChocolateBar\Chocolate.lua"]:266: in function <ChocolateBar\Chocolate.lua:235>

Locals:
self = <unnamed> {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 key = "VolumeTT"
 SetBackdropBorderColor = <function> defined @TipTac\ttCore.lua:1656
 RightEdge = <unnamed> {
 }
 ttSetBackdropBorderColorLocked = true
 scrollChild = <unnamed> {
 }
 ApplyBackdrop = <function> defined @TipTac\ttCore.lua:1632
 SetBackdrop = <function> defined @TipTac\ttCore.lua:1640
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 height = 379.310496
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 regularFont = GameTooltipText {
 }
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 BottomEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 headerFont = GameTooltipHeaderText {
 }
 BottomRightCorner = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 GetBackdropCoordValue = <function> defined @Blizzard_Deprecated\Deprecated_9_1_5.lua:15
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 BottomLeftCorner = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 NineSlice = <unnamed> {
 }
 ttSetBackdropLocked = true
 TopEdge = <unnamed> {
 }
 colspans = <table> {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 width = 247.904099
 ttGradient = <unnamed> {
 }
 lines = <table> {
 }
 ttSetBackdropColorLocked = true
 labelProvider = <table> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @TipTac\ttCore.lua:1648
 LeftEdge = <unnamed> {
 }
 columns = <table> {
 }
}
maxheight = 631.232813
scale = 1
topside = nil
bottomside = nil
screensize = 1052.054688
(*temporary) = UIParent {
 variablesLoaded = true
 SetScale = <function> defined =[C]:-1
 firstTimeLoaded = 1
 0 = <userdata>
}
(*temporary) = 1052.054688
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = <unnamed> {
 }
 2 = <unnamed> {
 }
 3 = <unnamed> {
 }
 4 = <unnamed> {
 }
 5 = <unnamed> {
 }
 6 = <unnamed> {
 }
 7 = <unnamed> {
 }
 8 = <unnamed> {
 }
 9 = <unnamed> {
 }
 10 = <unnamed> {
 }
 11 = <unnamed> {
 }
 12 = <unnamed> {
 }
 13 = <unnamed> {
 }
 14 = <unnamed> {
 }
 15 = <unnamed> {
 }
 16 = <unnamed> {
 }
 17 = <unnamed> {
 }
 18 = <unnamed> {
 }
 19 = <unnamed> {
 }
 20 = <unnamed> {
 }
 21 = <unnamed> {
 }
 22 = <unnamed> {
 }
}
(*temporary) = 22
(*temporary) = nil
(*temporary) = nil
(*temporary) = 22
(*temporary) = 23
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'topside' (a nil value)"
FixCellSizes = <function> defined @Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0.lua:901
layoutCleaner = <unnamed> {
 0 = <userdata>
 registry = <table> {
 }
 CleanupLayouts = <function> defined @Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0.lua:227
 RegisterForCleanup = <function> defined @Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0.lua:222
}
UIParent = UIParent {
 variablesLoaded = true
 SetScale = <function> defined =[C]:-1
 firstTimeLoaded = 1
 0 = <userdata>
}
TOOLTIP_PADDING = 10
CreateFrame = <function> defined =[C]:-1
BACKDROP_SLIDER_8_8 = <table> {
 bgFile = "Buttons\UI-SliderBar-Background"
 tileSize = 8
 edgeFile = "Buttons\UI-SliderBar-Border"
 tile = true
 edgeSize = 8
 tileEdge = true
 insets = <table> {
 }
}
slider_OnValueChanged = <function> defined @Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0.lua:722
tooltip_OnMouseWheel = <function> defined @Inter
-----------------------------------------------------------------------------------------------------------------------------

**Comment by frozn** [comment]
Can't reproduce the error message with the mentioned addons installed. Can you upload your "TipTacItemRef\ttItemRef.lua" here?

**Comment by Mariecle** [comment]
v22.03.30 no edit.
Then, I'll test more to see if it's a problem with other add-ons.

**Comment by Mariecle** [comment]
I found the cause.
Z-perl+Vuhdo+tiptac v22.03.30 
There's an error using it together.

I couldn't speak smoothly because I used a translator. I'm sorry.
thank you.

**Comment by frozn** [comment]
I installed Z-Perl and Vuhdo, but still no error messages. Perhaps this error occurs only with special settings in one of this addons?

**Comment by Mariecle** [comment]
I don't know about that yet. I don't think there's anything special. I'll report you when I find it.
Thank you

**Comment by frozn** [comment]
I could reproduce this error and fixed this issue with the current release [v22.04.15](https://github.com/frozn/TipTac/releases/tag/v22.04.15).
