### ISSUE TITLE
Errors when mouseover widget Bars

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#76]
This happened when i mouseovered pocopoc's energybar or stone-soup progression bar.

45x TipTac\ttCore.lua:1085: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `GetObjectType'
[string "@TipTac\ttCore.lua"]:1085: in function `ReApplyAnchorTypeForMouse'
[string "@TipTac\ttCore.lua"]:1329: in function <TipTac\ttCore.lua:1321>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua"]:102: in function `OnEnter'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua"]:590: in function <...Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:589>

Locals:
(*temporary) = EmbeddedItemTooltip {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ttSetBackdropBorderColorLocked = true
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 SetPetAction = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 ttGradient = <unnamed> {
 }
 PixelSnapDisabled = true
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 BottomOverlay = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 NineSlice = <unnamed> {
 }
 SetCompanionPet = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @TipTac\ttCore.lua:1671
 LeftEdge = <unnamed> {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 updateTooltipTimer = 0.200000
 SetBackdropBorderColor = <function> defined @TipTac\ttCore.lua:1679
 ttAnchorType = "mouse"
 textRight2Font = "GameTooltipText"
 ApplyBackdrop = <function> defined @TipTac\ttCore.lua:1655
 SetBackdrop = <function> defined @TipTac\ttCore.lua:1663
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 SetUnitDebuff = <function> defined =[C]:-1
 Center = <unnamed> {
 }
 SetQuestItem = <function> defined =[C]:-1
 SetAzeriteEssenceSlot = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 SetToyByItemID = <function> defined =[C]:-1
 TopLeftCorner = <unnamed> {
 }
 BottomFontString = <unnamed> {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 BottomLeftCorner = <unnamed> {
 }
 TextLeft1 = EmbeddedItemTooltipTextLeft1 {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 SetUnitBuff = <function> defined =[C]:-1
 SetEnhancedConduit = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetQuestLogItem = <function> defined =[C]:-1
 ttSetBackdropLocked = true
 TextRight1 = EmbeddedItemTooltipTextRight1 {
 }
 textLeft2Font = "GameTooltipText"
 BottomEdge = <unnamed> {
 }
 TextRight2 = EmbeddedItemTooltipTextRight2 {
 }
 TextLeft2 = EmbeddedItemTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetAction = <function> defined =[C]:-1
 ttSetBackdropColorLocked = true
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 ttAnchorPoint = "BOTTOMLEFT"
 SetQuestLogCurrency = <function> defined =[C]:-1
 TopRightCorner = <unnamed> {
 }
}

6x TipTac\ttCore.lua:1729: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `GetParent'
[string "@TipTac\ttCore.lua"]:1729: in function `SetCenterColor'
[string "@SharedXML\SharedTooltipTemplates.lua"]:52: in function <SharedXML\SharedTooltipTemplates.lua:41>
[string "=[C]"]: ?
[string "=[C]"]: in function `SharedTooltip_SetBackdropStyle'
[string "@FrameXML\GameTooltip.lua"]:413: in function <FrameXML\GameTooltip.lua:409>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua"]:109: in function `OnLeave'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua"]:595: in function <...Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:594>

Locals:
(*temporary) = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetBackdropBorderColor = <function> defined @TipTac\ttCore.lua:1720
 RightEdge = <unnamed> {
 }
 template = "Transparent"
 BottomEdge = <unnamed> {
 }
 SetBackdrop = <function> defined @TipTac\ttCore.lua:1704
 GetCenterColor = <function> defined @SharedXML\NineSlice.lua:231
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 SetCenterColor = <function> defined @TipTac\ttCore.lua:1728
 GetFrameLayoutTextureKit = <function> defined @SharedXML\NineSlice.lua:213
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 GetBorderColor = <function> defined @SharedXML\NineSlice.lua:249
 TopRightCorner = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 customBackdropAlpha = 0.750000
 0 = <userdata>
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 OnLoad = <function> defined @SharedXML\NineSlice.lua:217
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @TipTac\ttCore.lua:1696
 SetBorderColor = <function> defined @TipTac\ttCore.lua:1736
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 Center = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 GetFrameLayoutType = <function> defined @SharedXML\NineSlice.lua:209
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @TipTac\ttCore.lua:1712
 LeftEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
}

**Comment by hobulian** [comment]
https://imgur.com/a/sfMIIDC

**Comment by hobulian** [comment]
Just my customized codes made this one.

**Comment by hobulian** [comment]
After install dev on this page this still happened. But have process to reproduce. You have to mouseover stone soup's progress bar to see this error.

**Comment by frozn** [comment]
I will have a look...

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
