### ISSUE TITLE
LUA Error Retail 9.25 Transmog Window

### ISSUE THREAD

**Issue by Vilogity** [frozn/TipTac#82]
I get this Error when open the tranmog window

43x Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
[string "=[C]"]: in function `GetAppearanceSources'
[string "@FrameXML\CollectionsUtil.lua"]:76: in function `GetSortedAppearanceSources'
[string "@TipTacItemRef\ttItemRef.lua"]:1290: in function <TipTacItemRef\ttItemRef.lua:1285>
[string "=[C]"]: in function `RefreshAppearanceTooltip'
[string "@Blizzard_Collections\Blizzard_Wardrobe.lua"]:2272: in function `SetAppearanceTooltip'
[string "@Blizzard_Collections\Blizzard_Wardrobe.lua"]:2460: in function <...ceBlizzard_Collections\Blizzard_Wardrobe.lua:2436>
[string "=[C]"]: ?

Locals:
(*temporary) = "Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)"

**Comment by frozn** [comment]
Thanks for reporting this. Fixed in release [v22.06.02](https://github.com/frozn/TipTac/releases/tag/v22.06.02). 👍

**Comment by Vilogity** [comment]
@frozn 
Big THX fpr your unbelivable Support !!!
