### ISSUE TITLE
Separate options to show Icons for Items and Spells only

### ISSUE THREAD

**Issue by Desik** [frozn/TipTac#84]
Currently when you activate the option to show the icon it will show on both spells and items, would be nice to have an option to only show on items as I don't really see the point on showing the icon for spells, especially when you are already mouseovering the icon

A good addiction would be to detect if you are hovering a Icon and don't show the icon or a link and show the icon there, with options.

**Comment by frozn** [comment]
With option "ItemRef->Smart Icon Appearance" enabled the icon should only be displayed if it is not already visible where you are already mouseovering.
