### ISSUE TITLE
Mythic+ Rating

### ISSUE THREAD

**Issue by DaleHuntGB** [frozn/TipTac#86]
Hi there,

Any chance you can add Blizzard Mythic+ Rating to the tooltip?

I am aware of the RaiderIO AddOn but I'd prefer not to use that.

Cheers,

**Comment by DaleHuntGB** [comment]
Hey,

I have been trying to add this myself but having no particular luck.

I have, however, found the indicators that would need to be used in order to find the relevant information.

_Get Mythic+ Score_: `C_PlayerInfo.GetPlayerMythicPlusRatingSummary` -> **Argument**: Valid Unit (In/Out of Group).
_Get Mythic+ Score Color_: `C_ChallengeMode.GetDungeonScoreRarityColor` -> **Argument**: Dungeon Score

**Comment by frozn** [comment]
I digged into this, too. It seems, that you can only get your own overall dungeon score with `C_ChallengeMode.GetOverallDungeonScore()` or the leader's dungeon score in LFG tool with `C_LFGList.GetApplicantDungeonScoreForListing()`. A function for retrieving the dungeon score for other players seems not to exist.

I think this is the reason why raider io addon exists with its internal db with all player dungeon scores which are updated regularly.

**Comment by frozn** [comment]
I took another look at it. The 2 functions you mentioned will do the trick. I implemented this feature and added the new option "General->Show Mythic+ Dungeon Score" to show mythic+ dungeon score, see the latest release:

https://github.com/frozn/TipTac/releases/tag/v22.08.18

How about it?

**Comment by DaleHuntGB** [comment]
Appreciate the work. Testing it now but seems to be working perfectly.
