### ISSUE TITLE
Mouseover tooltip with icon missing

### ISSUE THREAD

**Issue by NayooZ** [frozn/TipTac#91]
Icon appears on the tooltip only if you click on the item
Icon does not appear on the tooltip if you mouseover the item (i.e. from a chat link)

![image](https://user-images.githubusercontent.com/37068647/188494250-25b2d4e2-fbb5-46bc-8059-77b9fb633d52.png)

**Comment by frozn** [comment]
If you enabled "ItemRef->Show Icon Texture and Stack Count" the icon for items in chat should always be visible. Do you have "ItemRef->Smart Icon Appearance" enabled? If so, disable it temporarily and check, if the icon appears. You should also check, if the addon files for the latest release are properly in place. Or do you use some addon, which replaces/enhances the default chat frame?

On my side a actually can't reproduce this behaviour unfortunately.

**Comment by NayooZ** [comment]
Ah ha, it was Smart Icon Appearance, now it works as intended - thankyou.
