### ISSUE TITLE
[wotlk] itemlevel option doesnt work

### ISSUE THREAD

**Issue by jarveson** [frozn/TipTac#95]
'show itemlevel' doesnt work in options,

ive noticed at least that commenting out or putting a 'if retail' type guard around below line fixes it, not sure if thats correct solution 
https://github.com/frozn/TipTac/blob/215c4d4706a56948a41b0ec70297d81de2e02168/TipTacItemRef/ttItemRef.lua#L1944

**Comment by frozn** [comment]
Thanks for reporting this! 👍

Fixed with new release [v22.09.17](https://github.com/frozn/TipTac/releases/tag/v22.09.17).

**Comment by jarveson** [comment]
thanks, works!
