### ISSUE TITLE
[wotlk] Latest version doesn't work.

### ISSUE THREAD

**Issue by zdinch** [frozn/TipTac#96]
Hello, I just updated to the latest version and it seems that the background of the tooltip does not work well.

![ss+(2022-09-18+at+12 10 03)](https://user-images.githubusercontent.com/84704512/190877981-30d58d04-da2d-4eb4-a0af-2407cc6609e5.png)

Thanks for keeping it!

**Comment by frozn** [comment]
If you open the options window (with "/tiptac"), which version is displayed here?

**Comment by zdinch** [comment]
Version 22.08.18

![ss+(2022-09-18+at+08 58 02)](https://user-images.githubusercontent.com/84704512/190889804-e8f8f106-f2cc-4e2c-8b28-039cc36046bf.png)

**Comment by frozn** [comment]
You're right, WowUp only recognize -Wrath as suffix for WotLKC. It seems, that WowUp pulls the latest release for BCC (v22.08.18) as a fallback.

I opened an issue for this on WowUp: https://github.com/WowUp/WowUp/issues/1303

**Comment by frozn** [comment]
Suffix -WOTLKC has been added to development branch of WowUp. It will be included in the next release. If this is available, the automatic updates for TipTac will work again.
