### ISSUE TITLE
TipTac [Dev Version] - Taint Error

### ISSUE THREAD

**Issue by DaleHuntGB** [frozn/TipTac#98]
Hi there,

Running Development Version on TipTac for the QueueStatusFrame skinning, ran into a few LUA errors during Mythic+.

![image](https://user-images.githubusercontent.com/95256492/191370902-5cb9f13a-861a-4609-8abc-2b7c18a90375.png)

--

![image](https://user-images.githubusercontent.com/95256492/191371020-45197586-31b4-4f86-ac7b-cb2ad78e1a98.png)

--

![image](https://user-images.githubusercontent.com/95256492/191371052-81c40c17-2e2a-4289-81d8-179a5b0d109c.png)

--

![image](https://user-images.githubusercontent.com/95256492/191371091-1f8e6aa7-61c1-443e-8646-30df22738ff4.png)

--

![image](https://user-images.githubusercontent.com/95256492/191371331-2eec242e-fd3b-4cab-8737-5b4f5b08e63c.png)

--

Seems to be mainly related to the Collections Journal.

Hope this helps and also, I am aware that the Development version will have some issues but still testing QueueStatusFrame, as stated above.

**Comment by frozn** [comment]
Fixed some ADDON_ACTION_BLOCKED-issues regarding toys with latest release [v22.10.14](https://github.com/frozn/TipTac/releases/tag/v22.10.14). I guess that this could also fix this problem.

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
