### ISSUE TITLE
ADDON_ACTION_FORBIDDEN caused by TipTac

### ISSUE THREAD

**Issue by zaphon** [frozn/TipTac#99]
I recently found out about this version of TipTac and started using it and encountered a strange bug. If I have TipTac loaded, I get the following error if I try and click a toy in the ToyBox more than once (example is the Scouting Maps, while it's learning one, I am spam clicking the next one so I can instantly start learning it as soon as one finishes, but I can reproduce this by just spam clicking the same one over and over (2 or 3 clicks is all it takes)).

> 7x [ADDON_ACTION_FORBIDDEN] AddOn 'Ace3' tried to call the protected function 'UseToy()'.
> [string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
> [string "=[C]"]: in function `UseToy'
> [string "@Blizzard_Collections\Blizzard_ToyBox.lua"]:181: in function `ToySpellButton_OnClick'
> [string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>
> 

Obviously the error doesn't point to TipTac, but this doesn't occur the moment I remove TipTac. The only code I even saw remotely related to the ToyBox doesn't seem to matter (I commented it out, error still occurs), and there's not much around OnClick either. So it's very strange, not sure why this would be occurring.

**Comment by frozn** [comment]
Thanks for reporting this. I will dig into this...
